/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define("npm_angular_bazel/src/ng_package/packager", ["require", "exports", "fs", "path", "shelljs"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    const fs = require("fs");
    const path = require("path");
    const shx = require("shelljs");
    function main(args) {
        // Exit immediately when encountering an error.
        shx.set('-e');
        // Keep track of whether an error has occured so that we can return an appropriate exit code.
        let errorHasOccured = false;
        // This utility expects all of its arguments to be specified in a params file generated by
        // bazel (see https://docs.bazel.build/versions/master/skylark/lib/Args.html#use_param_file).
        const paramFilePath = args[0];
        // Bazel params may be surrounded with quotes
        function unquoteParameter(s) { return s.replace(/^'(.*)'$/, '$1'); }
        // Parameters are specified in the file one per line.
        const params = fs.readFileSync(paramFilePath, 'utf-8').split('\n').map(unquoteParameter);
        const [
        // Output directory for the npm package.
        out, 
        // The package segment of the ng_package rule's label (e.g. 'package/common').
        srcDir, 
        // The bazel-bin dir joined with the srcDir (e.g. 'bazel-bin/package.common').
        // This is the intended output location for package artifacts.
        binDir, 
        // The bazel-genfiles dir joined with the srcDir (e.g. 'bazel-bin/package.common').
        genfilesDir, 
        // JSON data mapping each entry point to the generated bundle index and
        // flat module metadata, for example
        // {"@angular/core": {
        //     "index": "bazel-bin/packages/core/core.js",
        //     "typings": "bazel-bin/packages/core/core.d.ts",
        //     "metadata": "bazel-bin/packages/core/core.metadata.json"
        //  },
        // ...
        // }
        modulesManifestArg, 
        // Path to the package's README.md.
        readmeMd, 
        // List of rolled-up flat ES2015 modules
        fesm2015Arg, 
        // List of rolled-up flat ES5 modules
        fesm5Arg, 
        // List of individual ES2015 modules
        esm2015Arg, 
        // List of individual ES5 modules
        esm5Arg, 
        // List of all UMD bundles generated by rollup.
        bundlesArg, 
        // List of all files in the ng_package rule's srcs.
        srcsArg, 
        // List of all type definitions that need to packaged into the ng_package.
        typeDefinitionsArg, 
        // List of all files in the ng_package rule's data.
        dataArg, 
        // Path to the package's LICENSE.
        licenseFile, 
        // List of all dts bundles generated by the API extractor.
        dtsBundleArg, 
        // The dts bundle file suffix example: '.bundle.d.ts'
        dtsBundleFileSuffix,] = params;
        const fesm2015 = fesm2015Arg.split(',').filter(s => !!s);
        const fesm5 = fesm5Arg.split(',').filter(s => !!s);
        const esm2015 = esm2015Arg.split(',').filter(s => !!s);
        const esm5 = esm5Arg.split(',').filter(s => !!s);
        const bundles = bundlesArg.split(',').filter(s => !!s);
        const typeDefinitions = typeDefinitionsArg.split(',').filter(s => !!s);
        const srcs = srcsArg.split(',').filter(s => !!s);
        const dataFiles = dataArg.split(',').filter(s => !!s);
        const modulesManifest = JSON.parse(modulesManifestArg);
        const dtsBundles = dtsBundleArg.split(',').filter(s => !!s);
        if (readmeMd) {
            copyFile(readmeMd, out);
        }
        /**
         * Writes a file into the package based on its input path, relativizing to the package path.
         * @param inputPath Path to the file in the input tree.
         * @param fileContent Content of the file.
         */
        function writeFileFromInputPath(inputPath, fileContent) {
            // We want the relative path from the given file to its ancestor "root" directory.
            // This root depends on whether the file lives in the source tree (srcDir) as a basic file
            // input to ng_package, the bin output tree (binDir) as the output of another rule, or
            // the genfiles output tree (genfilesDir) as the output of a genrule.
            let rootDir;
            if (inputPath.includes(binDir)) {
                rootDir = binDir;
            }
            else if (inputPath.includes(genfilesDir)) {
                rootDir = genfilesDir;
            }
            else {
                rootDir = srcDir;
            }
            const outputPath = path.join(out, path.relative(rootDir, inputPath));
            // Always ensure that the target directory exists.
            shx.mkdir('-p', path.dirname(outputPath));
            fs.writeFileSync(outputPath, fileContent, 'utf-8');
        }
        /**
         * Copies a file into the package based on its input path, relativizing to the package path.
         * @param inputPath a path relative to the binDir, typically from a file in the deps[]
         */
        function copyFileFromInputPath(inputPath) {
            writeFileFromInputPath(inputPath, fs.readFileSync(inputPath, 'utf-8'));
        }
        /**
         * Relativize the path where a file is written.
         * @param file a path containing a re-rooted segment like .esm5 or .es6
         * @param suffix the re-rooted directory
         * @param outDir path where we copy the file, relative to the out
         */
        function writeEsmFile(file, suffix, outDir) {
            // Note that the specified file path is always using the posix path delimiter.
            const root = file.substr(0, file.lastIndexOf(`${suffix}/`) + suffix.length + 1);
            const rel = path.dirname(path.relative(path.join(root, srcDir), file));
            if (!rel.startsWith('..')) {
                copyFile(file, path.join(out, outDir), rel);
            }
        }
        esm2015.forEach(file => writeEsmFile(file, '.es6', 'esm2015'));
        esm5.forEach(file => writeEsmFile(file, '.esm5', 'esm5'));
        bundles.forEach(bundle => { copyFile(bundle, out, 'bundles'); });
        fesm2015.forEach(file => { copyFile(file, out, 'fesm2015'); });
        fesm5.forEach(file => { copyFile(file, out, 'fesm5'); });
        // Copy all type definitions into the package. This is necessary so that developers can use
        // the package with type definitions.
        typeDefinitions.forEach(f => writeFileFromInputPath(f, readTypingsAndStripAmdModule(f)));
        // Copy all `data` files into the package. These are files that aren't built by the ng_package
        // rule, but instead are just straight copied into the package, e.g. global CSS assets.
        dataFiles.forEach(f => copyFileFromInputPath(f));
        // Iterate through the entry point modules
        // We do this first because we also record new paths for the esm5 and esm2015 copies
        // of the index JS file, which we need to amend the package.json.
        Object.keys(modulesManifest).forEach(moduleName => {
            const moduleFiles = modulesManifest[moduleName];
            const relative = path.relative(binDir, moduleFiles['index']);
            moduleFiles['esm5_index'] = path.join(binDir, 'esm5', relative);
            moduleFiles['esm2015_index'] = path.join(binDir, 'esm2015', relative);
            // Metadata file is optional as entry-points can be also built
            // with the "ts_library" rule.
            const metadataFile = moduleFiles['metadata'];
            if (!metadataFile) {
                return;
            }
            const typingsOutFile = moduleFiles['typings'];
            // We only support all modules within a package to be dts bundled
            // ie: if @angular/common/http has flat dts, so should @angular/common
            if (dtsBundles.length) {
                const metadataContent = rewireMetadata(metadataFile, typingsOutFile);
                writeFileFromInputPath(metadataFile, metadataContent);
            }
            else {
                copyFileFromInputPath(metadataFile);
            }
        });
        const licenseBanner = licenseFile ? fs.readFileSync(licenseFile, 'utf-8') : '';
        dtsBundles.forEach(bundleFile => {
            const cleanDistPath = bundleFile.replace(dtsBundleFileSuffix, '.d.ts');
            // API extractor will not dedupe license comments from various files
            // this will remove all the license comments and append the license banner.
            const content = licenseBanner + '\n' +
                readTypingsAndStripAmdModule(bundleFile)
                    .replace(/(\/\*\*\s+\*\s\@license(((?!\*\/).|\s)*)\*\/)/gm, '');
            writeFileFromInputPath(cleanDistPath, content);
        });
        // Root package name (e.g. '@angular/common'), captures as we iterate through sources below.
        let rootPackageName = '';
        const packagesWithExistingPackageJson = new Set();
        for (const src of srcs) {
            if (src.includes(binDir) || src.includes(genfilesDir)) {
                errorHasOccured = true;
                console.error('The "srcs" for ng_package should not include output of other rules. Found:\n' +
                    `  ${src}`);
            }
            let content = fs.readFileSync(src, 'utf-8');
            // Modify package.json files as necessary for publishing
            if (path.basename(src) === 'package.json') {
                const packageJson = JSON.parse(content);
                content = amendPackageJson(src, packageJson, false);
                const packageName = packageJson['name'];
                packagesWithExistingPackageJson.add(packageName);
                // Keep track of the root package name, e.g. "@angular/common". We assume that the
                // root name will be shortest because secondary entry-points will append to it
                // (e.g. "@angular/common/http").
                if (!rootPackageName || packageName.length < rootPackageName.length) {
                    rootPackageName = packageJson['name'];
                }
            }
            writeFileFromInputPath(src, content);
        }
        // Generate extra files for secondary entry-points.
        Object.keys(modulesManifest).forEach(entryPointPackageName => {
            const entryPointName = entryPointPackageName.substr(rootPackageName.length + 1);
            if (!entryPointName)
                return;
            const metadataFilePath = modulesManifest[entryPointPackageName]['metadata'];
            if (metadataFilePath) {
                createMetadataReexportFile(entryPointName, modulesManifest[entryPointPackageName]['metadata'], entryPointPackageName);
            }
            createTypingsReexportFile(entryPointName, licenseBanner, modulesManifest[entryPointPackageName]['typings']);
            if (!packagesWithExistingPackageJson.has(entryPointPackageName)) {
                createEntryPointPackageJson(entryPointName, entryPointPackageName);
            }
        });
        return errorHasOccured ? 1 : 0;
        /**
         * Convert a binDir-relative path to srcDir-relative
         * @param from path to a file under the srcDir, like packages/core/testing/package.json
         * @param file path to a file under the binDir, like bazel-bin/core/testing/generated.js
         */
        function srcDirRelative(from, file) {
            const result = normalizeSeparators(path.relative(path.dirname(from), path.join(srcDir, path.relative(binDir, file))));
            if (result.startsWith('..'))
                return result;
            return `./${result}`;
        }
        function copyFile(file, baseDir, relative = '.') {
            const dir = path.join(baseDir, relative);
            shx.mkdir('-p', dir);
            shx.cp(file, dir);
            // Double-underscore is used to escape forward slash in FESM filenames.
            // See ng_package.bzl:
            //   fesm_output_filename = entry_point.replace("/", "__")
            // We need to unescape these.
            if (file.indexOf('__') >= 0) {
                const outputPath = path.join(dir, ...path.basename(file).split('__'));
                shx.mkdir('-p', path.dirname(outputPath));
                shx.mv(path.join(dir, path.basename(file)), outputPath);
                // if we are renaming the .js file, we'll also need to update the sourceMappingURL in the file
                if (file.endsWith('.js')) {
                    shx.chmod('+w', outputPath);
                    shx.sed('-i', `${path.basename(file)}.map`, `${path.basename(outputPath)}.map`, outputPath);
                }
            }
        }
        /**
         * Inserts or edits properties into the package.json file(s) in the package so that
         * they point to all the right generated artifacts.
         *
         * @param packageJson The path to the package.json file.
         * @param parsedPackage Parsed package.json content
         * @param isGeneratedPackageJson Whether the passed package.json has been generated.
         */
        function amendPackageJson(packageJson, parsedPackage, isGeneratedPackageJson) {
            const packageName = parsedPackage['name'];
            const moduleData = modulesManifest[packageName];
            // We don't want to modify the "package.json" if we guessed the entry-point
            // paths and there is a custom "package.json" for that package already. Module
            // data will be only undefined if the package name comes from a non-generated
            // "package.json". In that case we want to leave the file untouched as well.
            if (!moduleData || moduleData.guessedPaths && !isGeneratedPackageJson) {
                // Ideally we should throw here, as we got an entry point that doesn't
                // have flat module metadata / bundle index, so it may have been an
                // ng_module that's missing a module_name attribute.
                // However, @angular/compiler can't be an ng_module, as it's the internals
                // of the ngc compiler, yet we want to build an ng_package for it.
                // So ignore package.json files when we are missing data.
                console.error('WARNING: no module metadata for package', packageName);
                console.error('   Not updating the package.json file to point to it');
                console.error('   The ng_module for this package is possibly missing the module_name attribute ');
                return JSON.stringify(parsedPackage, null, 2);
            }
            // Derive the paths to the files from the hard-coded names we gave them.
            // TODO(alexeagle): it would be better to transfer this information from the place
            // where we created the filenames, via the modulesManifestArg
            parsedPackage['main'] = getBundleName(packageName, 'bundles');
            parsedPackage['fesm5'] = getBundleName(packageName, 'fesm5');
            parsedPackage['fesm2015'] = getBundleName(packageName, 'fesm2015');
            parsedPackage['esm5'] = srcDirRelative(packageJson, moduleData['esm5_index']);
            parsedPackage['esm2015'] = srcDirRelative(packageJson, moduleData['esm2015_index']);
            parsedPackage['typings'] = srcDirRelative(packageJson, moduleData['typings']);
            // For now, we point the primary entry points at the fesm files, because of Webpack
            // performance issues with a large number of individual files.
            // TODO(iminar): resolve performance issues with the toolchain and point these to esm
            parsedPackage['module'] = parsedPackage['fesm5'];
            parsedPackage['es2015'] = parsedPackage['fesm2015'];
            return JSON.stringify(parsedPackage, null, 2);
        }
        // e.g. @angular/common/http/testing -> ../../bundles/common-http-testing.umd.js
        // or   @angular/common/http/testing -> ../../fesm5/http/testing.js
        function getBundleName(packageName, dir) {
            const parts = packageName.split('/');
            // Remove the scoped package part, like @angular if present
            const nameParts = packageName.startsWith('@') ? parts.splice(1) : parts;
            const relativePath = newArray(nameParts.length - 1, '..').join('/') || '.';
            let basename;
            if (dir === 'bundles') {
                basename = nameParts.join('-') + '.umd';
            }
            else if (nameParts.length === 1) {
                basename = nameParts[0];
            }
            else {
                basename = nameParts.slice(1).join('/');
            }
            return [relativePath, dir, basename + '.js'].join('/');
        }
        /** Creates metadata re-export file for a secondary entry-point. */
        function createMetadataReexportFile(entryPointName, metadataFile, packageName) {
            const inputPath = path.join(srcDir, `${entryPointName}.metadata.json`);
            writeFileFromInputPath(inputPath, JSON.stringify({
                '__symbolic': 'module',
                'version': 3,
                'metadata': {},
                'exports': [{ 'from': `${srcDirRelative(inputPath, metadataFile.replace(/.metadata.json$/, ''))}` }],
                'flatModuleIndexRedirect': true,
                'importAs': packageName
            }) + '\n');
        }
        /**
         * Creates a typings (d.ts) re-export file for a secondary-entry point,
         * e.g., `export * from './common/common'`
         */
        function createTypingsReexportFile(entryPointName, license, typingsFile) {
            const inputPath = path.join(srcDir, `${entryPointName}.d.ts`);
            const content = `${license}
export * from '${srcDirRelative(inputPath, typingsFile.replace(/\.d\.tsx?$/, ''))}';
`;
            writeFileFromInputPath(inputPath, content);
        }
        /**
         * Creates a package.json for a secondary entry-point.
         * @param dir The directory under which the package.json should be written.
         * @param entryPointPackageName The full package name for the entry point,
         *     e.g. '@angular/common/http'.
         */
        function createEntryPointPackageJson(dir, entryPointPackageName) {
            const pkgJson = path.join(srcDir, dir, 'package.json');
            const content = amendPackageJson(pkgJson, { name: entryPointPackageName }, true);
            writeFileFromInputPath(pkgJson, content);
        }
        /**
         * Normalizes the specified path by replacing backslash separators with Posix
         * forward slash separators.
         */
        function normalizeSeparators(path) { return path.replace(/\\/g, '/'); }
        /**
        * Rewires metadata to point to the flattened dts file.
        *
        * @param metadataPath the metadata file path
        * @param typingsPath the typings bundle entrypoint
        */
        function rewireMetadata(metadataPath, typingsPath) {
            const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf-8'));
            let typingsRelativePath = normalizeSeparators(path.relative(path.dirname(metadataPath), typingsPath));
            if (!typingsRelativePath.startsWith('..')) {
                typingsRelativePath = `./${typingsRelativePath}`;
            }
            typingsRelativePath = typingsRelativePath.replace('.d.ts', '');
            // the regexp here catches all relative paths such as:
            // ./src/core/foo.d.ts and ../src/core/foo.d.ts
            const relativePathRegex = /\.?\.\/[\w\.\-_\/]+/g;
            if (metadata.exports) {
                // Strip re-exports which are now self-references
                metadata.exports =
                    metadata.exports.filter((e) => !e.from.match(relativePathRegex));
            }
            return JSON.stringify(metadata).replace(relativePathRegex, typingsRelativePath);
        }
        /**
         * Strip the named AMD module for compatibility with non-bazel users from typings content
         * @param filePath dts file path
         */
        function readTypingsAndStripAmdModule(filePath) {
            return fs
                .readFileSync(filePath, 'utf-8')
                // Strip the named AMD module for compatibility with non-bazel users
                .replace(/^\/\/\/ <amd-module name=.*\/>[\r\n]+/gm, '');
        }
    }
    if (require.main === module) {
        process.exitCode = main(process.argv.slice(2));
    }
    function newArray(size, value) {
        const list = [];
        for (let i = 0; i < size; i++) {
            list.push(value);
        }
        return list;
    }
    exports.newArray = newArray;
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGFja2FnZXIuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi8uLi8uLi8uLi9wYWNrYWdlcy9iYXplbC9zcmMvbmdfcGFja2FnZS9wYWNrYWdlci50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7O0dBTUc7Ozs7Ozs7Ozs7OztJQUVILHlCQUF5QjtJQUN6Qiw2QkFBNkI7SUFDN0IsK0JBQStCO0lBRS9CLFNBQVMsSUFBSSxDQUFDLElBQWM7UUFDMUIsK0NBQStDO1FBQy9DLEdBQUcsQ0FBQyxHQUFHLENBQUMsSUFBSSxDQUFDLENBQUM7UUFFZCw2RkFBNkY7UUFDN0YsSUFBSSxlQUFlLEdBQUcsS0FBSyxDQUFDO1FBRTVCLDBGQUEwRjtRQUMxRiw2RkFBNkY7UUFDN0YsTUFBTSxhQUFhLEdBQUcsSUFBSSxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBRTlCLDZDQUE2QztRQUM3QyxTQUFTLGdCQUFnQixDQUFDLENBQVMsSUFBSSxPQUFPLENBQUMsQ0FBQyxPQUFPLENBQUMsVUFBVSxFQUFFLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUU1RSxxREFBcUQ7UUFDckQsTUFBTSxNQUFNLEdBQUcsRUFBRSxDQUFDLFlBQVksQ0FBQyxhQUFhLEVBQUUsT0FBTyxDQUFDLENBQUMsS0FBSyxDQUFDLElBQUksQ0FBQyxDQUFDLEdBQUcsQ0FBQyxnQkFBZ0IsQ0FBQyxDQUFDO1FBRXpGLE1BQU07UUFDRix3Q0FBd0M7UUFDeEMsR0FBRztRQUVILDhFQUE4RTtRQUM5RSxNQUFNO1FBRU4sOEVBQThFO1FBQzlFLDhEQUE4RDtRQUM5RCxNQUFNO1FBRU4sbUZBQW1GO1FBQ25GLFdBQVc7UUFFWCx1RUFBdUU7UUFDdkUsb0NBQW9DO1FBQ3BDLHNCQUFzQjtRQUN0QixrREFBa0Q7UUFDbEQsc0RBQXNEO1FBQ3RELCtEQUErRDtRQUMvRCxNQUFNO1FBQ04sTUFBTTtRQUNOLElBQUk7UUFDSixrQkFBa0I7UUFFbEIsbUNBQW1DO1FBQ25DLFFBQVE7UUFFUix3Q0FBd0M7UUFDeEMsV0FBVztRQUVYLHFDQUFxQztRQUNyQyxRQUFRO1FBRVIsb0NBQW9DO1FBQ3BDLFVBQVU7UUFFVixpQ0FBaUM7UUFDakMsT0FBTztRQUVQLCtDQUErQztRQUMvQyxVQUFVO1FBRVYsbURBQW1EO1FBQ25ELE9BQU87UUFFUCwwRUFBMEU7UUFDMUUsa0JBQWtCO1FBRWxCLG1EQUFtRDtRQUNuRCxPQUFPO1FBRVAsaUNBQWlDO1FBQ2pDLFdBQVc7UUFFWCwwREFBMEQ7UUFDMUQsWUFBWTtRQUVaLHFEQUFxRDtRQUNyRCxtQkFBbUIsRUFDdEIsR0FBRyxNQUFNLENBQUM7UUFFWCxNQUFNLFFBQVEsR0FBRyxXQUFXLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUN6RCxNQUFNLEtBQUssR0FBRyxRQUFRLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUNuRCxNQUFNLE9BQU8sR0FBRyxVQUFVLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUN2RCxNQUFNLElBQUksR0FBRyxPQUFPLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUNqRCxNQUFNLE9BQU8sR0FBRyxVQUFVLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUN2RCxNQUFNLGVBQWUsR0FBRyxrQkFBa0IsQ0FBQyxLQUFLLENBQUMsR0FBRyxDQUFDLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBQ3ZFLE1BQU0sSUFBSSxHQUFHLE9BQU8sQ0FBQyxLQUFLLENBQUMsR0FBRyxDQUFDLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBQ2pELE1BQU0sU0FBUyxHQUFhLE9BQU8sQ0FBQyxLQUFLLENBQUMsR0FBRyxDQUFDLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBQ2hFLE1BQU0sZUFBZSxHQUFHLElBQUksQ0FBQyxLQUFLLENBQUMsa0JBQWtCLENBQUMsQ0FBQztRQUN2RCxNQUFNLFVBQVUsR0FBYSxZQUFZLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUV0RSxJQUFJLFFBQVEsRUFBRTtZQUNaLFFBQVEsQ0FBQyxRQUFRLEVBQUUsR0FBRyxDQUFDLENBQUM7U0FDekI7UUFFRDs7OztXQUlHO1FBQ0gsU0FBUyxzQkFBc0IsQ0FBQyxTQUFpQixFQUFFLFdBQW1CO1lBQ3BFLGtGQUFrRjtZQUNsRiwwRkFBMEY7WUFDMUYsc0ZBQXNGO1lBQ3RGLHFFQUFxRTtZQUNyRSxJQUFJLE9BQWUsQ0FBQztZQUNwQixJQUFJLFNBQVMsQ0FBQyxRQUFRLENBQUMsTUFBTSxDQUFDLEVBQUU7Z0JBQzlCLE9BQU8sR0FBRyxNQUFNLENBQUM7YUFDbEI7aUJBQU0sSUFBSSxTQUFTLENBQUMsUUFBUSxDQUFDLFdBQVcsQ0FBQyxFQUFFO2dCQUMxQyxPQUFPLEdBQUcsV0FBVyxDQUFDO2FBQ3ZCO2lCQUFNO2dCQUNMLE9BQU8sR0FBRyxNQUFNLENBQUM7YUFDbEI7WUFFRCxNQUFNLFVBQVUsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLEdBQUcsRUFBRSxJQUFJLENBQUMsUUFBUSxDQUFDLE9BQU8sRUFBRSxTQUFTLENBQUMsQ0FBQyxDQUFDO1lBRXJFLGtEQUFrRDtZQUNsRCxHQUFHLENBQUMsS0FBSyxDQUFDLElBQUksRUFBRSxJQUFJLENBQUMsT0FBTyxDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUM7WUFDMUMsRUFBRSxDQUFDLGFBQWEsQ0FBQyxVQUFVLEVBQUUsV0FBVyxFQUFFLE9BQU8sQ0FBQyxDQUFDO1FBQ3JELENBQUM7UUFFRDs7O1dBR0c7UUFDSCxTQUFTLHFCQUFxQixDQUFDLFNBQWlCO1lBQzlDLHNCQUFzQixDQUFDLFNBQVMsRUFBRSxFQUFFLENBQUMsWUFBWSxDQUFDLFNBQVMsRUFBRSxPQUFPLENBQUMsQ0FBQyxDQUFDO1FBQ3pFLENBQUM7UUFFRDs7Ozs7V0FLRztRQUNILFNBQVMsWUFBWSxDQUFDLElBQVksRUFBRSxNQUFjLEVBQUUsTUFBYztZQUNoRSw4RUFBOEU7WUFDOUUsTUFBTSxJQUFJLEdBQUcsSUFBSSxDQUFDLE1BQU0sQ0FBQyxDQUFDLEVBQUUsSUFBSSxDQUFDLFdBQVcsQ0FBQyxHQUFHLE1BQU0sR0FBRyxDQUFDLEdBQUcsTUFBTSxDQUFDLE1BQU0sR0FBRyxDQUFDLENBQUMsQ0FBQztZQUNoRixNQUFNLEdBQUcsR0FBRyxJQUFJLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxRQUFRLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxJQUFJLEVBQUUsTUFBTSxDQUFDLEVBQUUsSUFBSSxDQUFDLENBQUMsQ0FBQztZQUN2RSxJQUFJLENBQUMsR0FBRyxDQUFDLFVBQVUsQ0FBQyxJQUFJLENBQUMsRUFBRTtnQkFDekIsUUFBUSxDQUFDLElBQUksRUFBRSxJQUFJLENBQUMsSUFBSSxDQUFDLEdBQUcsRUFBRSxNQUFNLENBQUMsRUFBRSxHQUFHLENBQUMsQ0FBQzthQUM3QztRQUNILENBQUM7UUFFRCxPQUFPLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxFQUFFLENBQUMsWUFBWSxDQUFDLElBQUksRUFBRSxNQUFNLEVBQUUsU0FBUyxDQUFDLENBQUMsQ0FBQztRQUMvRCxJQUFJLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxFQUFFLENBQUMsWUFBWSxDQUFDLElBQUksRUFBRSxPQUFPLEVBQUUsTUFBTSxDQUFDLENBQUMsQ0FBQztRQUUxRCxPQUFPLENBQUMsT0FBTyxDQUFDLE1BQU0sQ0FBQyxFQUFFLEdBQUcsUUFBUSxDQUFDLE1BQU0sRUFBRSxHQUFHLEVBQUUsU0FBUyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUNqRSxRQUFRLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxFQUFFLEdBQUcsUUFBUSxDQUFDLElBQUksRUFBRSxHQUFHLEVBQUUsVUFBVSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUMvRCxLQUFLLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxFQUFFLEdBQUcsUUFBUSxDQUFDLElBQUksRUFBRSxHQUFHLEVBQUUsT0FBTyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUV6RCwyRkFBMkY7UUFDM0YscUNBQXFDO1FBQ3JDLGVBQWUsQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxzQkFBc0IsQ0FBQyxDQUFDLEVBQUUsNEJBQTRCLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBRXpGLDhGQUE4RjtRQUM5Rix1RkFBdUY7UUFDdkYsU0FBUyxDQUFDLE9BQU8sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLHFCQUFxQixDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7UUFFakQsMENBQTBDO1FBQzFDLG9GQUFvRjtRQUNwRixpRUFBaUU7UUFDakUsTUFBTSxDQUFDLElBQUksQ0FBQyxlQUFlLENBQUMsQ0FBQyxPQUFPLENBQUMsVUFBVSxDQUFDLEVBQUU7WUFDaEQsTUFBTSxXQUFXLEdBQUcsZUFBZSxDQUFDLFVBQVUsQ0FBQyxDQUFDO1lBQ2hELE1BQU0sUUFBUSxHQUFHLElBQUksQ0FBQyxRQUFRLENBQUMsTUFBTSxFQUFFLFdBQVcsQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDO1lBRTdELFdBQVcsQ0FBQyxZQUFZLENBQUMsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLE1BQU0sRUFBRSxNQUFNLEVBQUUsUUFBUSxDQUFDLENBQUM7WUFDaEUsV0FBVyxDQUFDLGVBQWUsQ0FBQyxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsTUFBTSxFQUFFLFNBQVMsRUFBRSxRQUFRLENBQUMsQ0FBQztZQUV0RSw4REFBOEQ7WUFDOUQsOEJBQThCO1lBQzlCLE1BQU0sWUFBWSxHQUFHLFdBQVcsQ0FBQyxVQUFVLENBQUMsQ0FBQztZQUM3QyxJQUFJLENBQUMsWUFBWSxFQUFFO2dCQUNqQixPQUFPO2FBQ1I7WUFFRCxNQUFNLGNBQWMsR0FBRyxXQUFXLENBQUMsU0FBUyxDQUFDLENBQUM7WUFDOUMsaUVBQWlFO1lBQ2pFLHNFQUFzRTtZQUN0RSxJQUFJLFVBQVUsQ0FBQyxNQUFNLEVBQUU7Z0JBQ3JCLE1BQU0sZUFBZSxHQUFHLGNBQWMsQ0FBQyxZQUFZLEVBQUUsY0FBYyxDQUFDLENBQUM7Z0JBQ3JFLHNCQUFzQixDQUFDLFlBQVksRUFBRSxlQUFlLENBQUMsQ0FBQzthQUN2RDtpQkFBTTtnQkFDTCxxQkFBcUIsQ0FBQyxZQUFZLENBQUMsQ0FBQzthQUNyQztRQUNILENBQUMsQ0FBQyxDQUFDO1FBRUgsTUFBTSxhQUFhLEdBQUcsV0FBVyxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsWUFBWSxDQUFDLFdBQVcsRUFBRSxPQUFPLENBQUMsQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDO1FBRS9FLFVBQVUsQ0FBQyxPQUFPLENBQUMsVUFBVSxDQUFDLEVBQUU7WUFDOUIsTUFBTSxhQUFhLEdBQUcsVUFBVSxDQUFDLE9BQU8sQ0FBQyxtQkFBbUIsRUFBRSxPQUFPLENBQUMsQ0FBQztZQUN2RSxvRUFBb0U7WUFDcEUsMkVBQTJFO1lBQzNFLE1BQU0sT0FBTyxHQUFHLGFBQWEsR0FBRyxJQUFJO2dCQUNoQyw0QkFBNEIsQ0FBQyxVQUFVLENBQUM7cUJBQ25DLE9BQU8sQ0FBQyxpREFBaUQsRUFBRSxFQUFFLENBQUMsQ0FBQztZQUV4RSxzQkFBc0IsQ0FBQyxhQUFhLEVBQUUsT0FBTyxDQUFDLENBQUM7UUFDakQsQ0FBQyxDQUFDLENBQUM7UUFFSCw0RkFBNEY7UUFDNUYsSUFBSSxlQUFlLEdBQUcsRUFBRSxDQUFDO1FBQ3pCLE1BQU0sK0JBQStCLEdBQUcsSUFBSSxHQUFHLEVBQVUsQ0FBQztRQUUxRCxLQUFLLE1BQU0sR0FBRyxJQUFJLElBQUksRUFBRTtZQUN0QixJQUFJLEdBQUcsQ0FBQyxRQUFRLENBQUMsTUFBTSxDQUFDLElBQUksR0FBRyxDQUFDLFFBQVEsQ0FBQyxXQUFXLENBQUMsRUFBRTtnQkFDckQsZUFBZSxHQUFHLElBQUksQ0FBQztnQkFDdkIsT0FBTyxDQUFDLEtBQUssQ0FDVCw4RUFBOEU7b0JBQzlFLEtBQUssR0FBRyxFQUFFLENBQUMsQ0FBQzthQUNqQjtZQUVELElBQUksT0FBTyxHQUFHLEVBQUUsQ0FBQyxZQUFZLENBQUMsR0FBRyxFQUFFLE9BQU8sQ0FBQyxDQUFDO1lBQzVDLHdEQUF3RDtZQUN4RCxJQUFJLElBQUksQ0FBQyxRQUFRLENBQUMsR0FBRyxDQUFDLEtBQUssY0FBYyxFQUFFO2dCQUN6QyxNQUFNLFdBQVcsR0FBRyxJQUFJLENBQUMsS0FBSyxDQUFDLE9BQU8sQ0FBQyxDQUFDO2dCQUN4QyxPQUFPLEdBQUcsZ0JBQWdCLENBQUMsR0FBRyxFQUFFLFdBQVcsRUFBRSxLQUFLLENBQUMsQ0FBQztnQkFFcEQsTUFBTSxXQUFXLEdBQUcsV0FBVyxDQUFDLE1BQU0sQ0FBQyxDQUFDO2dCQUN4QywrQkFBK0IsQ0FBQyxHQUFHLENBQUMsV0FBVyxDQUFDLENBQUM7Z0JBRWpELGtGQUFrRjtnQkFDbEYsOEVBQThFO2dCQUM5RSxpQ0FBaUM7Z0JBQ2pDLElBQUksQ0FBQyxlQUFlLElBQUksV0FBVyxDQUFDLE1BQU0sR0FBRyxlQUFlLENBQUMsTUFBTSxFQUFFO29CQUNuRSxlQUFlLEdBQUcsV0FBVyxDQUFDLE1BQU0sQ0FBQyxDQUFDO2lCQUN2QzthQUNGO1lBQ0Qsc0JBQXNCLENBQUMsR0FBRyxFQUFFLE9BQU8sQ0FBQyxDQUFDO1NBQ3RDO1FBRUQsbURBQW1EO1FBQ25ELE1BQU0sQ0FBQyxJQUFJLENBQUMsZUFBZSxDQUFDLENBQUMsT0FBTyxDQUFDLHFCQUFxQixDQUFDLEVBQUU7WUFDM0QsTUFBTSxjQUFjLEdBQUcscUJBQXFCLENBQUMsTUFBTSxDQUFDLGVBQWUsQ0FBQyxNQUFNLEdBQUcsQ0FBQyxDQUFDLENBQUM7WUFDaEYsSUFBSSxDQUFDLGNBQWM7Z0JBQUUsT0FBTztZQUU1QixNQUFNLGdCQUFnQixHQUFHLGVBQWUsQ0FBQyxxQkFBcUIsQ0FBQyxDQUFDLFVBQVUsQ0FBQyxDQUFDO1lBQzVFLElBQUksZ0JBQWdCLEVBQUU7Z0JBQ3BCLDBCQUEwQixDQUN0QixjQUFjLEVBQUUsZUFBZSxDQUFDLHFCQUFxQixDQUFDLENBQUMsVUFBVSxDQUFDLEVBQ2xFLHFCQUFxQixDQUFDLENBQUM7YUFDNUI7WUFFRCx5QkFBeUIsQ0FDckIsY0FBYyxFQUFFLGFBQWEsRUFBRSxlQUFlLENBQUMscUJBQXFCLENBQUMsQ0FBQyxTQUFTLENBQUMsQ0FBQyxDQUFDO1lBRXRGLElBQUksQ0FBQywrQkFBK0IsQ0FBQyxHQUFHLENBQUMscUJBQXFCLENBQUMsRUFBRTtnQkFDL0QsMkJBQTJCLENBQUMsY0FBYyxFQUFFLHFCQUFxQixDQUFDLENBQUM7YUFDcEU7UUFDSCxDQUFDLENBQUMsQ0FBQztRQUVILE9BQU8sZUFBZSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUUvQjs7OztXQUlHO1FBQ0gsU0FBUyxjQUFjLENBQUMsSUFBWSxFQUFFLElBQVk7WUFDaEQsTUFBTSxNQUFNLEdBQUcsbUJBQW1CLENBQzlCLElBQUksQ0FBQyxRQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBQyxJQUFJLENBQUMsRUFBRSxJQUFJLENBQUMsSUFBSSxDQUFDLE1BQU0sRUFBRSxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztZQUN2RixJQUFJLE1BQU0sQ0FBQyxVQUFVLENBQUMsSUFBSSxDQUFDO2dCQUFFLE9BQU8sTUFBTSxDQUFDO1lBQzNDLE9BQU8sS0FBSyxNQUFNLEVBQUUsQ0FBQztRQUN2QixDQUFDO1FBRUQsU0FBUyxRQUFRLENBQUMsSUFBWSxFQUFFLE9BQWUsRUFBRSxRQUFRLEdBQUcsR0FBRztZQUM3RCxNQUFNLEdBQUcsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxRQUFRLENBQUMsQ0FBQztZQUN6QyxHQUFHLENBQUMsS0FBSyxDQUFDLElBQUksRUFBRSxHQUFHLENBQUMsQ0FBQztZQUNyQixHQUFHLENBQUMsRUFBRSxDQUFDLElBQUksRUFBRSxHQUFHLENBQUMsQ0FBQztZQUNsQix1RUFBdUU7WUFDdkUsc0JBQXNCO1lBQ3RCLDBEQUEwRDtZQUMxRCw2QkFBNkI7WUFDN0IsSUFBSSxJQUFJLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxJQUFJLENBQUMsRUFBRTtnQkFDM0IsTUFBTSxVQUFVLEdBQUcsSUFBSSxDQUFDLElBQUksQ0FBQyxHQUFHLEVBQUUsR0FBRyxJQUFJLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxDQUFDLEtBQUssQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDO2dCQUN0RSxHQUFHLENBQUMsS0FBSyxDQUFDLElBQUksRUFBRSxJQUFJLENBQUMsT0FBTyxDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUM7Z0JBQzFDLEdBQUcsQ0FBQyxFQUFFLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxHQUFHLEVBQUUsSUFBSSxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsQ0FBQyxFQUFFLFVBQVUsQ0FBQyxDQUFDO2dCQUV4RCw4RkFBOEY7Z0JBQzlGLElBQUksSUFBSSxDQUFDLFFBQVEsQ0FBQyxLQUFLLENBQUMsRUFBRTtvQkFDeEIsR0FBRyxDQUFDLEtBQUssQ0FBQyxJQUFJLEVBQUUsVUFBVSxDQUFDLENBQUM7b0JBQzVCLEdBQUcsQ0FBQyxHQUFHLENBQUMsSUFBSSxFQUFFLEdBQUcsSUFBSSxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsTUFBTSxFQUFFLEdBQUcsSUFBSSxDQUFDLFFBQVEsQ0FBQyxVQUFVLENBQUMsTUFBTSxFQUFFLFVBQVUsQ0FBQyxDQUFDO2lCQUM3RjthQUNGO1FBQ0gsQ0FBQztRQUVEOzs7Ozs7O1dBT0c7UUFDSCxTQUFTLGdCQUFnQixDQUNyQixXQUFtQixFQUFFLGFBQXNDLEVBQzNELHNCQUErQjtZQUNqQyxNQUFNLFdBQVcsR0FBRyxhQUFhLENBQUMsTUFBTSxDQUFDLENBQUM7WUFDMUMsTUFBTSxVQUFVLEdBQUcsZUFBZSxDQUFDLFdBQVcsQ0FBQyxDQUFDO1lBRWhELDJFQUEyRTtZQUMzRSw4RUFBOEU7WUFDOUUsNkVBQTZFO1lBQzdFLDRFQUE0RTtZQUM1RSxJQUFJLENBQUMsVUFBVSxJQUFJLFVBQVUsQ0FBQyxZQUFZLElBQUksQ0FBQyxzQkFBc0IsRUFBRTtnQkFDckUsc0VBQXNFO2dCQUN0RSxtRUFBbUU7Z0JBQ25FLG9EQUFvRDtnQkFDcEQsMEVBQTBFO2dCQUMxRSxrRUFBa0U7Z0JBQ2xFLHlEQUF5RDtnQkFDekQsT0FBTyxDQUFDLEtBQUssQ0FBQyx5Q0FBeUMsRUFBRSxXQUFXLENBQUMsQ0FBQztnQkFDdEUsT0FBTyxDQUFDLEtBQUssQ0FBQyxzREFBc0QsQ0FBQyxDQUFDO2dCQUN0RSxPQUFPLENBQUMsS0FBSyxDQUNULGtGQUFrRixDQUFDLENBQUM7Z0JBQ3hGLE9BQU8sSUFBSSxDQUFDLFNBQVMsQ0FBQyxhQUFhLEVBQUUsSUFBSSxFQUFFLENBQUMsQ0FBQyxDQUFDO2FBQy9DO1lBRUQsd0VBQXdFO1lBQ3hFLGtGQUFrRjtZQUNsRiw2REFBNkQ7WUFDN0QsYUFBYSxDQUFDLE1BQU0sQ0FBQyxHQUFHLGFBQWEsQ0FBQyxXQUFXLEVBQUUsU0FBUyxDQUFDLENBQUM7WUFDOUQsYUFBYSxDQUFDLE9BQU8sQ0FBQyxHQUFHLGFBQWEsQ0FBQyxXQUFXLEVBQUUsT0FBTyxDQUFDLENBQUM7WUFDN0QsYUFBYSxDQUFDLFVBQVUsQ0FBQyxHQUFHLGFBQWEsQ0FBQyxXQUFXLEVBQUUsVUFBVSxDQUFDLENBQUM7WUFFbkUsYUFBYSxDQUFDLE1BQU0sQ0FBQyxHQUFHLGNBQWMsQ0FBQyxXQUFXLEVBQUUsVUFBVSxDQUFDLFlBQVksQ0FBQyxDQUFDLENBQUM7WUFDOUUsYUFBYSxDQUFDLFNBQVMsQ0FBQyxHQUFHLGNBQWMsQ0FBQyxXQUFXLEVBQUUsVUFBVSxDQUFDLGVBQWUsQ0FBQyxDQUFDLENBQUM7WUFDcEYsYUFBYSxDQUFDLFNBQVMsQ0FBQyxHQUFHLGNBQWMsQ0FBQyxXQUFXLEVBQUUsVUFBVSxDQUFDLFNBQVMsQ0FBQyxDQUFDLENBQUM7WUFFOUUsbUZBQW1GO1lBQ25GLDhEQUE4RDtZQUM5RCxxRkFBcUY7WUFDckYsYUFBYSxDQUFDLFFBQVEsQ0FBQyxHQUFHLGFBQWEsQ0FBQyxPQUFPLENBQUMsQ0FBQztZQUNqRCxhQUFhLENBQUMsUUFBUSxDQUFDLEdBQUcsYUFBYSxDQUFDLFVBQVUsQ0FBQyxDQUFDO1lBRXBELE9BQU8sSUFBSSxDQUFDLFNBQVMsQ0FBQyxhQUFhLEVBQUUsSUFBSSxFQUFFLENBQUMsQ0FBQyxDQUFDO1FBQ2hELENBQUM7UUFFRCxnRkFBZ0Y7UUFDaEYsbUVBQW1FO1FBQ25FLFNBQVMsYUFBYSxDQUFDLFdBQW1CLEVBQUUsR0FBVztZQUNyRCxNQUFNLEtBQUssR0FBRyxXQUFXLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDO1lBQ3JDLDJEQUEyRDtZQUMzRCxNQUFNLFNBQVMsR0FBRyxXQUFXLENBQUMsVUFBVSxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQUM7WUFDeEUsTUFBTSxZQUFZLEdBQUcsUUFBUSxDQUFDLFNBQVMsQ0FBQyxNQUFNLEdBQUcsQ0FBQyxFQUFFLElBQUksQ0FBQyxDQUFDLElBQUksQ0FBQyxHQUFHLENBQUMsSUFBSSxHQUFHLENBQUM7WUFDM0UsSUFBSSxRQUFnQixDQUFDO1lBQ3JCLElBQUksR0FBRyxLQUFLLFNBQVMsRUFBRTtnQkFDckIsUUFBUSxHQUFHLFNBQVMsQ0FBQyxJQUFJLENBQUMsR0FBRyxDQUFDLEdBQUcsTUFBTSxDQUFDO2FBQ3pDO2lCQUFNLElBQUksU0FBUyxDQUFDLE1BQU0sS0FBSyxDQUFDLEVBQUU7Z0JBQ2pDLFFBQVEsR0FBRyxTQUFTLENBQUMsQ0FBQyxDQUFDLENBQUM7YUFDekI7aUJBQU07Z0JBQ0wsUUFBUSxHQUFHLFNBQVMsQ0FBQyxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsSUFBSSxDQUFDLEdBQUcsQ0FBQyxDQUFDO2FBQ3pDO1lBQ0QsT0FBTyxDQUFDLFlBQVksRUFBRSxHQUFHLEVBQUUsUUFBUSxHQUFHLEtBQUssQ0FBQyxDQUFDLElBQUksQ0FBQyxHQUFHLENBQUMsQ0FBQztRQUN6RCxDQUFDO1FBRUQsbUVBQW1FO1FBQ25FLFNBQVMsMEJBQTBCLENBQy9CLGNBQXNCLEVBQUUsWUFBb0IsRUFBRSxXQUFtQjtZQUNuRSxNQUFNLFNBQVMsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLE1BQU0sRUFBRSxHQUFHLGNBQWMsZ0JBQWdCLENBQUMsQ0FBQztZQUN2RSxzQkFBc0IsQ0FBQyxTQUFTLEVBQUUsSUFBSSxDQUFDLFNBQVMsQ0FBQztnQkFDL0MsWUFBWSxFQUFFLFFBQVE7Z0JBQ3RCLFNBQVMsRUFBRSxDQUFDO2dCQUNaLFVBQVUsRUFBRSxFQUFFO2dCQUNkLFNBQVMsRUFDTCxDQUFDLEVBQUMsTUFBTSxFQUFFLEdBQUcsY0FBYyxDQUFDLFNBQVMsRUFBRSxZQUFZLENBQUMsT0FBTyxDQUFDLGlCQUFpQixFQUFFLEVBQUUsQ0FBQyxDQUFDLEVBQUUsRUFBQyxDQUFDO2dCQUMzRix5QkFBeUIsRUFBRSxJQUFJO2dCQUMvQixVQUFVLEVBQUUsV0FBVzthQUN4QixDQUFDLEdBQUcsSUFBSSxDQUFDLENBQUM7UUFDYixDQUFDO1FBRUQ7OztXQUdHO1FBQ0gsU0FBUyx5QkFBeUIsQ0FBQyxjQUFzQixFQUFFLE9BQWUsRUFBRSxXQUFtQjtZQUM3RixNQUFNLFNBQVMsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLE1BQU0sRUFBRSxHQUFHLGNBQWMsT0FBTyxDQUFDLENBQUM7WUFDOUQsTUFBTSxPQUFPLEdBQUcsR0FBRyxPQUFPO2lCQUNiLGNBQWMsQ0FBQyxTQUFTLEVBQUUsV0FBVyxDQUFDLE9BQU8sQ0FBQyxZQUFZLEVBQUUsRUFBRSxDQUFDLENBQUM7Q0FDaEYsQ0FBQztZQUNFLHNCQUFzQixDQUFDLFNBQVMsRUFBRSxPQUFPLENBQUMsQ0FBQztRQUM3QyxDQUFDO1FBRUQ7Ozs7O1dBS0c7UUFDSCxTQUFTLDJCQUEyQixDQUFDLEdBQVcsRUFBRSxxQkFBNkI7WUFDN0UsTUFBTSxPQUFPLEdBQUcsSUFBSSxDQUFDLElBQUksQ0FBQyxNQUFNLEVBQUUsR0FBRyxFQUFFLGNBQWMsQ0FBQyxDQUFDO1lBQ3ZELE1BQU0sT0FBTyxHQUFHLGdCQUFnQixDQUFDLE9BQU8sRUFBRSxFQUFDLElBQUksRUFBRSxxQkFBcUIsRUFBQyxFQUFFLElBQUksQ0FBQyxDQUFDO1lBQy9FLHNCQUFzQixDQUFDLE9BQU8sRUFBRSxPQUFPLENBQUMsQ0FBQztRQUMzQyxDQUFDO1FBRUQ7OztXQUdHO1FBQ0gsU0FBUyxtQkFBbUIsQ0FBQyxJQUFZLElBQVksT0FBTyxJQUFJLENBQUMsT0FBTyxDQUFDLEtBQUssRUFBRSxHQUFHLENBQUMsQ0FBQyxDQUFDLENBQUM7UUFFdkY7Ozs7O1VBS0U7UUFDRixTQUFTLGNBQWMsQ0FBQyxZQUFvQixFQUFFLFdBQW1CO1lBQy9ELE1BQU0sUUFBUSxHQUFHLElBQUksQ0FBQyxLQUFLLENBQUMsRUFBRSxDQUFDLFlBQVksQ0FBQyxZQUFZLEVBQUUsT0FBTyxDQUFDLENBQUMsQ0FBQztZQUVwRSxJQUFJLG1CQUFtQixHQUNuQixtQkFBbUIsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxPQUFPLENBQUMsWUFBWSxDQUFDLEVBQUUsV0FBVyxDQUFDLENBQUMsQ0FBQztZQUNoRixJQUFJLENBQUMsbUJBQW1CLENBQUMsVUFBVSxDQUFDLElBQUksQ0FBQyxFQUFFO2dCQUN6QyxtQkFBbUIsR0FBRyxLQUFLLG1CQUFtQixFQUFFLENBQUM7YUFDbEQ7WUFFRCxtQkFBbUIsR0FBRyxtQkFBbUIsQ0FBQyxPQUFPLENBQUMsT0FBTyxFQUFFLEVBQUUsQ0FBQyxDQUFDO1lBRS9ELHNEQUFzRDtZQUN0RCwrQ0FBK0M7WUFDL0MsTUFBTSxpQkFBaUIsR0FBRyxzQkFBc0IsQ0FBQztZQUNqRCxJQUFJLFFBQVEsQ0FBQyxPQUFPLEVBQUU7Z0JBQ3BCLGlEQUFpRDtnQkFDakQsUUFBUSxDQUFDLE9BQU87b0JBQ1osUUFBUSxDQUFDLE9BQU8sQ0FBQyxNQUFNLENBQUMsQ0FBQyxDQUFpQixFQUFFLEVBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLGlCQUFpQixDQUFDLENBQUMsQ0FBQzthQUN0RjtZQUNELE9BQU8sSUFBSSxDQUFDLFNBQVMsQ0FBQyxRQUFRLENBQUMsQ0FBQyxPQUFPLENBQUMsaUJBQWlCLEVBQUUsbUJBQW1CLENBQUMsQ0FBQztRQUNsRixDQUFDO1FBRUQ7OztXQUdHO1FBQ0gsU0FBUyw0QkFBNEIsQ0FBQyxRQUFnQjtZQUNwRCxPQUFPLEVBQUU7aUJBQ0osWUFBWSxDQUFDLFFBQVEsRUFBRSxPQUFPLENBQUM7Z0JBQ2hDLG9FQUFvRTtpQkFDbkUsT0FBTyxDQUFDLHlDQUF5QyxFQUFFLEVBQUUsQ0FBQyxDQUFDO1FBQzlELENBQUM7SUFDSCxDQUFDO0lBRUQsSUFBSSxPQUFPLENBQUMsSUFBSSxLQUFLLE1BQU0sRUFBRTtRQUMzQixPQUFPLENBQUMsUUFBUSxHQUFHLElBQUksQ0FBQyxPQUFPLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO0tBQ2hEO0lBSUQsU0FBZ0IsUUFBUSxDQUFJLElBQVksRUFBRSxLQUFTO1FBQ2pELE1BQU0sSUFBSSxHQUFRLEVBQUUsQ0FBQztRQUNyQixLQUFLLElBQUksQ0FBQyxHQUFHLENBQUMsRUFBRSxDQUFDLEdBQUcsSUFBSSxFQUFFLENBQUMsRUFBRSxFQUFFO1lBQzdCLElBQUksQ0FBQyxJQUFJLENBQUMsS0FBTyxDQUFDLENBQUM7U0FDcEI7UUFDRCxPQUFPLElBQUksQ0FBQztJQUNkLENBQUM7SUFORCw0QkFNQyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxuICogQGxpY2Vuc2VcbiAqIENvcHlyaWdodCBHb29nbGUgSW5jLiBBbGwgUmlnaHRzIFJlc2VydmVkLlxuICpcbiAqIFVzZSBvZiB0aGlzIHNvdXJjZSBjb2RlIGlzIGdvdmVybmVkIGJ5IGFuIE1JVC1zdHlsZSBsaWNlbnNlIHRoYXQgY2FuIGJlXG4gKiBmb3VuZCBpbiB0aGUgTElDRU5TRSBmaWxlIGF0IGh0dHBzOi8vYW5ndWxhci5pby9saWNlbnNlXG4gKi9cblxuaW1wb3J0ICogYXMgZnMgZnJvbSAnZnMnO1xuaW1wb3J0ICogYXMgcGF0aCBmcm9tICdwYXRoJztcbmltcG9ydCAqIGFzIHNoeCBmcm9tICdzaGVsbGpzJztcblxuZnVuY3Rpb24gbWFpbihhcmdzOiBzdHJpbmdbXSk6IG51bWJlciB7XG4gIC8vIEV4aXQgaW1tZWRpYXRlbHkgd2hlbiBlbmNvdW50ZXJpbmcgYW4gZXJyb3IuXG4gIHNoeC5zZXQoJy1lJyk7XG5cbiAgLy8gS2VlcCB0cmFjayBvZiB3aGV0aGVyIGFuIGVycm9yIGhhcyBvY2N1cmVkIHNvIHRoYXQgd2UgY2FuIHJldHVybiBhbiBhcHByb3ByaWF0ZSBleGl0IGNvZGUuXG4gIGxldCBlcnJvckhhc09jY3VyZWQgPSBmYWxzZTtcblxuICAvLyBUaGlzIHV0aWxpdHkgZXhwZWN0cyBhbGwgb2YgaXRzIGFyZ3VtZW50cyB0byBiZSBzcGVjaWZpZWQgaW4gYSBwYXJhbXMgZmlsZSBnZW5lcmF0ZWQgYnlcbiAgLy8gYmF6ZWwgKHNlZSBodHRwczovL2RvY3MuYmF6ZWwuYnVpbGQvdmVyc2lvbnMvbWFzdGVyL3NreWxhcmsvbGliL0FyZ3MuaHRtbCN1c2VfcGFyYW1fZmlsZSkuXG4gIGNvbnN0IHBhcmFtRmlsZVBhdGggPSBhcmdzWzBdO1xuXG4gIC8vIEJhemVsIHBhcmFtcyBtYXkgYmUgc3Vycm91bmRlZCB3aXRoIHF1b3Rlc1xuICBmdW5jdGlvbiB1bnF1b3RlUGFyYW1ldGVyKHM6IHN0cmluZykgeyByZXR1cm4gcy5yZXBsYWNlKC9eJyguKiknJC8sICckMScpOyB9XG5cbiAgLy8gUGFyYW1ldGVycyBhcmUgc3BlY2lmaWVkIGluIHRoZSBmaWxlIG9uZSBwZXIgbGluZS5cbiAgY29uc3QgcGFyYW1zID0gZnMucmVhZEZpbGVTeW5jKHBhcmFtRmlsZVBhdGgsICd1dGYtOCcpLnNwbGl0KCdcXG4nKS5tYXAodW5xdW90ZVBhcmFtZXRlcik7XG5cbiAgY29uc3QgW1xuICAgICAgLy8gT3V0cHV0IGRpcmVjdG9yeSBmb3IgdGhlIG5wbSBwYWNrYWdlLlxuICAgICAgb3V0LFxuXG4gICAgICAvLyBUaGUgcGFja2FnZSBzZWdtZW50IG9mIHRoZSBuZ19wYWNrYWdlIHJ1bGUncyBsYWJlbCAoZS5nLiAncGFja2FnZS9jb21tb24nKS5cbiAgICAgIHNyY0RpcixcblxuICAgICAgLy8gVGhlIGJhemVsLWJpbiBkaXIgam9pbmVkIHdpdGggdGhlIHNyY0RpciAoZS5nLiAnYmF6ZWwtYmluL3BhY2thZ2UuY29tbW9uJykuXG4gICAgICAvLyBUaGlzIGlzIHRoZSBpbnRlbmRlZCBvdXRwdXQgbG9jYXRpb24gZm9yIHBhY2thZ2UgYXJ0aWZhY3RzLlxuICAgICAgYmluRGlyLFxuXG4gICAgICAvLyBUaGUgYmF6ZWwtZ2VuZmlsZXMgZGlyIGpvaW5lZCB3aXRoIHRoZSBzcmNEaXIgKGUuZy4gJ2JhemVsLWJpbi9wYWNrYWdlLmNvbW1vbicpLlxuICAgICAgZ2VuZmlsZXNEaXIsXG5cbiAgICAgIC8vIEpTT04gZGF0YSBtYXBwaW5nIGVhY2ggZW50cnkgcG9pbnQgdG8gdGhlIGdlbmVyYXRlZCBidW5kbGUgaW5kZXggYW5kXG4gICAgICAvLyBmbGF0IG1vZHVsZSBtZXRhZGF0YSwgZm9yIGV4YW1wbGVcbiAgICAgIC8vIHtcIkBhbmd1bGFyL2NvcmVcIjoge1xuICAgICAgLy8gICAgIFwiaW5kZXhcIjogXCJiYXplbC1iaW4vcGFja2FnZXMvY29yZS9jb3JlLmpzXCIsXG4gICAgICAvLyAgICAgXCJ0eXBpbmdzXCI6IFwiYmF6ZWwtYmluL3BhY2thZ2VzL2NvcmUvY29yZS5kLnRzXCIsXG4gICAgICAvLyAgICAgXCJtZXRhZGF0YVwiOiBcImJhemVsLWJpbi9wYWNrYWdlcy9jb3JlL2NvcmUubWV0YWRhdGEuanNvblwiXG4gICAgICAvLyAgfSxcbiAgICAgIC8vIC4uLlxuICAgICAgLy8gfVxuICAgICAgbW9kdWxlc01hbmlmZXN0QXJnLFxuXG4gICAgICAvLyBQYXRoIHRvIHRoZSBwYWNrYWdlJ3MgUkVBRE1FLm1kLlxuICAgICAgcmVhZG1lTWQsXG5cbiAgICAgIC8vIExpc3Qgb2Ygcm9sbGVkLXVwIGZsYXQgRVMyMDE1IG1vZHVsZXNcbiAgICAgIGZlc20yMDE1QXJnLFxuXG4gICAgICAvLyBMaXN0IG9mIHJvbGxlZC11cCBmbGF0IEVTNSBtb2R1bGVzXG4gICAgICBmZXNtNUFyZyxcblxuICAgICAgLy8gTGlzdCBvZiBpbmRpdmlkdWFsIEVTMjAxNSBtb2R1bGVzXG4gICAgICBlc20yMDE1QXJnLFxuXG4gICAgICAvLyBMaXN0IG9mIGluZGl2aWR1YWwgRVM1IG1vZHVsZXNcbiAgICAgIGVzbTVBcmcsXG5cbiAgICAgIC8vIExpc3Qgb2YgYWxsIFVNRCBidW5kbGVzIGdlbmVyYXRlZCBieSByb2xsdXAuXG4gICAgICBidW5kbGVzQXJnLFxuXG4gICAgICAvLyBMaXN0IG9mIGFsbCBmaWxlcyBpbiB0aGUgbmdfcGFja2FnZSBydWxlJ3Mgc3Jjcy5cbiAgICAgIHNyY3NBcmcsXG5cbiAgICAgIC8vIExpc3Qgb2YgYWxsIHR5cGUgZGVmaW5pdGlvbnMgdGhhdCBuZWVkIHRvIHBhY2thZ2VkIGludG8gdGhlIG5nX3BhY2thZ2UuXG4gICAgICB0eXBlRGVmaW5pdGlvbnNBcmcsXG5cbiAgICAgIC8vIExpc3Qgb2YgYWxsIGZpbGVzIGluIHRoZSBuZ19wYWNrYWdlIHJ1bGUncyBkYXRhLlxuICAgICAgZGF0YUFyZyxcblxuICAgICAgLy8gUGF0aCB0byB0aGUgcGFja2FnZSdzIExJQ0VOU0UuXG4gICAgICBsaWNlbnNlRmlsZSxcblxuICAgICAgLy8gTGlzdCBvZiBhbGwgZHRzIGJ1bmRsZXMgZ2VuZXJhdGVkIGJ5IHRoZSBBUEkgZXh0cmFjdG9yLlxuICAgICAgZHRzQnVuZGxlQXJnLFxuXG4gICAgICAvLyBUaGUgZHRzIGJ1bmRsZSBmaWxlIHN1ZmZpeCBleGFtcGxlOiAnLmJ1bmRsZS5kLnRzJ1xuICAgICAgZHRzQnVuZGxlRmlsZVN1ZmZpeCxcbiAgXSA9IHBhcmFtcztcblxuICBjb25zdCBmZXNtMjAxNSA9IGZlc20yMDE1QXJnLnNwbGl0KCcsJykuZmlsdGVyKHMgPT4gISFzKTtcbiAgY29uc3QgZmVzbTUgPSBmZXNtNUFyZy5zcGxpdCgnLCcpLmZpbHRlcihzID0+ICEhcyk7XG4gIGNvbnN0IGVzbTIwMTUgPSBlc20yMDE1QXJnLnNwbGl0KCcsJykuZmlsdGVyKHMgPT4gISFzKTtcbiAgY29uc3QgZXNtNSA9IGVzbTVBcmcuc3BsaXQoJywnKS5maWx0ZXIocyA9PiAhIXMpO1xuICBjb25zdCBidW5kbGVzID0gYnVuZGxlc0FyZy5zcGxpdCgnLCcpLmZpbHRlcihzID0+ICEhcyk7XG4gIGNvbnN0IHR5cGVEZWZpbml0aW9ucyA9IHR5cGVEZWZpbml0aW9uc0FyZy5zcGxpdCgnLCcpLmZpbHRlcihzID0+ICEhcyk7XG4gIGNvbnN0IHNyY3MgPSBzcmNzQXJnLnNwbGl0KCcsJykuZmlsdGVyKHMgPT4gISFzKTtcbiAgY29uc3QgZGF0YUZpbGVzOiBzdHJpbmdbXSA9IGRhdGFBcmcuc3BsaXQoJywnKS5maWx0ZXIocyA9PiAhIXMpO1xuICBjb25zdCBtb2R1bGVzTWFuaWZlc3QgPSBKU09OLnBhcnNlKG1vZHVsZXNNYW5pZmVzdEFyZyk7XG4gIGNvbnN0IGR0c0J1bmRsZXM6IHN0cmluZ1tdID0gZHRzQnVuZGxlQXJnLnNwbGl0KCcsJykuZmlsdGVyKHMgPT4gISFzKTtcblxuICBpZiAocmVhZG1lTWQpIHtcbiAgICBjb3B5RmlsZShyZWFkbWVNZCwgb3V0KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBXcml0ZXMgYSBmaWxlIGludG8gdGhlIHBhY2thZ2UgYmFzZWQgb24gaXRzIGlucHV0IHBhdGgsIHJlbGF0aXZpemluZyB0byB0aGUgcGFja2FnZSBwYXRoLlxuICAgKiBAcGFyYW0gaW5wdXRQYXRoIFBhdGggdG8gdGhlIGZpbGUgaW4gdGhlIGlucHV0IHRyZWUuXG4gICAqIEBwYXJhbSBmaWxlQ29udGVudCBDb250ZW50IG9mIHRoZSBmaWxlLlxuICAgKi9cbiAgZnVuY3Rpb24gd3JpdGVGaWxlRnJvbUlucHV0UGF0aChpbnB1dFBhdGg6IHN0cmluZywgZmlsZUNvbnRlbnQ6IHN0cmluZykge1xuICAgIC8vIFdlIHdhbnQgdGhlIHJlbGF0aXZlIHBhdGggZnJvbSB0aGUgZ2l2ZW4gZmlsZSB0byBpdHMgYW5jZXN0b3IgXCJyb290XCIgZGlyZWN0b3J5LlxuICAgIC8vIFRoaXMgcm9vdCBkZXBlbmRzIG9uIHdoZXRoZXIgdGhlIGZpbGUgbGl2ZXMgaW4gdGhlIHNvdXJjZSB0cmVlIChzcmNEaXIpIGFzIGEgYmFzaWMgZmlsZVxuICAgIC8vIGlucHV0IHRvIG5nX3BhY2thZ2UsIHRoZSBiaW4gb3V0cHV0IHRyZWUgKGJpbkRpcikgYXMgdGhlIG91dHB1dCBvZiBhbm90aGVyIHJ1bGUsIG9yXG4gICAgLy8gdGhlIGdlbmZpbGVzIG91dHB1dCB0cmVlIChnZW5maWxlc0RpcikgYXMgdGhlIG91dHB1dCBvZiBhIGdlbnJ1bGUuXG4gICAgbGV0IHJvb3REaXI6IHN0cmluZztcbiAgICBpZiAoaW5wdXRQYXRoLmluY2x1ZGVzKGJpbkRpcikpIHtcbiAgICAgIHJvb3REaXIgPSBiaW5EaXI7XG4gICAgfSBlbHNlIGlmIChpbnB1dFBhdGguaW5jbHVkZXMoZ2VuZmlsZXNEaXIpKSB7XG4gICAgICByb290RGlyID0gZ2VuZmlsZXNEaXI7XG4gICAgfSBlbHNlIHtcbiAgICAgIHJvb3REaXIgPSBzcmNEaXI7XG4gICAgfVxuXG4gICAgY29uc3Qgb3V0cHV0UGF0aCA9IHBhdGguam9pbihvdXQsIHBhdGgucmVsYXRpdmUocm9vdERpciwgaW5wdXRQYXRoKSk7XG5cbiAgICAvLyBBbHdheXMgZW5zdXJlIHRoYXQgdGhlIHRhcmdldCBkaXJlY3RvcnkgZXhpc3RzLlxuICAgIHNoeC5ta2RpcignLXAnLCBwYXRoLmRpcm5hbWUob3V0cHV0UGF0aCkpO1xuICAgIGZzLndyaXRlRmlsZVN5bmMob3V0cHV0UGF0aCwgZmlsZUNvbnRlbnQsICd1dGYtOCcpO1xuICB9XG5cbiAgLyoqXG4gICAqIENvcGllcyBhIGZpbGUgaW50byB0aGUgcGFja2FnZSBiYXNlZCBvbiBpdHMgaW5wdXQgcGF0aCwgcmVsYXRpdml6aW5nIHRvIHRoZSBwYWNrYWdlIHBhdGguXG4gICAqIEBwYXJhbSBpbnB1dFBhdGggYSBwYXRoIHJlbGF0aXZlIHRvIHRoZSBiaW5EaXIsIHR5cGljYWxseSBmcm9tIGEgZmlsZSBpbiB0aGUgZGVwc1tdXG4gICAqL1xuICBmdW5jdGlvbiBjb3B5RmlsZUZyb21JbnB1dFBhdGgoaW5wdXRQYXRoOiBzdHJpbmcpIHtcbiAgICB3cml0ZUZpbGVGcm9tSW5wdXRQYXRoKGlucHV0UGF0aCwgZnMucmVhZEZpbGVTeW5jKGlucHV0UGF0aCwgJ3V0Zi04JykpO1xuICB9XG5cbiAgLyoqXG4gICAqIFJlbGF0aXZpemUgdGhlIHBhdGggd2hlcmUgYSBmaWxlIGlzIHdyaXR0ZW4uXG4gICAqIEBwYXJhbSBmaWxlIGEgcGF0aCBjb250YWluaW5nIGEgcmUtcm9vdGVkIHNlZ21lbnQgbGlrZSAuZXNtNSBvciAuZXM2XG4gICAqIEBwYXJhbSBzdWZmaXggdGhlIHJlLXJvb3RlZCBkaXJlY3RvcnlcbiAgICogQHBhcmFtIG91dERpciBwYXRoIHdoZXJlIHdlIGNvcHkgdGhlIGZpbGUsIHJlbGF0aXZlIHRvIHRoZSBvdXRcbiAgICovXG4gIGZ1bmN0aW9uIHdyaXRlRXNtRmlsZShmaWxlOiBzdHJpbmcsIHN1ZmZpeDogc3RyaW5nLCBvdXREaXI6IHN0cmluZykge1xuICAgIC8vIE5vdGUgdGhhdCB0aGUgc3BlY2lmaWVkIGZpbGUgcGF0aCBpcyBhbHdheXMgdXNpbmcgdGhlIHBvc2l4IHBhdGggZGVsaW1pdGVyLlxuICAgIGNvbnN0IHJvb3QgPSBmaWxlLnN1YnN0cigwLCBmaWxlLmxhc3RJbmRleE9mKGAke3N1ZmZpeH0vYCkgKyBzdWZmaXgubGVuZ3RoICsgMSk7XG4gICAgY29uc3QgcmVsID0gcGF0aC5kaXJuYW1lKHBhdGgucmVsYXRpdmUocGF0aC5qb2luKHJvb3QsIHNyY0RpciksIGZpbGUpKTtcbiAgICBpZiAoIXJlbC5zdGFydHNXaXRoKCcuLicpKSB7XG4gICAgICBjb3B5RmlsZShmaWxlLCBwYXRoLmpvaW4ob3V0LCBvdXREaXIpLCByZWwpO1xuICAgIH1cbiAgfVxuXG4gIGVzbTIwMTUuZm9yRWFjaChmaWxlID0+IHdyaXRlRXNtRmlsZShmaWxlLCAnLmVzNicsICdlc20yMDE1JykpO1xuICBlc201LmZvckVhY2goZmlsZSA9PiB3cml0ZUVzbUZpbGUoZmlsZSwgJy5lc201JywgJ2VzbTUnKSk7XG5cbiAgYnVuZGxlcy5mb3JFYWNoKGJ1bmRsZSA9PiB7IGNvcHlGaWxlKGJ1bmRsZSwgb3V0LCAnYnVuZGxlcycpOyB9KTtcbiAgZmVzbTIwMTUuZm9yRWFjaChmaWxlID0+IHsgY29weUZpbGUoZmlsZSwgb3V0LCAnZmVzbTIwMTUnKTsgfSk7XG4gIGZlc201LmZvckVhY2goZmlsZSA9PiB7IGNvcHlGaWxlKGZpbGUsIG91dCwgJ2Zlc201Jyk7IH0pO1xuXG4gIC8vIENvcHkgYWxsIHR5cGUgZGVmaW5pdGlvbnMgaW50byB0aGUgcGFja2FnZS4gVGhpcyBpcyBuZWNlc3Nhcnkgc28gdGhhdCBkZXZlbG9wZXJzIGNhbiB1c2VcbiAgLy8gdGhlIHBhY2thZ2Ugd2l0aCB0eXBlIGRlZmluaXRpb25zLlxuICB0eXBlRGVmaW5pdGlvbnMuZm9yRWFjaChmID0+IHdyaXRlRmlsZUZyb21JbnB1dFBhdGgoZiwgcmVhZFR5cGluZ3NBbmRTdHJpcEFtZE1vZHVsZShmKSkpO1xuXG4gIC8vIENvcHkgYWxsIGBkYXRhYCBmaWxlcyBpbnRvIHRoZSBwYWNrYWdlLiBUaGVzZSBhcmUgZmlsZXMgdGhhdCBhcmVuJ3QgYnVpbHQgYnkgdGhlIG5nX3BhY2thZ2VcbiAgLy8gcnVsZSwgYnV0IGluc3RlYWQgYXJlIGp1c3Qgc3RyYWlnaHQgY29waWVkIGludG8gdGhlIHBhY2thZ2UsIGUuZy4gZ2xvYmFsIENTUyBhc3NldHMuXG4gIGRhdGFGaWxlcy5mb3JFYWNoKGYgPT4gY29weUZpbGVGcm9tSW5wdXRQYXRoKGYpKTtcblxuICAvLyBJdGVyYXRlIHRocm91Z2ggdGhlIGVudHJ5IHBvaW50IG1vZHVsZXNcbiAgLy8gV2UgZG8gdGhpcyBmaXJzdCBiZWNhdXNlIHdlIGFsc28gcmVjb3JkIG5ldyBwYXRocyBmb3IgdGhlIGVzbTUgYW5kIGVzbTIwMTUgY29waWVzXG4gIC8vIG9mIHRoZSBpbmRleCBKUyBmaWxlLCB3aGljaCB3ZSBuZWVkIHRvIGFtZW5kIHRoZSBwYWNrYWdlLmpzb24uXG4gIE9iamVjdC5rZXlzKG1vZHVsZXNNYW5pZmVzdCkuZm9yRWFjaChtb2R1bGVOYW1lID0+IHtcbiAgICBjb25zdCBtb2R1bGVGaWxlcyA9IG1vZHVsZXNNYW5pZmVzdFttb2R1bGVOYW1lXTtcbiAgICBjb25zdCByZWxhdGl2ZSA9IHBhdGgucmVsYXRpdmUoYmluRGlyLCBtb2R1bGVGaWxlc1snaW5kZXgnXSk7XG5cbiAgICBtb2R1bGVGaWxlc1snZXNtNV9pbmRleCddID0gcGF0aC5qb2luKGJpbkRpciwgJ2VzbTUnLCByZWxhdGl2ZSk7XG4gICAgbW9kdWxlRmlsZXNbJ2VzbTIwMTVfaW5kZXgnXSA9IHBhdGguam9pbihiaW5EaXIsICdlc20yMDE1JywgcmVsYXRpdmUpO1xuXG4gICAgLy8gTWV0YWRhdGEgZmlsZSBpcyBvcHRpb25hbCBhcyBlbnRyeS1wb2ludHMgY2FuIGJlIGFsc28gYnVpbHRcbiAgICAvLyB3aXRoIHRoZSBcInRzX2xpYnJhcnlcIiBydWxlLlxuICAgIGNvbnN0IG1ldGFkYXRhRmlsZSA9IG1vZHVsZUZpbGVzWydtZXRhZGF0YSddO1xuICAgIGlmICghbWV0YWRhdGFGaWxlKSB7XG4gICAgICByZXR1cm47XG4gICAgfVxuXG4gICAgY29uc3QgdHlwaW5nc091dEZpbGUgPSBtb2R1bGVGaWxlc1sndHlwaW5ncyddO1xuICAgIC8vIFdlIG9ubHkgc3VwcG9ydCBhbGwgbW9kdWxlcyB3aXRoaW4gYSBwYWNrYWdlIHRvIGJlIGR0cyBidW5kbGVkXG4gICAgLy8gaWU6IGlmIEBhbmd1bGFyL2NvbW1vbi9odHRwIGhhcyBmbGF0IGR0cywgc28gc2hvdWxkIEBhbmd1bGFyL2NvbW1vblxuICAgIGlmIChkdHNCdW5kbGVzLmxlbmd0aCkge1xuICAgICAgY29uc3QgbWV0YWRhdGFDb250ZW50ID0gcmV3aXJlTWV0YWRhdGEobWV0YWRhdGFGaWxlLCB0eXBpbmdzT3V0RmlsZSk7XG4gICAgICB3cml0ZUZpbGVGcm9tSW5wdXRQYXRoKG1ldGFkYXRhRmlsZSwgbWV0YWRhdGFDb250ZW50KTtcbiAgICB9IGVsc2Uge1xuICAgICAgY29weUZpbGVGcm9tSW5wdXRQYXRoKG1ldGFkYXRhRmlsZSk7XG4gICAgfVxuICB9KTtcblxuICBjb25zdCBsaWNlbnNlQmFubmVyID0gbGljZW5zZUZpbGUgPyBmcy5yZWFkRmlsZVN5bmMobGljZW5zZUZpbGUsICd1dGYtOCcpIDogJyc7XG5cbiAgZHRzQnVuZGxlcy5mb3JFYWNoKGJ1bmRsZUZpbGUgPT4ge1xuICAgIGNvbnN0IGNsZWFuRGlzdFBhdGggPSBidW5kbGVGaWxlLnJlcGxhY2UoZHRzQnVuZGxlRmlsZVN1ZmZpeCwgJy5kLnRzJyk7XG4gICAgLy8gQVBJIGV4dHJhY3RvciB3aWxsIG5vdCBkZWR1cGUgbGljZW5zZSBjb21tZW50cyBmcm9tIHZhcmlvdXMgZmlsZXNcbiAgICAvLyB0aGlzIHdpbGwgcmVtb3ZlIGFsbCB0aGUgbGljZW5zZSBjb21tZW50cyBhbmQgYXBwZW5kIHRoZSBsaWNlbnNlIGJhbm5lci5cbiAgICBjb25zdCBjb250ZW50ID0gbGljZW5zZUJhbm5lciArICdcXG4nICtcbiAgICAgICAgcmVhZFR5cGluZ3NBbmRTdHJpcEFtZE1vZHVsZShidW5kbGVGaWxlKVxuICAgICAgICAgICAgLnJlcGxhY2UoLyhcXC9cXCpcXCpcXHMrXFwqXFxzXFxAbGljZW5zZSgoKD8hXFwqXFwvKS58XFxzKSopXFwqXFwvKS9nbSwgJycpO1xuXG4gICAgd3JpdGVGaWxlRnJvbUlucHV0UGF0aChjbGVhbkRpc3RQYXRoLCBjb250ZW50KTtcbiAgfSk7XG5cbiAgLy8gUm9vdCBwYWNrYWdlIG5hbWUgKGUuZy4gJ0Bhbmd1bGFyL2NvbW1vbicpLCBjYXB0dXJlcyBhcyB3ZSBpdGVyYXRlIHRocm91Z2ggc291cmNlcyBiZWxvdy5cbiAgbGV0IHJvb3RQYWNrYWdlTmFtZSA9ICcnO1xuICBjb25zdCBwYWNrYWdlc1dpdGhFeGlzdGluZ1BhY2thZ2VKc29uID0gbmV3IFNldDxzdHJpbmc+KCk7XG5cbiAgZm9yIChjb25zdCBzcmMgb2Ygc3Jjcykge1xuICAgIGlmIChzcmMuaW5jbHVkZXMoYmluRGlyKSB8fCBzcmMuaW5jbHVkZXMoZ2VuZmlsZXNEaXIpKSB7XG4gICAgICBlcnJvckhhc09jY3VyZWQgPSB0cnVlO1xuICAgICAgY29uc29sZS5lcnJvcihcbiAgICAgICAgICAnVGhlIFwic3Jjc1wiIGZvciBuZ19wYWNrYWdlIHNob3VsZCBub3QgaW5jbHVkZSBvdXRwdXQgb2Ygb3RoZXIgcnVsZXMuIEZvdW5kOlxcbicgK1xuICAgICAgICAgIGAgICR7c3JjfWApO1xuICAgIH1cblxuICAgIGxldCBjb250ZW50ID0gZnMucmVhZEZpbGVTeW5jKHNyYywgJ3V0Zi04Jyk7XG4gICAgLy8gTW9kaWZ5IHBhY2thZ2UuanNvbiBmaWxlcyBhcyBuZWNlc3NhcnkgZm9yIHB1Ymxpc2hpbmdcbiAgICBpZiAocGF0aC5iYXNlbmFtZShzcmMpID09PSAncGFja2FnZS5qc29uJykge1xuICAgICAgY29uc3QgcGFja2FnZUpzb24gPSBKU09OLnBhcnNlKGNvbnRlbnQpO1xuICAgICAgY29udGVudCA9IGFtZW5kUGFja2FnZUpzb24oc3JjLCBwYWNrYWdlSnNvbiwgZmFsc2UpO1xuXG4gICAgICBjb25zdCBwYWNrYWdlTmFtZSA9IHBhY2thZ2VKc29uWyduYW1lJ107XG4gICAgICBwYWNrYWdlc1dpdGhFeGlzdGluZ1BhY2thZ2VKc29uLmFkZChwYWNrYWdlTmFtZSk7XG5cbiAgICAgIC8vIEtlZXAgdHJhY2sgb2YgdGhlIHJvb3QgcGFja2FnZSBuYW1lLCBlLmcuIFwiQGFuZ3VsYXIvY29tbW9uXCIuIFdlIGFzc3VtZSB0aGF0IHRoZVxuICAgICAgLy8gcm9vdCBuYW1lIHdpbGwgYmUgc2hvcnRlc3QgYmVjYXVzZSBzZWNvbmRhcnkgZW50cnktcG9pbnRzIHdpbGwgYXBwZW5kIHRvIGl0XG4gICAgICAvLyAoZS5nLiBcIkBhbmd1bGFyL2NvbW1vbi9odHRwXCIpLlxuICAgICAgaWYgKCFyb290UGFja2FnZU5hbWUgfHwgcGFja2FnZU5hbWUubGVuZ3RoIDwgcm9vdFBhY2thZ2VOYW1lLmxlbmd0aCkge1xuICAgICAgICByb290UGFja2FnZU5hbWUgPSBwYWNrYWdlSnNvblsnbmFtZSddO1xuICAgICAgfVxuICAgIH1cbiAgICB3cml0ZUZpbGVGcm9tSW5wdXRQYXRoKHNyYywgY29udGVudCk7XG4gIH1cblxuICAvLyBHZW5lcmF0ZSBleHRyYSBmaWxlcyBmb3Igc2Vjb25kYXJ5IGVudHJ5LXBvaW50cy5cbiAgT2JqZWN0LmtleXMobW9kdWxlc01hbmlmZXN0KS5mb3JFYWNoKGVudHJ5UG9pbnRQYWNrYWdlTmFtZSA9PiB7XG4gICAgY29uc3QgZW50cnlQb2ludE5hbWUgPSBlbnRyeVBvaW50UGFja2FnZU5hbWUuc3Vic3RyKHJvb3RQYWNrYWdlTmFtZS5sZW5ndGggKyAxKTtcbiAgICBpZiAoIWVudHJ5UG9pbnROYW1lKSByZXR1cm47XG5cbiAgICBjb25zdCBtZXRhZGF0YUZpbGVQYXRoID0gbW9kdWxlc01hbmlmZXN0W2VudHJ5UG9pbnRQYWNrYWdlTmFtZV1bJ21ldGFkYXRhJ107XG4gICAgaWYgKG1ldGFkYXRhRmlsZVBhdGgpIHtcbiAgICAgIGNyZWF0ZU1ldGFkYXRhUmVleHBvcnRGaWxlKFxuICAgICAgICAgIGVudHJ5UG9pbnROYW1lLCBtb2R1bGVzTWFuaWZlc3RbZW50cnlQb2ludFBhY2thZ2VOYW1lXVsnbWV0YWRhdGEnXSxcbiAgICAgICAgICBlbnRyeVBvaW50UGFja2FnZU5hbWUpO1xuICAgIH1cblxuICAgIGNyZWF0ZVR5cGluZ3NSZWV4cG9ydEZpbGUoXG4gICAgICAgIGVudHJ5UG9pbnROYW1lLCBsaWNlbnNlQmFubmVyLCBtb2R1bGVzTWFuaWZlc3RbZW50cnlQb2ludFBhY2thZ2VOYW1lXVsndHlwaW5ncyddKTtcblxuICAgIGlmICghcGFja2FnZXNXaXRoRXhpc3RpbmdQYWNrYWdlSnNvbi5oYXMoZW50cnlQb2ludFBhY2thZ2VOYW1lKSkge1xuICAgICAgY3JlYXRlRW50cnlQb2ludFBhY2thZ2VKc29uKGVudHJ5UG9pbnROYW1lLCBlbnRyeVBvaW50UGFja2FnZU5hbWUpO1xuICAgIH1cbiAgfSk7XG5cbiAgcmV0dXJuIGVycm9ySGFzT2NjdXJlZCA/IDEgOiAwO1xuXG4gIC8qKlxuICAgKiBDb252ZXJ0IGEgYmluRGlyLXJlbGF0aXZlIHBhdGggdG8gc3JjRGlyLXJlbGF0aXZlXG4gICAqIEBwYXJhbSBmcm9tIHBhdGggdG8gYSBmaWxlIHVuZGVyIHRoZSBzcmNEaXIsIGxpa2UgcGFja2FnZXMvY29yZS90ZXN0aW5nL3BhY2thZ2UuanNvblxuICAgKiBAcGFyYW0gZmlsZSBwYXRoIHRvIGEgZmlsZSB1bmRlciB0aGUgYmluRGlyLCBsaWtlIGJhemVsLWJpbi9jb3JlL3Rlc3RpbmcvZ2VuZXJhdGVkLmpzXG4gICAqL1xuICBmdW5jdGlvbiBzcmNEaXJSZWxhdGl2ZShmcm9tOiBzdHJpbmcsIGZpbGU6IHN0cmluZykge1xuICAgIGNvbnN0IHJlc3VsdCA9IG5vcm1hbGl6ZVNlcGFyYXRvcnMoXG4gICAgICAgIHBhdGgucmVsYXRpdmUocGF0aC5kaXJuYW1lKGZyb20pLCBwYXRoLmpvaW4oc3JjRGlyLCBwYXRoLnJlbGF0aXZlKGJpbkRpciwgZmlsZSkpKSk7XG4gICAgaWYgKHJlc3VsdC5zdGFydHNXaXRoKCcuLicpKSByZXR1cm4gcmVzdWx0O1xuICAgIHJldHVybiBgLi8ke3Jlc3VsdH1gO1xuICB9XG5cbiAgZnVuY3Rpb24gY29weUZpbGUoZmlsZTogc3RyaW5nLCBiYXNlRGlyOiBzdHJpbmcsIHJlbGF0aXZlID0gJy4nKSB7XG4gICAgY29uc3QgZGlyID0gcGF0aC5qb2luKGJhc2VEaXIsIHJlbGF0aXZlKTtcbiAgICBzaHgubWtkaXIoJy1wJywgZGlyKTtcbiAgICBzaHguY3AoZmlsZSwgZGlyKTtcbiAgICAvLyBEb3VibGUtdW5kZXJzY29yZSBpcyB1c2VkIHRvIGVzY2FwZSBmb3J3YXJkIHNsYXNoIGluIEZFU00gZmlsZW5hbWVzLlxuICAgIC8vIFNlZSBuZ19wYWNrYWdlLmJ6bDpcbiAgICAvLyAgIGZlc21fb3V0cHV0X2ZpbGVuYW1lID0gZW50cnlfcG9pbnQucmVwbGFjZShcIi9cIiwgXCJfX1wiKVxuICAgIC8vIFdlIG5lZWQgdG8gdW5lc2NhcGUgdGhlc2UuXG4gICAgaWYgKGZpbGUuaW5kZXhPZignX18nKSA+PSAwKSB7XG4gICAgICBjb25zdCBvdXRwdXRQYXRoID0gcGF0aC5qb2luKGRpciwgLi4ucGF0aC5iYXNlbmFtZShmaWxlKS5zcGxpdCgnX18nKSk7XG4gICAgICBzaHgubWtkaXIoJy1wJywgcGF0aC5kaXJuYW1lKG91dHB1dFBhdGgpKTtcbiAgICAgIHNoeC5tdihwYXRoLmpvaW4oZGlyLCBwYXRoLmJhc2VuYW1lKGZpbGUpKSwgb3V0cHV0UGF0aCk7XG5cbiAgICAgIC8vIGlmIHdlIGFyZSByZW5hbWluZyB0aGUgLmpzIGZpbGUsIHdlJ2xsIGFsc28gbmVlZCB0byB1cGRhdGUgdGhlIHNvdXJjZU1hcHBpbmdVUkwgaW4gdGhlIGZpbGVcbiAgICAgIGlmIChmaWxlLmVuZHNXaXRoKCcuanMnKSkge1xuICAgICAgICBzaHguY2htb2QoJyt3Jywgb3V0cHV0UGF0aCk7XG4gICAgICAgIHNoeC5zZWQoJy1pJywgYCR7cGF0aC5iYXNlbmFtZShmaWxlKX0ubWFwYCwgYCR7cGF0aC5iYXNlbmFtZShvdXRwdXRQYXRoKX0ubWFwYCwgb3V0cHV0UGF0aCk7XG4gICAgICB9XG4gICAgfVxuICB9XG5cbiAgLyoqXG4gICAqIEluc2VydHMgb3IgZWRpdHMgcHJvcGVydGllcyBpbnRvIHRoZSBwYWNrYWdlLmpzb24gZmlsZShzKSBpbiB0aGUgcGFja2FnZSBzbyB0aGF0XG4gICAqIHRoZXkgcG9pbnQgdG8gYWxsIHRoZSByaWdodCBnZW5lcmF0ZWQgYXJ0aWZhY3RzLlxuICAgKlxuICAgKiBAcGFyYW0gcGFja2FnZUpzb24gVGhlIHBhdGggdG8gdGhlIHBhY2thZ2UuanNvbiBmaWxlLlxuICAgKiBAcGFyYW0gcGFyc2VkUGFja2FnZSBQYXJzZWQgcGFja2FnZS5qc29uIGNvbnRlbnRcbiAgICogQHBhcmFtIGlzR2VuZXJhdGVkUGFja2FnZUpzb24gV2hldGhlciB0aGUgcGFzc2VkIHBhY2thZ2UuanNvbiBoYXMgYmVlbiBnZW5lcmF0ZWQuXG4gICAqL1xuICBmdW5jdGlvbiBhbWVuZFBhY2thZ2VKc29uKFxuICAgICAgcGFja2FnZUpzb246IHN0cmluZywgcGFyc2VkUGFja2FnZToge1trZXk6IHN0cmluZ106IHN0cmluZ30sXG4gICAgICBpc0dlbmVyYXRlZFBhY2thZ2VKc29uOiBib29sZWFuKSB7XG4gICAgY29uc3QgcGFja2FnZU5hbWUgPSBwYXJzZWRQYWNrYWdlWyduYW1lJ107XG4gICAgY29uc3QgbW9kdWxlRGF0YSA9IG1vZHVsZXNNYW5pZmVzdFtwYWNrYWdlTmFtZV07XG5cbiAgICAvLyBXZSBkb24ndCB3YW50IHRvIG1vZGlmeSB0aGUgXCJwYWNrYWdlLmpzb25cIiBpZiB3ZSBndWVzc2VkIHRoZSBlbnRyeS1wb2ludFxuICAgIC8vIHBhdGhzIGFuZCB0aGVyZSBpcyBhIGN1c3RvbSBcInBhY2thZ2UuanNvblwiIGZvciB0aGF0IHBhY2thZ2UgYWxyZWFkeS4gTW9kdWxlXG4gICAgLy8gZGF0YSB3aWxsIGJlIG9ubHkgdW5kZWZpbmVkIGlmIHRoZSBwYWNrYWdlIG5hbWUgY29tZXMgZnJvbSBhIG5vbi1nZW5lcmF0ZWRcbiAgICAvLyBcInBhY2thZ2UuanNvblwiLiBJbiB0aGF0IGNhc2Ugd2Ugd2FudCB0byBsZWF2ZSB0aGUgZmlsZSB1bnRvdWNoZWQgYXMgd2VsbC5cbiAgICBpZiAoIW1vZHVsZURhdGEgfHwgbW9kdWxlRGF0YS5ndWVzc2VkUGF0aHMgJiYgIWlzR2VuZXJhdGVkUGFja2FnZUpzb24pIHtcbiAgICAgIC8vIElkZWFsbHkgd2Ugc2hvdWxkIHRocm93IGhlcmUsIGFzIHdlIGdvdCBhbiBlbnRyeSBwb2ludCB0aGF0IGRvZXNuJ3RcbiAgICAgIC8vIGhhdmUgZmxhdCBtb2R1bGUgbWV0YWRhdGEgLyBidW5kbGUgaW5kZXgsIHNvIGl0IG1heSBoYXZlIGJlZW4gYW5cbiAgICAgIC8vIG5nX21vZHVsZSB0aGF0J3MgbWlzc2luZyBhIG1vZHVsZV9uYW1lIGF0dHJpYnV0ZS5cbiAgICAgIC8vIEhvd2V2ZXIsIEBhbmd1bGFyL2NvbXBpbGVyIGNhbid0IGJlIGFuIG5nX21vZHVsZSwgYXMgaXQncyB0aGUgaW50ZXJuYWxzXG4gICAgICAvLyBvZiB0aGUgbmdjIGNvbXBpbGVyLCB5ZXQgd2Ugd2FudCB0byBidWlsZCBhbiBuZ19wYWNrYWdlIGZvciBpdC5cbiAgICAgIC8vIFNvIGlnbm9yZSBwYWNrYWdlLmpzb24gZmlsZXMgd2hlbiB3ZSBhcmUgbWlzc2luZyBkYXRhLlxuICAgICAgY29uc29sZS5lcnJvcignV0FSTklORzogbm8gbW9kdWxlIG1ldGFkYXRhIGZvciBwYWNrYWdlJywgcGFja2FnZU5hbWUpO1xuICAgICAgY29uc29sZS5lcnJvcignICAgTm90IHVwZGF0aW5nIHRoZSBwYWNrYWdlLmpzb24gZmlsZSB0byBwb2ludCB0byBpdCcpO1xuICAgICAgY29uc29sZS5lcnJvcihcbiAgICAgICAgICAnICAgVGhlIG5nX21vZHVsZSBmb3IgdGhpcyBwYWNrYWdlIGlzIHBvc3NpYmx5IG1pc3NpbmcgdGhlIG1vZHVsZV9uYW1lIGF0dHJpYnV0ZSAnKTtcbiAgICAgIHJldHVybiBKU09OLnN0cmluZ2lmeShwYXJzZWRQYWNrYWdlLCBudWxsLCAyKTtcbiAgICB9XG5cbiAgICAvLyBEZXJpdmUgdGhlIHBhdGhzIHRvIHRoZSBmaWxlcyBmcm9tIHRoZSBoYXJkLWNvZGVkIG5hbWVzIHdlIGdhdmUgdGhlbS5cbiAgICAvLyBUT0RPKGFsZXhlYWdsZSk6IGl0IHdvdWxkIGJlIGJldHRlciB0byB0cmFuc2ZlciB0aGlzIGluZm9ybWF0aW9uIGZyb20gdGhlIHBsYWNlXG4gICAgLy8gd2hlcmUgd2UgY3JlYXRlZCB0aGUgZmlsZW5hbWVzLCB2aWEgdGhlIG1vZHVsZXNNYW5pZmVzdEFyZ1xuICAgIHBhcnNlZFBhY2thZ2VbJ21haW4nXSA9IGdldEJ1bmRsZU5hbWUocGFja2FnZU5hbWUsICdidW5kbGVzJyk7XG4gICAgcGFyc2VkUGFja2FnZVsnZmVzbTUnXSA9IGdldEJ1bmRsZU5hbWUocGFja2FnZU5hbWUsICdmZXNtNScpO1xuICAgIHBhcnNlZFBhY2thZ2VbJ2Zlc20yMDE1J10gPSBnZXRCdW5kbGVOYW1lKHBhY2thZ2VOYW1lLCAnZmVzbTIwMTUnKTtcblxuICAgIHBhcnNlZFBhY2thZ2VbJ2VzbTUnXSA9IHNyY0RpclJlbGF0aXZlKHBhY2thZ2VKc29uLCBtb2R1bGVEYXRhWydlc201X2luZGV4J10pO1xuICAgIHBhcnNlZFBhY2thZ2VbJ2VzbTIwMTUnXSA9IHNyY0RpclJlbGF0aXZlKHBhY2thZ2VKc29uLCBtb2R1bGVEYXRhWydlc20yMDE1X2luZGV4J10pO1xuICAgIHBhcnNlZFBhY2thZ2VbJ3R5cGluZ3MnXSA9IHNyY0RpclJlbGF0aXZlKHBhY2thZ2VKc29uLCBtb2R1bGVEYXRhWyd0eXBpbmdzJ10pO1xuXG4gICAgLy8gRm9yIG5vdywgd2UgcG9pbnQgdGhlIHByaW1hcnkgZW50cnkgcG9pbnRzIGF0IHRoZSBmZXNtIGZpbGVzLCBiZWNhdXNlIG9mIFdlYnBhY2tcbiAgICAvLyBwZXJmb3JtYW5jZSBpc3N1ZXMgd2l0aCBhIGxhcmdlIG51bWJlciBvZiBpbmRpdmlkdWFsIGZpbGVzLlxuICAgIC8vIFRPRE8oaW1pbmFyKTogcmVzb2x2ZSBwZXJmb3JtYW5jZSBpc3N1ZXMgd2l0aCB0aGUgdG9vbGNoYWluIGFuZCBwb2ludCB0aGVzZSB0byBlc21cbiAgICBwYXJzZWRQYWNrYWdlWydtb2R1bGUnXSA9IHBhcnNlZFBhY2thZ2VbJ2Zlc201J107XG4gICAgcGFyc2VkUGFja2FnZVsnZXMyMDE1J10gPSBwYXJzZWRQYWNrYWdlWydmZXNtMjAxNSddO1xuXG4gICAgcmV0dXJuIEpTT04uc3RyaW5naWZ5KHBhcnNlZFBhY2thZ2UsIG51bGwsIDIpO1xuICB9XG5cbiAgLy8gZS5nLiBAYW5ndWxhci9jb21tb24vaHR0cC90ZXN0aW5nIC0+IC4uLy4uL2J1bmRsZXMvY29tbW9uLWh0dHAtdGVzdGluZy51bWQuanNcbiAgLy8gb3IgICBAYW5ndWxhci9jb21tb24vaHR0cC90ZXN0aW5nIC0+IC4uLy4uL2Zlc201L2h0dHAvdGVzdGluZy5qc1xuICBmdW5jdGlvbiBnZXRCdW5kbGVOYW1lKHBhY2thZ2VOYW1lOiBzdHJpbmcsIGRpcjogc3RyaW5nKSB7XG4gICAgY29uc3QgcGFydHMgPSBwYWNrYWdlTmFtZS5zcGxpdCgnLycpO1xuICAgIC8vIFJlbW92ZSB0aGUgc2NvcGVkIHBhY2thZ2UgcGFydCwgbGlrZSBAYW5ndWxhciBpZiBwcmVzZW50XG4gICAgY29uc3QgbmFtZVBhcnRzID0gcGFja2FnZU5hbWUuc3RhcnRzV2l0aCgnQCcpID8gcGFydHMuc3BsaWNlKDEpIDogcGFydHM7XG4gICAgY29uc3QgcmVsYXRpdmVQYXRoID0gbmV3QXJyYXkobmFtZVBhcnRzLmxlbmd0aCAtIDEsICcuLicpLmpvaW4oJy8nKSB8fCAnLic7XG4gICAgbGV0IGJhc2VuYW1lOiBzdHJpbmc7XG4gICAgaWYgKGRpciA9PT0gJ2J1bmRsZXMnKSB7XG4gICAgICBiYXNlbmFtZSA9IG5hbWVQYXJ0cy5qb2luKCctJykgKyAnLnVtZCc7XG4gICAgfSBlbHNlIGlmIChuYW1lUGFydHMubGVuZ3RoID09PSAxKSB7XG4gICAgICBiYXNlbmFtZSA9IG5hbWVQYXJ0c1swXTtcbiAgICB9IGVsc2Uge1xuICAgICAgYmFzZW5hbWUgPSBuYW1lUGFydHMuc2xpY2UoMSkuam9pbignLycpO1xuICAgIH1cbiAgICByZXR1cm4gW3JlbGF0aXZlUGF0aCwgZGlyLCBiYXNlbmFtZSArICcuanMnXS5qb2luKCcvJyk7XG4gIH1cblxuICAvKiogQ3JlYXRlcyBtZXRhZGF0YSByZS1leHBvcnQgZmlsZSBmb3IgYSBzZWNvbmRhcnkgZW50cnktcG9pbnQuICovXG4gIGZ1bmN0aW9uIGNyZWF0ZU1ldGFkYXRhUmVleHBvcnRGaWxlKFxuICAgICAgZW50cnlQb2ludE5hbWU6IHN0cmluZywgbWV0YWRhdGFGaWxlOiBzdHJpbmcsIHBhY2thZ2VOYW1lOiBzdHJpbmcpIHtcbiAgICBjb25zdCBpbnB1dFBhdGggPSBwYXRoLmpvaW4oc3JjRGlyLCBgJHtlbnRyeVBvaW50TmFtZX0ubWV0YWRhdGEuanNvbmApO1xuICAgIHdyaXRlRmlsZUZyb21JbnB1dFBhdGgoaW5wdXRQYXRoLCBKU09OLnN0cmluZ2lmeSh7XG4gICAgICAnX19zeW1ib2xpYyc6ICdtb2R1bGUnLFxuICAgICAgJ3ZlcnNpb24nOiAzLFxuICAgICAgJ21ldGFkYXRhJzoge30sXG4gICAgICAnZXhwb3J0cyc6XG4gICAgICAgICAgW3snZnJvbSc6IGAke3NyY0RpclJlbGF0aXZlKGlucHV0UGF0aCwgbWV0YWRhdGFGaWxlLnJlcGxhY2UoLy5tZXRhZGF0YS5qc29uJC8sICcnKSl9YH1dLFxuICAgICAgJ2ZsYXRNb2R1bGVJbmRleFJlZGlyZWN0JzogdHJ1ZSxcbiAgICAgICdpbXBvcnRBcyc6IHBhY2thZ2VOYW1lXG4gICAgfSkgKyAnXFxuJyk7XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyBhIHR5cGluZ3MgKGQudHMpIHJlLWV4cG9ydCBmaWxlIGZvciBhIHNlY29uZGFyeS1lbnRyeSBwb2ludCxcbiAgICogZS5nLiwgYGV4cG9ydCAqIGZyb20gJy4vY29tbW9uL2NvbW1vbidgXG4gICAqL1xuICBmdW5jdGlvbiBjcmVhdGVUeXBpbmdzUmVleHBvcnRGaWxlKGVudHJ5UG9pbnROYW1lOiBzdHJpbmcsIGxpY2Vuc2U6IHN0cmluZywgdHlwaW5nc0ZpbGU6IHN0cmluZykge1xuICAgIGNvbnN0IGlucHV0UGF0aCA9IHBhdGguam9pbihzcmNEaXIsIGAke2VudHJ5UG9pbnROYW1lfS5kLnRzYCk7XG4gICAgY29uc3QgY29udGVudCA9IGAke2xpY2Vuc2V9XG5leHBvcnQgKiBmcm9tICcke3NyY0RpclJlbGF0aXZlKGlucHV0UGF0aCwgdHlwaW5nc0ZpbGUucmVwbGFjZSgvXFwuZFxcLnRzeD8kLywgJycpKX0nO1xuYDtcbiAgICB3cml0ZUZpbGVGcm9tSW5wdXRQYXRoKGlucHV0UGF0aCwgY29udGVudCk7XG4gIH1cblxuICAvKipcbiAgICogQ3JlYXRlcyBhIHBhY2thZ2UuanNvbiBmb3IgYSBzZWNvbmRhcnkgZW50cnktcG9pbnQuXG4gICAqIEBwYXJhbSBkaXIgVGhlIGRpcmVjdG9yeSB1bmRlciB3aGljaCB0aGUgcGFja2FnZS5qc29uIHNob3VsZCBiZSB3cml0dGVuLlxuICAgKiBAcGFyYW0gZW50cnlQb2ludFBhY2thZ2VOYW1lIFRoZSBmdWxsIHBhY2thZ2UgbmFtZSBmb3IgdGhlIGVudHJ5IHBvaW50LFxuICAgKiAgICAgZS5nLiAnQGFuZ3VsYXIvY29tbW9uL2h0dHAnLlxuICAgKi9cbiAgZnVuY3Rpb24gY3JlYXRlRW50cnlQb2ludFBhY2thZ2VKc29uKGRpcjogc3RyaW5nLCBlbnRyeVBvaW50UGFja2FnZU5hbWU6IHN0cmluZykge1xuICAgIGNvbnN0IHBrZ0pzb24gPSBwYXRoLmpvaW4oc3JjRGlyLCBkaXIsICdwYWNrYWdlLmpzb24nKTtcbiAgICBjb25zdCBjb250ZW50ID0gYW1lbmRQYWNrYWdlSnNvbihwa2dKc29uLCB7bmFtZTogZW50cnlQb2ludFBhY2thZ2VOYW1lfSwgdHJ1ZSk7XG4gICAgd3JpdGVGaWxlRnJvbUlucHV0UGF0aChwa2dKc29uLCBjb250ZW50KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBOb3JtYWxpemVzIHRoZSBzcGVjaWZpZWQgcGF0aCBieSByZXBsYWNpbmcgYmFja3NsYXNoIHNlcGFyYXRvcnMgd2l0aCBQb3NpeFxuICAgKiBmb3J3YXJkIHNsYXNoIHNlcGFyYXRvcnMuXG4gICAqL1xuICBmdW5jdGlvbiBub3JtYWxpemVTZXBhcmF0b3JzKHBhdGg6IHN0cmluZyk6IHN0cmluZyB7IHJldHVybiBwYXRoLnJlcGxhY2UoL1xcXFwvZywgJy8nKTsgfVxuXG4gIC8qKlxuICAqIFJld2lyZXMgbWV0YWRhdGEgdG8gcG9pbnQgdG8gdGhlIGZsYXR0ZW5lZCBkdHMgZmlsZS5cbiAgKlxuICAqIEBwYXJhbSBtZXRhZGF0YVBhdGggdGhlIG1ldGFkYXRhIGZpbGUgcGF0aFxuICAqIEBwYXJhbSB0eXBpbmdzUGF0aCB0aGUgdHlwaW5ncyBidW5kbGUgZW50cnlwb2ludFxuICAqL1xuICBmdW5jdGlvbiByZXdpcmVNZXRhZGF0YShtZXRhZGF0YVBhdGg6IHN0cmluZywgdHlwaW5nc1BhdGg6IHN0cmluZyk6IHN0cmluZyB7XG4gICAgY29uc3QgbWV0YWRhdGEgPSBKU09OLnBhcnNlKGZzLnJlYWRGaWxlU3luYyhtZXRhZGF0YVBhdGgsICd1dGYtOCcpKTtcblxuICAgIGxldCB0eXBpbmdzUmVsYXRpdmVQYXRoID1cbiAgICAgICAgbm9ybWFsaXplU2VwYXJhdG9ycyhwYXRoLnJlbGF0aXZlKHBhdGguZGlybmFtZShtZXRhZGF0YVBhdGgpLCB0eXBpbmdzUGF0aCkpO1xuICAgIGlmICghdHlwaW5nc1JlbGF0aXZlUGF0aC5zdGFydHNXaXRoKCcuLicpKSB7XG4gICAgICB0eXBpbmdzUmVsYXRpdmVQYXRoID0gYC4vJHt0eXBpbmdzUmVsYXRpdmVQYXRofWA7XG4gICAgfVxuXG4gICAgdHlwaW5nc1JlbGF0aXZlUGF0aCA9IHR5cGluZ3NSZWxhdGl2ZVBhdGgucmVwbGFjZSgnLmQudHMnLCAnJyk7XG5cbiAgICAvLyB0aGUgcmVnZXhwIGhlcmUgY2F0Y2hlcyBhbGwgcmVsYXRpdmUgcGF0aHMgc3VjaCBhczpcbiAgICAvLyAuL3NyYy9jb3JlL2Zvby5kLnRzIGFuZCAuLi9zcmMvY29yZS9mb28uZC50c1xuICAgIGNvbnN0IHJlbGF0aXZlUGF0aFJlZ2V4ID0gL1xcLj9cXC5cXC9bXFx3XFwuXFwtX1xcL10rL2c7XG4gICAgaWYgKG1ldGFkYXRhLmV4cG9ydHMpIHtcbiAgICAgIC8vIFN0cmlwIHJlLWV4cG9ydHMgd2hpY2ggYXJlIG5vdyBzZWxmLXJlZmVyZW5jZXNcbiAgICAgIG1ldGFkYXRhLmV4cG9ydHMgPVxuICAgICAgICAgIG1ldGFkYXRhLmV4cG9ydHMuZmlsdGVyKChlOiB7ZnJvbTogc3RyaW5nfSkgPT4gIWUuZnJvbS5tYXRjaChyZWxhdGl2ZVBhdGhSZWdleCkpO1xuICAgIH1cbiAgICByZXR1cm4gSlNPTi5zdHJpbmdpZnkobWV0YWRhdGEpLnJlcGxhY2UocmVsYXRpdmVQYXRoUmVnZXgsIHR5cGluZ3NSZWxhdGl2ZVBhdGgpO1xuICB9XG5cbiAgLyoqXG4gICAqIFN0cmlwIHRoZSBuYW1lZCBBTUQgbW9kdWxlIGZvciBjb21wYXRpYmlsaXR5IHdpdGggbm9uLWJhemVsIHVzZXJzIGZyb20gdHlwaW5ncyBjb250ZW50XG4gICAqIEBwYXJhbSBmaWxlUGF0aCBkdHMgZmlsZSBwYXRoXG4gICAqL1xuICBmdW5jdGlvbiByZWFkVHlwaW5nc0FuZFN0cmlwQW1kTW9kdWxlKGZpbGVQYXRoOiBzdHJpbmcpOiBzdHJpbmcge1xuICAgIHJldHVybiBmc1xuICAgICAgICAucmVhZEZpbGVTeW5jKGZpbGVQYXRoLCAndXRmLTgnKVxuICAgICAgICAvLyBTdHJpcCB0aGUgbmFtZWQgQU1EIG1vZHVsZSBmb3IgY29tcGF0aWJpbGl0eSB3aXRoIG5vbi1iYXplbCB1c2Vyc1xuICAgICAgICAucmVwbGFjZSgvXlxcL1xcL1xcLyA8YW1kLW1vZHVsZSBuYW1lPS4qXFwvPltcXHJcXG5dKy9nbSwgJycpO1xuICB9XG59XG5cbmlmIChyZXF1aXJlLm1haW4gPT09IG1vZHVsZSkge1xuICBwcm9jZXNzLmV4aXRDb2RlID0gbWFpbihwcm9jZXNzLmFyZ3Yuc2xpY2UoMikpO1xufVxuXG5leHBvcnQgZnVuY3Rpb24gbmV3QXJyYXk8VCA9IGFueT4oc2l6ZTogbnVtYmVyKTogVFtdO1xuZXhwb3J0IGZ1bmN0aW9uIG5ld0FycmF5PFQ+KHNpemU6IG51bWJlciwgdmFsdWU6IFQpOiBUW107XG5leHBvcnQgZnVuY3Rpb24gbmV3QXJyYXk8VD4oc2l6ZTogbnVtYmVyLCB2YWx1ZT86IFQpOiBUW10ge1xuICBjb25zdCBsaXN0OiBUW10gPSBbXTtcbiAgZm9yIChsZXQgaSA9IDA7IGkgPCBzaXplOyBpKyspIHtcbiAgICBsaXN0LnB1c2godmFsdWUgISk7XG4gIH1cbiAgcmV0dXJuIGxpc3Q7XG59XG4iXX0=