/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */
import * as fs from 'fs';
import * as path from 'path';
import { globSync } from 'tinyglobby';
import { analyzeFileAndEnsureNoCrossImports } from './cross_entry_points_imports';
/**
 * List of known `package.json` fields which provide information about
 * supported package formats and their associated entry paths.
 */
const knownFormatPackageJsonFormatFields = ['main', 'typings', 'module'];
// Main entry-point.
main(process.argv.slice(2));
function main(args) {
    // This utility expects all of its arguments to be specified in a params file generated by
    // bazel (see https://docs.bazel.build/versions/master/skylark/lib/Args.html#use_param_file).
    const paramFilePath = args[0];
    // Bazel params may be surrounded with quotes
    function unquoteParameter(s) {
        return s.replace(/^'(.*)'$/, '$1');
    }
    // Parameters are specified in the file one per line.
    const params = fs.readFileSync(paramFilePath, 'utf-8').split('\n').map(unquoteParameter);
    const [
    // Output directory for the npm package.
    outputDirExecPath, 
    // The package segment of the ng_package rule's label (e.g. 'package/common').
    owningPackageName, 
    // JSON data capturing metadata of the package being built. See `PackageMetadata`.
    metadataArg, 
    // Path to the package's README.md.
    readmeMd, 
    // Path to the package's LICENSE file.
    licenseFile, 
    // List of individual ES2022 modules
    esm2022Arg, 
    // List of static files that should be copied into the package.
    staticFilesArg, 
    // List of all type definitions that need to packaged into the ng_package.
    typeDefinitionsArg, 
    // List of side-effectful entry-points
    sideEffectEntryPointsArg,] = params;
    const esm2022 = JSON.parse(esm2022Arg);
    const typeDefinitions = JSON.parse(typeDefinitionsArg);
    const staticFiles = JSON.parse(staticFilesArg);
    const metadata = JSON.parse(metadataArg);
    const sideEffectEntryPoints = JSON.parse(sideEffectEntryPointsArg);
    if (readmeMd) {
        copyFile(readmeMd, 'README.md');
    }
    if (licenseFile) {
        copyFile(licenseFile, 'LICENSE');
    }
    /**
     * Writes a file with the specified content into the package output.
     * @param outputRelativePath Relative path in the output directory where the
     *   file is written to.
     * @param fileContent Content of the file.
     */
    function writeFile(outputRelativePath, fileContent) {
        const outputPath = path.join(outputDirExecPath, outputRelativePath);
        // Always ensure that the target directory exists.
        fs.mkdirSync(path.dirname(outputPath), { recursive: true });
        fs.writeFileSync(outputPath, fileContent);
    }
    /**
     * Copies a file into the package output to the specified location.
     * @param inputPath File that should be copied.
     * @param outputRelativePath Relative path in the output directory where the
     *   file is written to.
     */
    function copyFile(inputPath, outputRelativePath) {
        const fileContent = fs.readFileSync(inputPath, 'utf8');
        writeFile(outputRelativePath, fileContent);
    }
    /**
     * Gets the relative path for the given file within the owning package. This
     * assumes the file is contained in the owning package.
     *
     * e.g. consider the owning package is `packages/core` and the input file
     * is `packages/core/testing/index.d.ts`. This function would return the
     * relative path as followed: `testing/index.d.ts`.
     */
    function getOwningPackageRelativePath(file) {
        return path.relative(owningPackageName, file.shortPath);
    }
    /** Gets the output-relative path where the typing file is being written to. */
    function getTypingOutputRelativePath(file) {
        // Type definitions are intended to be copied into the package output while preserving the
        // sub-path from the owning package. e.g. a file like `packages/animations/browser/__index.d.ts`
        // will end up being written to `<pkg-out>/browser/index.d.ts`. Note that types are bundled
        // as a separate action in the `ng_package` Starlark rule and prefixed with `__` to avoid
        // conflicts with source `index.d.ts` files. We remove this prefix here.
        return getOwningPackageRelativePath(file).replace(/__index\.d\.ts$/, 'index.d.ts');
    }
    /**
     * Gets the entry-point sub-path from the package root. e.g. if the package name
     * is `@angular/cdk`, then for `@angular/cdk/a11y` just `a11y` would be returned.
     */
    function getEntryPointSubpath(moduleName) {
        return moduleName.slice(`${metadata.npmPackageName}/`.length);
    }
    /**
     * Gets whether the given module name resolves to a secondary entry-point.
     * e.g. if the package name is `@angular/cdk`, then for `@angular/cdk/a11y`
     * this would return `true`.
     */
    function isSecondaryEntryPoint(moduleName) {
        return getEntryPointSubpath(moduleName) !== '';
    }
    const crossEntryPointFailures = esm2022.flatMap((file) => analyzeFileAndEnsureNoCrossImports(file, metadata));
    if (crossEntryPointFailures.length) {
        console.error(crossEntryPointFailures);
        process.exit(1);
    }
    const fesmFiles = globSync('**/*', { cwd: metadata.bundlesOut.path });
    // Copy all FESM files (and their potential shared chunks) into the package output.
    fesmFiles.forEach((f) => copyFile(path.join(metadata.bundlesOut.path, f), f));
    // Copy all type definitions into the package, preserving the sub-path from the
    // owning package. e.g. a file like `packages/animations/browser/__index.d.ts` will
    // end up in `browser/index.d.ts`
    typeDefinitions.forEach((f) => copyFile(f.path, getTypingOutputRelativePath(f)));
    for (const file of staticFiles) {
        // We copy all files into the package output while preserving the sub-path from
        // the owning package. e.g. `packages/core/package.json` ends up `<pkg-out>/package.json`.
        const outputRelativePath = getOwningPackageRelativePath(file);
        let content = fs.readFileSync(file.path, 'utf8');
        // Check and modify package.json files as necessary for publishing
        if (path.basename(file.path) === 'package.json') {
            const isPrimaryPackageJson = outputRelativePath === 'package.json';
            const packageJson = JSON.parse(content);
            const packageName = packageJson['name'];
            // Prevent non-primary `package.json` files which would throw-off resolution.
            // Resolution in the package should only be based on the top-level `package.json`.
            if (!isPrimaryPackageJson) {
                throw Error(`Found a nested "package.json" file in the package output: ${file.shortPath}.\n` +
                    `All information of the package should reside in the primary package file.`);
            }
            // Check if the `name` field of the `package.json` files are matching with
            // name of the NPM package. This is an additional safety check.
            if (packageName !== metadata.npmPackageName) {
                throw Error(`Primary "package.json" has mismatching package name. Expected the ` +
                    `package to be named "${metadata.npmPackageName}", but is set to: ${packageName}.`);
            }
            let newPackageJson = insertFormatFieldsIntoPackageJson(outputRelativePath, packageJson, false);
            newPackageJson = updatePrimaryPackageJson(newPackageJson);
            // Update the content with the new `package.json` file content.
            content = JSON.stringify(newPackageJson, null, 2);
        }
        writeFile(outputRelativePath, content);
    }
    /**
     * Inserts or edits properties into the package.json file(s) in the package so that
     * they point to all the right generated artifacts.
     *
     * @param packageJsonOutRelativePath Path where the `package.json` is stored in
     *   the package output.
     * @param parsedPackage Parsed package.json content
     * @param isGeneratedPackageJson Whether the passed package.json has been generated.
     */
    function insertFormatFieldsIntoPackageJson(packageJsonOutRelativePath, parsedPackage, isGeneratedPackageJson) {
        const packageJson = { ...parsedPackage };
        const packageName = packageJson['name'];
        const entryPointInfo = metadata.entryPoints[packageName];
        const packageJsonContainingDir = path.dirname(packageJsonOutRelativePath);
        // If a package json file has been discovered that does not match any
        // entry-point in the metadata, we report a warning as most likely the target
        // is configured incorrectly (e.g. missing `module_name` attribute).
        if (!entryPointInfo) {
            // Ideally we should throw here, as we got an entry point that doesn't
            // have flat module metadata / bundle index, so it may have been an
            // ng_module that's missing a module_name attribute.
            // However, @angular/compiler can't be an ng_module, as it's the internals
            // of the ngc compiler, yet we want to build an ng_package for it.
            // So ignore package.json files when we are missing data.
            console.error('WARNING: no module metadata for package', packageName);
            console.error('   Not updating the package.json file to point to it');
            console.error('   The ng_module for this package is possibly missing the module_name attribute ');
            return packageJson;
        }
        // If we guessed the index paths for a module, and it contains an explicit `package.json`
        // file that already sets format properties, we skip automatic insertion of format
        // properties but report a warning in case properties have been set by accident.
        if (entryPointInfo.guessedPaths &&
            !isGeneratedPackageJson &&
            hasExplicitFormatProperties(packageJson)) {
            console.error('WARNING: `package.json` explicitly sets format properties (like `main`).');
            console.error('    Skipping automatic insertion of format properties as explicit ' +
                'format properties are set.');
            console.error('    Ignore this warning if explicit properties are set intentionally.');
            return packageJson;
        }
        const fesm2022RelativeOutPath = entryPointInfo.fesm2022RelativePath;
        const typingsRelativeOutPath = getTypingOutputRelativePath(entryPointInfo.typings);
        packageJson.module = normalizePath(path.relative(packageJsonContainingDir, fesm2022RelativeOutPath));
        packageJson.typings = normalizePath(path.relative(packageJsonContainingDir, typingsRelativeOutPath));
        return packageJson;
    }
    /**
     * Updates the primary `package.json` file of the NPM package to specify
     * the module conditional exports and the ESM module type.
     */
    function updatePrimaryPackageJson(packageJson) {
        if (packageJson.type !== undefined && packageJson.type !== 'module') {
            throw Error('The primary "package.json" file of the package sets the "type" field ' +
                'that is controlled by the packager. Please unset it or set `type` to `module`.');
        }
        const newPackageJson = { ...packageJson };
        newPackageJson.type = 'module';
        // The `package.json` file is made publicly accessible for tools that
        // might want to query information from the Angular NPM package.
        insertExportMappingOrError(newPackageJson, './package.json', { default: './package.json' });
        // Capture all entry-points in the `exports` field using the subpath export declarations:
        // https://nodejs.org/api/packages.html#packages_subpath_exports.
        for (const [moduleName, entryPoint] of Object.entries(metadata.entryPoints)) {
            const subpath = isSecondaryEntryPoint(moduleName)
                ? `./${getEntryPointSubpath(moduleName)}`
                : '.';
            const fesm2022OutRelativePath = entryPoint.fesm2022RelativePath;
            const typesOutRelativePath = getTypingOutputRelativePath(entryPoint.typings);
            // Insert the export mapping for the entry-point. We set `default` to the FESM 2022
            // output, and also set the `types` condition which will be respected by TS 4.5.
            // https://github.com/microsoft/TypeScript/pull/45884.
            insertExportMappingOrError(newPackageJson, subpath, {
                types: normalizePath(typesOutRelativePath),
                // Note: The default conditions needs to be the last one.
                default: normalizePath(fesm2022OutRelativePath),
            });
        }
        checkPackageJsonSideEffects(packageJson);
        return newPackageJson;
    }
    function checkPackageJsonSideEffects(packageJson) {
        // Convenience if there are no side effects, and it's explicitly marked.
        // This is okay and we don't ask the developer to drop the explicit field.
        if (packageJson.sideEffects === false && sideEffectEntryPoints.length === 0) {
            return;
        }
        if (packageJson.sideEffects === true) {
            throw Error('Unexpected `sideEffects` field in `package.json`. ' +
                'Side effects should be fine-grained and marked via the Bazel `side_effect_entry_points` option.');
        }
        const sideEffects = packageJson.sideEffects;
        const neededSideEffects = sideEffectEntryPoints.map((entryPointModule) => `./${metadata.entryPoints[entryPointModule].fesm2022RelativePath}`);
        const missingSideEffects = neededSideEffects.filter((p) => 
        // It's missing, if the whole package is marked as having no side effects.
        sideEffects === false ||
            // Alternatively, it's missing if the explicit list doesn't contain the pattern.
            !(sideEffects ?? []).includes(p));
        if (missingSideEffects.length > 0) {
            throw Error('Missing side effects in `package.json` `sideEffects` field. ' +
                'Please add the following side effect file patterns:\n' +
                missingSideEffects.join('\n - '));
        }
        // Find potential side-effects that refer to our FESM bundles, but aren't part
        // of the `ng_package` known entry points.
        const unexpectedExtra = sideEffects !== false
            ? (sideEffects ?? []).filter((p) => p.includes('fesm2022') && !neededSideEffects.includes(p))
            : [];
        if (unexpectedExtra.length > 0) {
            throw Error('Unexpected side effects in `package.json` `sideEffects` field that is not known to `ng_package`. ' +
                'Please add the side effect entry point to the Bazel `side_effect_entry_points` option. ' +
                'Unexpected patterns:\n' +
                unexpectedExtra.join('\n - '));
        }
    }
    /**
     * Inserts a subpath export mapping into the specified `package.json` object.
     * @throws An error if the mapping is already defined and would conflict.
     */
    function insertExportMappingOrError(packageJson, subpath, mapping) {
        if (packageJson.exports === undefined) {
            packageJson.exports = {};
        }
        if (packageJson.exports[subpath] === undefined) {
            packageJson.exports[subpath] = {};
        }
        const subpathExport = packageJson.exports[subpath];
        // Go through all conditions that should be inserted. If the condition is already
        // manually set of the subpath export, we throw an error. In general, we allow for
        // additional conditions to be set. These will always precede the generated ones.
        for (const conditionName of Object.keys(mapping)) {
            if (subpathExport[conditionName] !== undefined) {
                throw Error(`Found a conflicting export condition for "${subpath}". The "${conditionName}" ` +
                    `condition would be overridden by the packager. Please unset it.`);
            }
            // **Note**: The order of the conditions is preserved even though we are setting
            // the conditions once at a time (the latest assignment will be at the end).
            subpathExport[conditionName] = mapping[conditionName];
        }
    }
    /** Whether the package explicitly sets any of the format properties (like `main`). */
    function hasExplicitFormatProperties(parsedPackage) {
        return Object.keys(parsedPackage).some((fieldName) => knownFormatPackageJsonFormatFields.includes(fieldName));
    }
    /**
     * Normalizes the specified path by replacing backslash separators with Posix
     * forward slash separators.
     */
    function normalizePath(path) {
        const result = path.replace(/\\/g, '/');
        return result.startsWith('.') ? result : `./${result}`;
    }
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGFja2FnZXIuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi8uLi8uLi8uLi9wYWNrYWdlcy9iYXplbC9zcmMvbmdfcGFja2FnZS9wYWNrYWdlci50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7O0dBTUc7QUFFSCxPQUFPLEtBQUssRUFBRSxNQUFNLElBQUksQ0FBQztBQUN6QixPQUFPLEtBQUssSUFBSSxNQUFNLE1BQU0sQ0FBQztBQUM3QixPQUFPLEVBQUMsUUFBUSxFQUFDLE1BQU0sWUFBWSxDQUFDO0FBR3BDLE9BQU8sRUFBQyxrQ0FBa0MsRUFBQyxNQUFNLDhCQUE4QixDQUFDO0FBRWhGOzs7R0FHRztBQUNILE1BQU0sa0NBQWtDLEdBQUcsQ0FBQyxNQUFNLEVBQUUsU0FBUyxFQUFFLFFBQVEsQ0FBVSxDQUFDO0FBd0JsRixvQkFBb0I7QUFDcEIsSUFBSSxDQUFDLE9BQU8sQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7QUFFNUIsU0FBUyxJQUFJLENBQUMsSUFBYztJQUMxQiwwRkFBMEY7SUFDMUYsNkZBQTZGO0lBQzdGLE1BQU0sYUFBYSxHQUFHLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQztJQUU5Qiw2Q0FBNkM7SUFDN0MsU0FBUyxnQkFBZ0IsQ0FBQyxDQUFTO1FBQ2pDLE9BQU8sQ0FBQyxDQUFDLE9BQU8sQ0FBQyxVQUFVLEVBQUUsSUFBSSxDQUFDLENBQUM7SUFDckMsQ0FBQztJQUVELHFEQUFxRDtJQUNyRCxNQUFNLE1BQU0sR0FBRyxFQUFFLENBQUMsWUFBWSxDQUFDLGFBQWEsRUFBRSxPQUFPLENBQUMsQ0FBQyxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUMsR0FBRyxDQUFDLGdCQUFnQixDQUFDLENBQUM7SUFFekYsTUFBTTtJQUNKLHdDQUF3QztJQUN4QyxpQkFBaUI7SUFFakIsOEVBQThFO0lBQzlFLGlCQUFpQjtJQUVqQixrRkFBa0Y7SUFDbEYsV0FBVztJQUVYLG1DQUFtQztJQUNuQyxRQUFRO0lBRVIsc0NBQXNDO0lBQ3RDLFdBQVc7SUFFWCxvQ0FBb0M7SUFDcEMsVUFBVTtJQUVWLCtEQUErRDtJQUMvRCxjQUFjO0lBRWQsMEVBQTBFO0lBQzFFLGtCQUFrQjtJQUVsQixzQ0FBc0M7SUFDdEMsd0JBQXdCLEVBQ3pCLEdBQUcsTUFBTSxDQUFDO0lBRVgsTUFBTSxPQUFPLEdBQUcsSUFBSSxDQUFDLEtBQUssQ0FBQyxVQUFVLENBQW9CLENBQUM7SUFDMUQsTUFBTSxlQUFlLEdBQUcsSUFBSSxDQUFDLEtBQUssQ0FBQyxrQkFBa0IsQ0FBb0IsQ0FBQztJQUMxRSxNQUFNLFdBQVcsR0FBRyxJQUFJLENBQUMsS0FBSyxDQUFDLGNBQWMsQ0FBb0IsQ0FBQztJQUNsRSxNQUFNLFFBQVEsR0FBRyxJQUFJLENBQUMsS0FBSyxDQUFDLFdBQVcsQ0FBb0IsQ0FBQztJQUM1RCxNQUFNLHFCQUFxQixHQUFHLElBQUksQ0FBQyxLQUFLLENBQUMsd0JBQXdCLENBQWEsQ0FBQztJQUUvRSxJQUFJLFFBQVEsRUFBRSxDQUFDO1FBQ2IsUUFBUSxDQUFDLFFBQVEsRUFBRSxXQUFXLENBQUMsQ0FBQztJQUNsQyxDQUFDO0lBRUQsSUFBSSxXQUFXLEVBQUUsQ0FBQztRQUNoQixRQUFRLENBQUMsV0FBVyxFQUFFLFNBQVMsQ0FBQyxDQUFDO0lBQ25DLENBQUM7SUFFRDs7Ozs7T0FLRztJQUNILFNBQVMsU0FBUyxDQUFDLGtCQUEwQixFQUFFLFdBQTRCO1FBQ3pFLE1BQU0sVUFBVSxHQUFHLElBQUksQ0FBQyxJQUFJLENBQUMsaUJBQWlCLEVBQUUsa0JBQWtCLENBQUMsQ0FBQztRQUVwRSxrREFBa0Q7UUFDbEQsRUFBRSxDQUFDLFNBQVMsQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUFDLFVBQVUsQ0FBQyxFQUFFLEVBQUMsU0FBUyxFQUFFLElBQUksRUFBQyxDQUFDLENBQUM7UUFDMUQsRUFBRSxDQUFDLGFBQWEsQ0FBQyxVQUFVLEVBQUUsV0FBVyxDQUFDLENBQUM7SUFDNUMsQ0FBQztJQUVEOzs7OztPQUtHO0lBQ0gsU0FBUyxRQUFRLENBQUMsU0FBaUIsRUFBRSxrQkFBMEI7UUFDN0QsTUFBTSxXQUFXLEdBQUcsRUFBRSxDQUFDLFlBQVksQ0FBQyxTQUFTLEVBQUUsTUFBTSxDQUFDLENBQUM7UUFDdkQsU0FBUyxDQUFDLGtCQUFrQixFQUFFLFdBQVcsQ0FBQyxDQUFDO0lBQzdDLENBQUM7SUFFRDs7Ozs7OztPQU9HO0lBQ0gsU0FBUyw0QkFBNEIsQ0FBQyxJQUFtQjtRQUN2RCxPQUFPLElBQUksQ0FBQyxRQUFRLENBQUMsaUJBQWlCLEVBQUUsSUFBSSxDQUFDLFNBQVMsQ0FBQyxDQUFDO0lBQzFELENBQUM7SUFFRCwrRUFBK0U7SUFDL0UsU0FBUywyQkFBMkIsQ0FBQyxJQUFtQjtRQUN0RCwwRkFBMEY7UUFDMUYsZ0dBQWdHO1FBQ2hHLDJGQUEyRjtRQUMzRix5RkFBeUY7UUFDekYsd0VBQXdFO1FBQ3hFLE9BQU8sNEJBQTRCLENBQUMsSUFBSSxDQUFDLENBQUMsT0FBTyxDQUFDLGlCQUFpQixFQUFFLFlBQVksQ0FBQyxDQUFDO0lBQ3JGLENBQUM7SUFFRDs7O09BR0c7SUFDSCxTQUFTLG9CQUFvQixDQUFDLFVBQWtCO1FBQzlDLE9BQU8sVUFBVSxDQUFDLEtBQUssQ0FBQyxHQUFHLFFBQVEsQ0FBQyxjQUFjLEdBQUcsQ0FBQyxNQUFNLENBQUMsQ0FBQztJQUNoRSxDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILFNBQVMscUJBQXFCLENBQUMsVUFBa0I7UUFDL0MsT0FBTyxvQkFBb0IsQ0FBQyxVQUFVLENBQUMsS0FBSyxFQUFFLENBQUM7SUFDakQsQ0FBQztJQUVELE1BQU0sdUJBQXVCLEdBQUcsT0FBTyxDQUFDLE9BQU8sQ0FBQyxDQUFDLElBQUksRUFBRSxFQUFFLENBQ3ZELGtDQUFrQyxDQUFDLElBQUksRUFBRSxRQUFRLENBQUMsQ0FDbkQsQ0FBQztJQUVGLElBQUksdUJBQXVCLENBQUMsTUFBTSxFQUFFLENBQUM7UUFDbkMsT0FBTyxDQUFDLEtBQUssQ0FBQyx1QkFBdUIsQ0FBQyxDQUFDO1FBQ3ZDLE9BQU8sQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFDbEIsQ0FBQztJQUVELE1BQU0sU0FBUyxHQUFHLFFBQVEsQ0FBQyxNQUFNLEVBQUUsRUFBQyxHQUFHLEVBQUUsUUFBUSxDQUFDLFVBQVUsQ0FBQyxJQUFJLEVBQUMsQ0FBQyxDQUFDO0lBQ3BFLG1GQUFtRjtJQUNuRixTQUFTLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQyxFQUFFLEVBQUUsQ0FBQyxRQUFRLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxRQUFRLENBQUMsVUFBVSxDQUFDLElBQUksRUFBRSxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDO0lBRTlFLCtFQUErRTtJQUMvRSxtRkFBbUY7SUFDbkYsaUNBQWlDO0lBQ2pDLGVBQWUsQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDLEVBQUUsRUFBRSxDQUFDLFFBQVEsQ0FBQyxDQUFDLENBQUMsSUFBSSxFQUFFLDJCQUEyQixDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztJQUVqRixLQUFLLE1BQU0sSUFBSSxJQUFJLFdBQVcsRUFBRSxDQUFDO1FBQy9CLCtFQUErRTtRQUMvRSwwRkFBMEY7UUFDMUYsTUFBTSxrQkFBa0IsR0FBRyw0QkFBNEIsQ0FBQyxJQUFJLENBQUMsQ0FBQztRQUM5RCxJQUFJLE9BQU8sR0FBRyxFQUFFLENBQUMsWUFBWSxDQUFDLElBQUksQ0FBQyxJQUFJLEVBQUUsTUFBTSxDQUFDLENBQUM7UUFFakQsa0VBQWtFO1FBQ2xFLElBQUksSUFBSSxDQUFDLFFBQVEsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEtBQUssY0FBYyxFQUFFLENBQUM7WUFDaEQsTUFBTSxvQkFBb0IsR0FBRyxrQkFBa0IsS0FBSyxjQUFjLENBQUM7WUFDbkUsTUFBTSxXQUFXLEdBQUcsSUFBSSxDQUFDLEtBQUssQ0FBQyxPQUFPLENBQWdCLENBQUM7WUFDdkQsTUFBTSxXQUFXLEdBQUcsV0FBVyxDQUFDLE1BQU0sQ0FBQyxDQUFDO1lBRXhDLDZFQUE2RTtZQUM3RSxrRkFBa0Y7WUFDbEYsSUFBSSxDQUFDLG9CQUFvQixFQUFFLENBQUM7Z0JBQzFCLE1BQU0sS0FBSyxDQUNULDZEQUE2RCxJQUFJLENBQUMsU0FBUyxLQUFLO29CQUM5RSwyRUFBMkUsQ0FDOUUsQ0FBQztZQUNKLENBQUM7WUFFRCwwRUFBMEU7WUFDMUUsK0RBQStEO1lBQy9ELElBQUksV0FBVyxLQUFLLFFBQVEsQ0FBQyxjQUFjLEVBQUUsQ0FBQztnQkFDNUMsTUFBTSxLQUFLLENBQ1Qsb0VBQW9FO29CQUNsRSx3QkFBd0IsUUFBUSxDQUFDLGNBQWMscUJBQXFCLFdBQVcsR0FBRyxDQUNyRixDQUFDO1lBQ0osQ0FBQztZQUVELElBQUksY0FBYyxHQUFHLGlDQUFpQyxDQUNwRCxrQkFBa0IsRUFDbEIsV0FBVyxFQUNYLEtBQUssQ0FDTixDQUFDO1lBRUYsY0FBYyxHQUFHLHdCQUF3QixDQUFDLGNBQWMsQ0FBQyxDQUFDO1lBRTFELCtEQUErRDtZQUMvRCxPQUFPLEdBQUcsSUFBSSxDQUFDLFNBQVMsQ0FBQyxjQUFjLEVBQUUsSUFBSSxFQUFFLENBQUMsQ0FBQyxDQUFDO1FBQ3BELENBQUM7UUFFRCxTQUFTLENBQUMsa0JBQWtCLEVBQUUsT0FBTyxDQUFDLENBQUM7SUFDekMsQ0FBQztJQUVEOzs7Ozs7OztPQVFHO0lBQ0gsU0FBUyxpQ0FBaUMsQ0FDeEMsMEJBQWtDLEVBQ2xDLGFBQW9DLEVBQ3BDLHNCQUErQjtRQUUvQixNQUFNLFdBQVcsR0FBZ0IsRUFBQyxHQUFHLGFBQWEsRUFBQyxDQUFDO1FBQ3BELE1BQU0sV0FBVyxHQUFHLFdBQVcsQ0FBQyxNQUFNLENBQUMsQ0FBQztRQUN4QyxNQUFNLGNBQWMsR0FBRyxRQUFRLENBQUMsV0FBVyxDQUFDLFdBQVcsQ0FBQyxDQUFDO1FBQ3pELE1BQU0sd0JBQXdCLEdBQUcsSUFBSSxDQUFDLE9BQU8sQ0FBQywwQkFBMEIsQ0FBQyxDQUFDO1FBRTFFLHFFQUFxRTtRQUNyRSw2RUFBNkU7UUFDN0Usb0VBQW9FO1FBQ3BFLElBQUksQ0FBQyxjQUFjLEVBQUUsQ0FBQztZQUNwQixzRUFBc0U7WUFDdEUsbUVBQW1FO1lBQ25FLG9EQUFvRDtZQUNwRCwwRUFBMEU7WUFDMUUsa0VBQWtFO1lBQ2xFLHlEQUF5RDtZQUN6RCxPQUFPLENBQUMsS0FBSyxDQUFDLHlDQUF5QyxFQUFFLFdBQVcsQ0FBQyxDQUFDO1lBQ3RFLE9BQU8sQ0FBQyxLQUFLLENBQUMsc0RBQXNELENBQUMsQ0FBQztZQUN0RSxPQUFPLENBQUMsS0FBSyxDQUNYLGtGQUFrRixDQUNuRixDQUFDO1lBQ0YsT0FBTyxXQUFXLENBQUM7UUFDckIsQ0FBQztRQUVELHlGQUF5RjtRQUN6RixrRkFBa0Y7UUFDbEYsZ0ZBQWdGO1FBQ2hGLElBQ0UsY0FBYyxDQUFDLFlBQVk7WUFDM0IsQ0FBQyxzQkFBc0I7WUFDdkIsMkJBQTJCLENBQUMsV0FBVyxDQUFDLEVBQ3hDLENBQUM7WUFDRCxPQUFPLENBQUMsS0FBSyxDQUFDLDBFQUEwRSxDQUFDLENBQUM7WUFDMUYsT0FBTyxDQUFDLEtBQUssQ0FDWCxvRUFBb0U7Z0JBQ2xFLDRCQUE0QixDQUMvQixDQUFDO1lBQ0YsT0FBTyxDQUFDLEtBQUssQ0FBQyx1RUFBdUUsQ0FBQyxDQUFDO1lBQ3ZGLE9BQU8sV0FBVyxDQUFDO1FBQ3JCLENBQUM7UUFFRCxNQUFNLHVCQUF1QixHQUFHLGNBQWMsQ0FBQyxvQkFBb0IsQ0FBQztRQUNwRSxNQUFNLHNCQUFzQixHQUFHLDJCQUEyQixDQUFDLGNBQWMsQ0FBQyxPQUFPLENBQUMsQ0FBQztRQUVuRixXQUFXLENBQUMsTUFBTSxHQUFHLGFBQWEsQ0FDaEMsSUFBSSxDQUFDLFFBQVEsQ0FBQyx3QkFBd0IsRUFBRSx1QkFBdUIsQ0FBQyxDQUNqRSxDQUFDO1FBQ0YsV0FBVyxDQUFDLE9BQU8sR0FBRyxhQUFhLENBQ2pDLElBQUksQ0FBQyxRQUFRLENBQUMsd0JBQXdCLEVBQUUsc0JBQXNCLENBQUMsQ0FDaEUsQ0FBQztRQUVGLE9BQU8sV0FBVyxDQUFDO0lBQ3JCLENBQUM7SUFFRDs7O09BR0c7SUFDSCxTQUFTLHdCQUF3QixDQUFDLFdBQWtDO1FBQ2xFLElBQUksV0FBVyxDQUFDLElBQUksS0FBSyxTQUFTLElBQUksV0FBVyxDQUFDLElBQUksS0FBSyxRQUFRLEVBQUUsQ0FBQztZQUNwRSxNQUFNLEtBQUssQ0FDVCx1RUFBdUU7Z0JBQ3JFLGdGQUFnRixDQUNuRixDQUFDO1FBQ0osQ0FBQztRQUVELE1BQU0sY0FBYyxHQUFnQixFQUFDLEdBQUcsV0FBVyxFQUFDLENBQUM7UUFFckQsY0FBYyxDQUFDLElBQUksR0FBRyxRQUFRLENBQUM7UUFFL0IscUVBQXFFO1FBQ3JFLGdFQUFnRTtRQUNoRSwwQkFBMEIsQ0FBQyxjQUFjLEVBQUUsZ0JBQWdCLEVBQUUsRUFBQyxPQUFPLEVBQUUsZ0JBQWdCLEVBQUMsQ0FBQyxDQUFDO1FBRTFGLHlGQUF5RjtRQUN6RixpRUFBaUU7UUFDakUsS0FBSyxNQUFNLENBQUMsVUFBVSxFQUFFLFVBQVUsQ0FBQyxJQUFJLE1BQU0sQ0FBQyxPQUFPLENBQUMsUUFBUSxDQUFDLFdBQVcsQ0FBQyxFQUFFLENBQUM7WUFDNUUsTUFBTSxPQUFPLEdBQUcscUJBQXFCLENBQUMsVUFBVSxDQUFDO2dCQUMvQyxDQUFDLENBQUMsS0FBSyxvQkFBb0IsQ0FBQyxVQUFVLENBQUMsRUFBRTtnQkFDekMsQ0FBQyxDQUFDLEdBQUcsQ0FBQztZQUNSLE1BQU0sdUJBQXVCLEdBQUcsVUFBVSxDQUFDLG9CQUFvQixDQUFDO1lBQ2hFLE1BQU0sb0JBQW9CLEdBQUcsMkJBQTJCLENBQUMsVUFBVSxDQUFDLE9BQU8sQ0FBQyxDQUFDO1lBRTdFLG1GQUFtRjtZQUNuRixnRkFBZ0Y7WUFDaEYsc0RBQXNEO1lBQ3RELDBCQUEwQixDQUFDLGNBQWMsRUFBRSxPQUFPLEVBQUU7Z0JBQ2xELEtBQUssRUFBRSxhQUFhLENBQUMsb0JBQW9CLENBQUM7Z0JBQzFDLHlEQUF5RDtnQkFDekQsT0FBTyxFQUFFLGFBQWEsQ0FBQyx1QkFBdUIsQ0FBQzthQUNoRCxDQUFDLENBQUM7UUFDTCxDQUFDO1FBRUQsMkJBQTJCLENBQUMsV0FBVyxDQUFDLENBQUM7UUFFekMsT0FBTyxjQUFjLENBQUM7SUFDeEIsQ0FBQztJQUVELFNBQVMsMkJBQTJCLENBQUMsV0FBd0I7UUFDM0Qsd0VBQXdFO1FBQ3hFLDBFQUEwRTtRQUMxRSxJQUFJLFdBQVcsQ0FBQyxXQUFXLEtBQUssS0FBSyxJQUFJLHFCQUFxQixDQUFDLE1BQU0sS0FBSyxDQUFDLEVBQUUsQ0FBQztZQUM1RSxPQUFPO1FBQ1QsQ0FBQztRQUVELElBQUksV0FBVyxDQUFDLFdBQVcsS0FBSyxJQUFJLEVBQUUsQ0FBQztZQUNyQyxNQUFNLEtBQUssQ0FDVCxvREFBb0Q7Z0JBQ2xELGlHQUFpRyxDQUNwRyxDQUFDO1FBQ0osQ0FBQztRQUVELE1BQU0sV0FBVyxHQUFHLFdBQVcsQ0FBQyxXQUEyQyxDQUFDO1FBQzVFLE1BQU0saUJBQWlCLEdBQUcscUJBQXFCLENBQUMsR0FBRyxDQUNqRCxDQUFDLGdCQUFnQixFQUFFLEVBQUUsQ0FBQyxLQUFLLFFBQVEsQ0FBQyxXQUFXLENBQUMsZ0JBQWdCLENBQUMsQ0FBQyxvQkFBb0IsRUFBRSxDQUN6RixDQUFDO1FBQ0YsTUFBTSxrQkFBa0IsR0FBRyxpQkFBaUIsQ0FBQyxNQUFNLENBQ2pELENBQUMsQ0FBQyxFQUFFLEVBQUU7UUFDSiwwRUFBMEU7UUFDMUUsV0FBVyxLQUFLLEtBQUs7WUFDckIsZ0ZBQWdGO1lBQ2hGLENBQUMsQ0FBQyxXQUFXLElBQUksRUFBRSxDQUFDLENBQUMsUUFBUSxDQUFDLENBQUMsQ0FBQyxDQUNuQyxDQUFDO1FBRUYsSUFBSSxrQkFBa0IsQ0FBQyxNQUFNLEdBQUcsQ0FBQyxFQUFFLENBQUM7WUFDbEMsTUFBTSxLQUFLLENBQ1QsOERBQThEO2dCQUM1RCx1REFBdUQ7Z0JBQ3ZELGtCQUFrQixDQUFDLElBQUksQ0FBQyxPQUFPLENBQUMsQ0FDbkMsQ0FBQztRQUNKLENBQUM7UUFFRCw4RUFBOEU7UUFDOUUsMENBQTBDO1FBQzFDLE1BQU0sZUFBZSxHQUNuQixXQUFXLEtBQUssS0FBSztZQUNuQixDQUFDLENBQUMsQ0FBQyxXQUFXLElBQUksRUFBRSxDQUFDLENBQUMsTUFBTSxDQUN4QixDQUFDLENBQUMsRUFBRSxFQUFFLENBQUMsQ0FBQyxDQUFDLFFBQVEsQ0FBQyxVQUFVLENBQUMsSUFBSSxDQUFDLGlCQUFpQixDQUFDLFFBQVEsQ0FBQyxDQUFDLENBQUMsQ0FDaEU7WUFDSCxDQUFDLENBQUMsRUFBRSxDQUFDO1FBQ1QsSUFBSSxlQUFlLENBQUMsTUFBTSxHQUFHLENBQUMsRUFBRSxDQUFDO1lBQy9CLE1BQU0sS0FBSyxDQUNULG1HQUFtRztnQkFDakcseUZBQXlGO2dCQUN6Rix3QkFBd0I7Z0JBQ3hCLGVBQWUsQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUFDLENBQ2hDLENBQUM7UUFDSixDQUFDO0lBQ0gsQ0FBQztJQUVEOzs7T0FHRztJQUNILFNBQVMsMEJBQTBCLENBQ2pDLFdBQXdCLEVBQ3hCLE9BQWUsRUFDZixPQUEwQjtRQUUxQixJQUFJLFdBQVcsQ0FBQyxPQUFPLEtBQUssU0FBUyxFQUFFLENBQUM7WUFDdEMsV0FBVyxDQUFDLE9BQU8sR0FBRyxFQUFFLENBQUM7UUFDM0IsQ0FBQztRQUNELElBQUksV0FBVyxDQUFDLE9BQU8sQ0FBQyxPQUFPLENBQUMsS0FBSyxTQUFTLEVBQUUsQ0FBQztZQUMvQyxXQUFXLENBQUMsT0FBTyxDQUFDLE9BQU8sQ0FBQyxHQUFHLEVBQUUsQ0FBQztRQUNwQyxDQUFDO1FBRUQsTUFBTSxhQUFhLEdBQUcsV0FBVyxDQUFDLE9BQU8sQ0FBQyxPQUFPLENBQUMsQ0FBQztRQUVuRCxpRkFBaUY7UUFDakYsa0ZBQWtGO1FBQ2xGLGlGQUFpRjtRQUNqRixLQUFLLE1BQU0sYUFBYSxJQUFJLE1BQU0sQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUE4QixFQUFFLENBQUM7WUFDOUUsSUFBSSxhQUFhLENBQUMsYUFBYSxDQUFDLEtBQUssU0FBUyxFQUFFLENBQUM7Z0JBQy9DLE1BQU0sS0FBSyxDQUNULDZDQUE2QyxPQUFPLFdBQVcsYUFBYSxJQUFJO29CQUM5RSxpRUFBaUUsQ0FDcEUsQ0FBQztZQUNKLENBQUM7WUFFRCxnRkFBZ0Y7WUFDaEYsNEVBQTRFO1lBQzVFLGFBQWEsQ0FBQyxhQUFhLENBQUMsR0FBRyxPQUFPLENBQUMsYUFBYSxDQUFDLENBQUM7UUFDeEQsQ0FBQztJQUNILENBQUM7SUFFRCxzRkFBc0Y7SUFDdEYsU0FBUywyQkFBMkIsQ0FBQyxhQUFvQztRQUN2RSxPQUFPLE1BQU0sQ0FBQyxJQUFJLENBQUMsYUFBYSxDQUFDLENBQUMsSUFBSSxDQUFDLENBQUMsU0FBaUIsRUFBRSxFQUFFLENBQzNELGtDQUFrQyxDQUFDLFFBQVEsQ0FBQyxTQUF5QyxDQUFDLENBQ3ZGLENBQUM7SUFDSixDQUFDO0lBRUQ7OztPQUdHO0lBQ0gsU0FBUyxhQUFhLENBQUMsSUFBWTtRQUNqQyxNQUFNLE1BQU0sR0FBRyxJQUFJLENBQUMsT0FBTyxDQUFDLEtBQUssRUFBRSxHQUFHLENBQUMsQ0FBQztRQUN4QyxPQUFPLE1BQU0sQ0FBQyxVQUFVLENBQUMsR0FBRyxDQUFDLENBQUMsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsS0FBSyxNQUFNLEVBQUUsQ0FBQztJQUN6RCxDQUFDO0FBQ0gsQ0FBQyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxuICogQGxpY2Vuc2VcbiAqIENvcHlyaWdodCBHb29nbGUgTExDIEFsbCBSaWdodHMgUmVzZXJ2ZWQuXG4gKlxuICogVXNlIG9mIHRoaXMgc291cmNlIGNvZGUgaXMgZ292ZXJuZWQgYnkgYW4gTUlULXN0eWxlIGxpY2Vuc2UgdGhhdCBjYW4gYmVcbiAqIGZvdW5kIGluIHRoZSBMSUNFTlNFIGZpbGUgYXQgaHR0cHM6Ly9hbmd1bGFyLmRldi9saWNlbnNlXG4gKi9cblxuaW1wb3J0ICogYXMgZnMgZnJvbSAnZnMnO1xuaW1wb3J0ICogYXMgcGF0aCBmcm9tICdwYXRoJztcbmltcG9ydCB7Z2xvYlN5bmN9IGZyb20gJ3RpbnlnbG9iYnknO1xuXG5pbXBvcnQge0JhemVsRmlsZUluZm8sIFBhY2thZ2VNZXRhZGF0YX0gZnJvbSAnLi9hcGknO1xuaW1wb3J0IHthbmFseXplRmlsZUFuZEVuc3VyZU5vQ3Jvc3NJbXBvcnRzfSBmcm9tICcuL2Nyb3NzX2VudHJ5X3BvaW50c19pbXBvcnRzJztcblxuLyoqXG4gKiBMaXN0IG9mIGtub3duIGBwYWNrYWdlLmpzb25gIGZpZWxkcyB3aGljaCBwcm92aWRlIGluZm9ybWF0aW9uIGFib3V0XG4gKiBzdXBwb3J0ZWQgcGFja2FnZSBmb3JtYXRzIGFuZCB0aGVpciBhc3NvY2lhdGVkIGVudHJ5IHBhdGhzLlxuICovXG5jb25zdCBrbm93bkZvcm1hdFBhY2thZ2VKc29uRm9ybWF0RmllbGRzID0gWydtYWluJywgJ3R5cGluZ3MnLCAnbW9kdWxlJ10gYXMgY29uc3Q7XG5cbi8qKiBVbmlvbiB0eXBlIG1hdGNoaW5nIGtub3duIGBwYWNrYWdlLmpzb25gIGZvcm1hdCBmaWVsZHMuICovXG50eXBlIEtub3duUGFja2FnZUpzb25Gb3JtYXRGaWVsZHMgPSAodHlwZW9mIGtub3duRm9ybWF0UGFja2FnZUpzb25Gb3JtYXRGaWVsZHMpW251bWJlcl07XG5cbi8qKlxuICogVHlwZSBkZXNjcmliaW5nIHRoZSBjb25kaXRpb25hbCBleHBvcnRzIGRlc2NyaXB0b3IgZm9yIGFuIGVudHJ5LXBvaW50LlxuICogaHR0cHM6Ly9ub2RlanMub3JnL2FwaS9wYWNrYWdlcy5odG1sI3BhY2thZ2VzX2NvbmRpdGlvbmFsX2V4cG9ydHNcbiAqL1xudHlwZSBDb25kaXRpb25hbEV4cG9ydCA9IHtcbiAgdHlwZXM/OiBzdHJpbmc7XG4gIGRlZmF1bHQ/OiBzdHJpbmc7XG59O1xuXG4vKiogVHlwZSBkZXNjcmliaW5nIGEgYHBhY2thZ2UuanNvbmAgdGhlIHBhY2thZ2VyIGRlYWxzIHdpdGguICovXG50eXBlIFBhY2thZ2VKc29uID0ge1xuICBba2V5IGluIEtub3duUGFja2FnZUpzb25Gb3JtYXRGaWVsZHNdPzogc3RyaW5nO1xufSAmIHtcbiAgbmFtZTogc3RyaW5nO1xuICB0eXBlPzogc3RyaW5nO1xuICBzaWRlRWZmZWN0cz86IHN0cmluZ1tdIHwgYm9vbGVhbjtcbiAgZXhwb3J0cz86IFJlY29yZDxzdHJpbmcsIENvbmRpdGlvbmFsRXhwb3J0Pjtcbn07XG5cbi8vIE1haW4gZW50cnktcG9pbnQuXG5tYWluKHByb2Nlc3MuYXJndi5zbGljZSgyKSk7XG5cbmZ1bmN0aW9uIG1haW4oYXJnczogc3RyaW5nW10pOiB2b2lkIHtcbiAgLy8gVGhpcyB1dGlsaXR5IGV4cGVjdHMgYWxsIG9mIGl0cyBhcmd1bWVudHMgdG8gYmUgc3BlY2lmaWVkIGluIGEgcGFyYW1zIGZpbGUgZ2VuZXJhdGVkIGJ5XG4gIC8vIGJhemVsIChzZWUgaHR0cHM6Ly9kb2NzLmJhemVsLmJ1aWxkL3ZlcnNpb25zL21hc3Rlci9za3lsYXJrL2xpYi9BcmdzLmh0bWwjdXNlX3BhcmFtX2ZpbGUpLlxuICBjb25zdCBwYXJhbUZpbGVQYXRoID0gYXJnc1swXTtcblxuICAvLyBCYXplbCBwYXJhbXMgbWF5IGJlIHN1cnJvdW5kZWQgd2l0aCBxdW90ZXNcbiAgZnVuY3Rpb24gdW5xdW90ZVBhcmFtZXRlcihzOiBzdHJpbmcpIHtcbiAgICByZXR1cm4gcy5yZXBsYWNlKC9eJyguKiknJC8sICckMScpO1xuICB9XG5cbiAgLy8gUGFyYW1ldGVycyBhcmUgc3BlY2lmaWVkIGluIHRoZSBmaWxlIG9uZSBwZXIgbGluZS5cbiAgY29uc3QgcGFyYW1zID0gZnMucmVhZEZpbGVTeW5jKHBhcmFtRmlsZVBhdGgsICd1dGYtOCcpLnNwbGl0KCdcXG4nKS5tYXAodW5xdW90ZVBhcmFtZXRlcik7XG5cbiAgY29uc3QgW1xuICAgIC8vIE91dHB1dCBkaXJlY3RvcnkgZm9yIHRoZSBucG0gcGFja2FnZS5cbiAgICBvdXRwdXREaXJFeGVjUGF0aCxcblxuICAgIC8vIFRoZSBwYWNrYWdlIHNlZ21lbnQgb2YgdGhlIG5nX3BhY2thZ2UgcnVsZSdzIGxhYmVsIChlLmcuICdwYWNrYWdlL2NvbW1vbicpLlxuICAgIG93bmluZ1BhY2thZ2VOYW1lLFxuXG4gICAgLy8gSlNPTiBkYXRhIGNhcHR1cmluZyBtZXRhZGF0YSBvZiB0aGUgcGFja2FnZSBiZWluZyBidWlsdC4gU2VlIGBQYWNrYWdlTWV0YWRhdGFgLlxuICAgIG1ldGFkYXRhQXJnLFxuXG4gICAgLy8gUGF0aCB0byB0aGUgcGFja2FnZSdzIFJFQURNRS5tZC5cbiAgICByZWFkbWVNZCxcblxuICAgIC8vIFBhdGggdG8gdGhlIHBhY2thZ2UncyBMSUNFTlNFIGZpbGUuXG4gICAgbGljZW5zZUZpbGUsXG5cbiAgICAvLyBMaXN0IG9mIGluZGl2aWR1YWwgRVMyMDIyIG1vZHVsZXNcbiAgICBlc20yMDIyQXJnLFxuXG4gICAgLy8gTGlzdCBvZiBzdGF0aWMgZmlsZXMgdGhhdCBzaG91bGQgYmUgY29waWVkIGludG8gdGhlIHBhY2thZ2UuXG4gICAgc3RhdGljRmlsZXNBcmcsXG5cbiAgICAvLyBMaXN0IG9mIGFsbCB0eXBlIGRlZmluaXRpb25zIHRoYXQgbmVlZCB0byBwYWNrYWdlZCBpbnRvIHRoZSBuZ19wYWNrYWdlLlxuICAgIHR5cGVEZWZpbml0aW9uc0FyZyxcblxuICAgIC8vIExpc3Qgb2Ygc2lkZS1lZmZlY3RmdWwgZW50cnktcG9pbnRzXG4gICAgc2lkZUVmZmVjdEVudHJ5UG9pbnRzQXJnLFxuICBdID0gcGFyYW1zO1xuXG4gIGNvbnN0IGVzbTIwMjIgPSBKU09OLnBhcnNlKGVzbTIwMjJBcmcpIGFzIEJhemVsRmlsZUluZm9bXTtcbiAgY29uc3QgdHlwZURlZmluaXRpb25zID0gSlNPTi5wYXJzZSh0eXBlRGVmaW5pdGlvbnNBcmcpIGFzIEJhemVsRmlsZUluZm9bXTtcbiAgY29uc3Qgc3RhdGljRmlsZXMgPSBKU09OLnBhcnNlKHN0YXRpY0ZpbGVzQXJnKSBhcyBCYXplbEZpbGVJbmZvW107XG4gIGNvbnN0IG1ldGFkYXRhID0gSlNPTi5wYXJzZShtZXRhZGF0YUFyZykgYXMgUGFja2FnZU1ldGFkYXRhO1xuICBjb25zdCBzaWRlRWZmZWN0RW50cnlQb2ludHMgPSBKU09OLnBhcnNlKHNpZGVFZmZlY3RFbnRyeVBvaW50c0FyZykgYXMgc3RyaW5nW107XG5cbiAgaWYgKHJlYWRtZU1kKSB7XG4gICAgY29weUZpbGUocmVhZG1lTWQsICdSRUFETUUubWQnKTtcbiAgfVxuXG4gIGlmIChsaWNlbnNlRmlsZSkge1xuICAgIGNvcHlGaWxlKGxpY2Vuc2VGaWxlLCAnTElDRU5TRScpO1xuICB9XG5cbiAgLyoqXG4gICAqIFdyaXRlcyBhIGZpbGUgd2l0aCB0aGUgc3BlY2lmaWVkIGNvbnRlbnQgaW50byB0aGUgcGFja2FnZSBvdXRwdXQuXG4gICAqIEBwYXJhbSBvdXRwdXRSZWxhdGl2ZVBhdGggUmVsYXRpdmUgcGF0aCBpbiB0aGUgb3V0cHV0IGRpcmVjdG9yeSB3aGVyZSB0aGVcbiAgICogICBmaWxlIGlzIHdyaXR0ZW4gdG8uXG4gICAqIEBwYXJhbSBmaWxlQ29udGVudCBDb250ZW50IG9mIHRoZSBmaWxlLlxuICAgKi9cbiAgZnVuY3Rpb24gd3JpdGVGaWxlKG91dHB1dFJlbGF0aXZlUGF0aDogc3RyaW5nLCBmaWxlQ29udGVudDogc3RyaW5nIHwgQnVmZmVyKSB7XG4gICAgY29uc3Qgb3V0cHV0UGF0aCA9IHBhdGguam9pbihvdXRwdXREaXJFeGVjUGF0aCwgb3V0cHV0UmVsYXRpdmVQYXRoKTtcblxuICAgIC8vIEFsd2F5cyBlbnN1cmUgdGhhdCB0aGUgdGFyZ2V0IGRpcmVjdG9yeSBleGlzdHMuXG4gICAgZnMubWtkaXJTeW5jKHBhdGguZGlybmFtZShvdXRwdXRQYXRoKSwge3JlY3Vyc2l2ZTogdHJ1ZX0pO1xuICAgIGZzLndyaXRlRmlsZVN5bmMob3V0cHV0UGF0aCwgZmlsZUNvbnRlbnQpO1xuICB9XG5cbiAgLyoqXG4gICAqIENvcGllcyBhIGZpbGUgaW50byB0aGUgcGFja2FnZSBvdXRwdXQgdG8gdGhlIHNwZWNpZmllZCBsb2NhdGlvbi5cbiAgICogQHBhcmFtIGlucHV0UGF0aCBGaWxlIHRoYXQgc2hvdWxkIGJlIGNvcGllZC5cbiAgICogQHBhcmFtIG91dHB1dFJlbGF0aXZlUGF0aCBSZWxhdGl2ZSBwYXRoIGluIHRoZSBvdXRwdXQgZGlyZWN0b3J5IHdoZXJlIHRoZVxuICAgKiAgIGZpbGUgaXMgd3JpdHRlbiB0by5cbiAgICovXG4gIGZ1bmN0aW9uIGNvcHlGaWxlKGlucHV0UGF0aDogc3RyaW5nLCBvdXRwdXRSZWxhdGl2ZVBhdGg6IHN0cmluZykge1xuICAgIGNvbnN0IGZpbGVDb250ZW50ID0gZnMucmVhZEZpbGVTeW5jKGlucHV0UGF0aCwgJ3V0ZjgnKTtcbiAgICB3cml0ZUZpbGUob3V0cHV0UmVsYXRpdmVQYXRoLCBmaWxlQ29udGVudCk7XG4gIH1cblxuICAvKipcbiAgICogR2V0cyB0aGUgcmVsYXRpdmUgcGF0aCBmb3IgdGhlIGdpdmVuIGZpbGUgd2l0aGluIHRoZSBvd25pbmcgcGFja2FnZS4gVGhpc1xuICAgKiBhc3N1bWVzIHRoZSBmaWxlIGlzIGNvbnRhaW5lZCBpbiB0aGUgb3duaW5nIHBhY2thZ2UuXG4gICAqXG4gICAqIGUuZy4gY29uc2lkZXIgdGhlIG93bmluZyBwYWNrYWdlIGlzIGBwYWNrYWdlcy9jb3JlYCBhbmQgdGhlIGlucHV0IGZpbGVcbiAgICogaXMgYHBhY2thZ2VzL2NvcmUvdGVzdGluZy9pbmRleC5kLnRzYC4gVGhpcyBmdW5jdGlvbiB3b3VsZCByZXR1cm4gdGhlXG4gICAqIHJlbGF0aXZlIHBhdGggYXMgZm9sbG93ZWQ6IGB0ZXN0aW5nL2luZGV4LmQudHNgLlxuICAgKi9cbiAgZnVuY3Rpb24gZ2V0T3duaW5nUGFja2FnZVJlbGF0aXZlUGF0aChmaWxlOiBCYXplbEZpbGVJbmZvKTogc3RyaW5nIHtcbiAgICByZXR1cm4gcGF0aC5yZWxhdGl2ZShvd25pbmdQYWNrYWdlTmFtZSwgZmlsZS5zaG9ydFBhdGgpO1xuICB9XG5cbiAgLyoqIEdldHMgdGhlIG91dHB1dC1yZWxhdGl2ZSBwYXRoIHdoZXJlIHRoZSB0eXBpbmcgZmlsZSBpcyBiZWluZyB3cml0dGVuIHRvLiAqL1xuICBmdW5jdGlvbiBnZXRUeXBpbmdPdXRwdXRSZWxhdGl2ZVBhdGgoZmlsZTogQmF6ZWxGaWxlSW5mbykge1xuICAgIC8vIFR5cGUgZGVmaW5pdGlvbnMgYXJlIGludGVuZGVkIHRvIGJlIGNvcGllZCBpbnRvIHRoZSBwYWNrYWdlIG91dHB1dCB3aGlsZSBwcmVzZXJ2aW5nIHRoZVxuICAgIC8vIHN1Yi1wYXRoIGZyb20gdGhlIG93bmluZyBwYWNrYWdlLiBlLmcuIGEgZmlsZSBsaWtlIGBwYWNrYWdlcy9hbmltYXRpb25zL2Jyb3dzZXIvX19pbmRleC5kLnRzYFxuICAgIC8vIHdpbGwgZW5kIHVwIGJlaW5nIHdyaXR0ZW4gdG8gYDxwa2ctb3V0Pi9icm93c2VyL2luZGV4LmQudHNgLiBOb3RlIHRoYXQgdHlwZXMgYXJlIGJ1bmRsZWRcbiAgICAvLyBhcyBhIHNlcGFyYXRlIGFjdGlvbiBpbiB0aGUgYG5nX3BhY2thZ2VgIFN0YXJsYXJrIHJ1bGUgYW5kIHByZWZpeGVkIHdpdGggYF9fYCB0byBhdm9pZFxuICAgIC8vIGNvbmZsaWN0cyB3aXRoIHNvdXJjZSBgaW5kZXguZC50c2AgZmlsZXMuIFdlIHJlbW92ZSB0aGlzIHByZWZpeCBoZXJlLlxuICAgIHJldHVybiBnZXRPd25pbmdQYWNrYWdlUmVsYXRpdmVQYXRoKGZpbGUpLnJlcGxhY2UoL19faW5kZXhcXC5kXFwudHMkLywgJ2luZGV4LmQudHMnKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXRzIHRoZSBlbnRyeS1wb2ludCBzdWItcGF0aCBmcm9tIHRoZSBwYWNrYWdlIHJvb3QuIGUuZy4gaWYgdGhlIHBhY2thZ2UgbmFtZVxuICAgKiBpcyBgQGFuZ3VsYXIvY2RrYCwgdGhlbiBmb3IgYEBhbmd1bGFyL2Nkay9hMTF5YCBqdXN0IGBhMTF5YCB3b3VsZCBiZSByZXR1cm5lZC5cbiAgICovXG4gIGZ1bmN0aW9uIGdldEVudHJ5UG9pbnRTdWJwYXRoKG1vZHVsZU5hbWU6IHN0cmluZyk6IHN0cmluZyB7XG4gICAgcmV0dXJuIG1vZHVsZU5hbWUuc2xpY2UoYCR7bWV0YWRhdGEubnBtUGFja2FnZU5hbWV9L2AubGVuZ3RoKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXRzIHdoZXRoZXIgdGhlIGdpdmVuIG1vZHVsZSBuYW1lIHJlc29sdmVzIHRvIGEgc2Vjb25kYXJ5IGVudHJ5LXBvaW50LlxuICAgKiBlLmcuIGlmIHRoZSBwYWNrYWdlIG5hbWUgaXMgYEBhbmd1bGFyL2Nka2AsIHRoZW4gZm9yIGBAYW5ndWxhci9jZGsvYTExeWBcbiAgICogdGhpcyB3b3VsZCByZXR1cm4gYHRydWVgLlxuICAgKi9cbiAgZnVuY3Rpb24gaXNTZWNvbmRhcnlFbnRyeVBvaW50KG1vZHVsZU5hbWU6IHN0cmluZyk6IGJvb2xlYW4ge1xuICAgIHJldHVybiBnZXRFbnRyeVBvaW50U3VicGF0aChtb2R1bGVOYW1lKSAhPT0gJyc7XG4gIH1cblxuICBjb25zdCBjcm9zc0VudHJ5UG9pbnRGYWlsdXJlcyA9IGVzbTIwMjIuZmxhdE1hcCgoZmlsZSkgPT5cbiAgICBhbmFseXplRmlsZUFuZEVuc3VyZU5vQ3Jvc3NJbXBvcnRzKGZpbGUsIG1ldGFkYXRhKSxcbiAgKTtcblxuICBpZiAoY3Jvc3NFbnRyeVBvaW50RmFpbHVyZXMubGVuZ3RoKSB7XG4gICAgY29uc29sZS5lcnJvcihjcm9zc0VudHJ5UG9pbnRGYWlsdXJlcyk7XG4gICAgcHJvY2Vzcy5leGl0KDEpO1xuICB9XG5cbiAgY29uc3QgZmVzbUZpbGVzID0gZ2xvYlN5bmMoJyoqLyonLCB7Y3dkOiBtZXRhZGF0YS5idW5kbGVzT3V0LnBhdGh9KTtcbiAgLy8gQ29weSBhbGwgRkVTTSBmaWxlcyAoYW5kIHRoZWlyIHBvdGVudGlhbCBzaGFyZWQgY2h1bmtzKSBpbnRvIHRoZSBwYWNrYWdlIG91dHB1dC5cbiAgZmVzbUZpbGVzLmZvckVhY2goKGYpID0+IGNvcHlGaWxlKHBhdGguam9pbihtZXRhZGF0YS5idW5kbGVzT3V0LnBhdGgsIGYpLCBmKSk7XG5cbiAgLy8gQ29weSBhbGwgdHlwZSBkZWZpbml0aW9ucyBpbnRvIHRoZSBwYWNrYWdlLCBwcmVzZXJ2aW5nIHRoZSBzdWItcGF0aCBmcm9tIHRoZVxuICAvLyBvd25pbmcgcGFja2FnZS4gZS5nLiBhIGZpbGUgbGlrZSBgcGFja2FnZXMvYW5pbWF0aW9ucy9icm93c2VyL19faW5kZXguZC50c2Agd2lsbFxuICAvLyBlbmQgdXAgaW4gYGJyb3dzZXIvaW5kZXguZC50c2BcbiAgdHlwZURlZmluaXRpb25zLmZvckVhY2goKGYpID0+IGNvcHlGaWxlKGYucGF0aCwgZ2V0VHlwaW5nT3V0cHV0UmVsYXRpdmVQYXRoKGYpKSk7XG5cbiAgZm9yIChjb25zdCBmaWxlIG9mIHN0YXRpY0ZpbGVzKSB7XG4gICAgLy8gV2UgY29weSBhbGwgZmlsZXMgaW50byB0aGUgcGFja2FnZSBvdXRwdXQgd2hpbGUgcHJlc2VydmluZyB0aGUgc3ViLXBhdGggZnJvbVxuICAgIC8vIHRoZSBvd25pbmcgcGFja2FnZS4gZS5nLiBgcGFja2FnZXMvY29yZS9wYWNrYWdlLmpzb25gIGVuZHMgdXAgYDxwa2ctb3V0Pi9wYWNrYWdlLmpzb25gLlxuICAgIGNvbnN0IG91dHB1dFJlbGF0aXZlUGF0aCA9IGdldE93bmluZ1BhY2thZ2VSZWxhdGl2ZVBhdGgoZmlsZSk7XG4gICAgbGV0IGNvbnRlbnQgPSBmcy5yZWFkRmlsZVN5bmMoZmlsZS5wYXRoLCAndXRmOCcpO1xuXG4gICAgLy8gQ2hlY2sgYW5kIG1vZGlmeSBwYWNrYWdlLmpzb24gZmlsZXMgYXMgbmVjZXNzYXJ5IGZvciBwdWJsaXNoaW5nXG4gICAgaWYgKHBhdGguYmFzZW5hbWUoZmlsZS5wYXRoKSA9PT0gJ3BhY2thZ2UuanNvbicpIHtcbiAgICAgIGNvbnN0IGlzUHJpbWFyeVBhY2thZ2VKc29uID0gb3V0cHV0UmVsYXRpdmVQYXRoID09PSAncGFja2FnZS5qc29uJztcbiAgICAgIGNvbnN0IHBhY2thZ2VKc29uID0gSlNPTi5wYXJzZShjb250ZW50KSBhcyBQYWNrYWdlSnNvbjtcbiAgICAgIGNvbnN0IHBhY2thZ2VOYW1lID0gcGFja2FnZUpzb25bJ25hbWUnXTtcblxuICAgICAgLy8gUHJldmVudCBub24tcHJpbWFyeSBgcGFja2FnZS5qc29uYCBmaWxlcyB3aGljaCB3b3VsZCB0aHJvdy1vZmYgcmVzb2x1dGlvbi5cbiAgICAgIC8vIFJlc29sdXRpb24gaW4gdGhlIHBhY2thZ2Ugc2hvdWxkIG9ubHkgYmUgYmFzZWQgb24gdGhlIHRvcC1sZXZlbCBgcGFja2FnZS5qc29uYC5cbiAgICAgIGlmICghaXNQcmltYXJ5UGFja2FnZUpzb24pIHtcbiAgICAgICAgdGhyb3cgRXJyb3IoXG4gICAgICAgICAgYEZvdW5kIGEgbmVzdGVkIFwicGFja2FnZS5qc29uXCIgZmlsZSBpbiB0aGUgcGFja2FnZSBvdXRwdXQ6ICR7ZmlsZS5zaG9ydFBhdGh9LlxcbmAgK1xuICAgICAgICAgICAgYEFsbCBpbmZvcm1hdGlvbiBvZiB0aGUgcGFja2FnZSBzaG91bGQgcmVzaWRlIGluIHRoZSBwcmltYXJ5IHBhY2thZ2UgZmlsZS5gLFxuICAgICAgICApO1xuICAgICAgfVxuXG4gICAgICAvLyBDaGVjayBpZiB0aGUgYG5hbWVgIGZpZWxkIG9mIHRoZSBgcGFja2FnZS5qc29uYCBmaWxlcyBhcmUgbWF0Y2hpbmcgd2l0aFxuICAgICAgLy8gbmFtZSBvZiB0aGUgTlBNIHBhY2thZ2UuIFRoaXMgaXMgYW4gYWRkaXRpb25hbCBzYWZldHkgY2hlY2suXG4gICAgICBpZiAocGFja2FnZU5hbWUgIT09IG1ldGFkYXRhLm5wbVBhY2thZ2VOYW1lKSB7XG4gICAgICAgIHRocm93IEVycm9yKFxuICAgICAgICAgIGBQcmltYXJ5IFwicGFja2FnZS5qc29uXCIgaGFzIG1pc21hdGNoaW5nIHBhY2thZ2UgbmFtZS4gRXhwZWN0ZWQgdGhlIGAgK1xuICAgICAgICAgICAgYHBhY2thZ2UgdG8gYmUgbmFtZWQgXCIke21ldGFkYXRhLm5wbVBhY2thZ2VOYW1lfVwiLCBidXQgaXMgc2V0IHRvOiAke3BhY2thZ2VOYW1lfS5gLFxuICAgICAgICApO1xuICAgICAgfVxuXG4gICAgICBsZXQgbmV3UGFja2FnZUpzb24gPSBpbnNlcnRGb3JtYXRGaWVsZHNJbnRvUGFja2FnZUpzb24oXG4gICAgICAgIG91dHB1dFJlbGF0aXZlUGF0aCxcbiAgICAgICAgcGFja2FnZUpzb24sXG4gICAgICAgIGZhbHNlLFxuICAgICAgKTtcblxuICAgICAgbmV3UGFja2FnZUpzb24gPSB1cGRhdGVQcmltYXJ5UGFja2FnZUpzb24obmV3UGFja2FnZUpzb24pO1xuXG4gICAgICAvLyBVcGRhdGUgdGhlIGNvbnRlbnQgd2l0aCB0aGUgbmV3IGBwYWNrYWdlLmpzb25gIGZpbGUgY29udGVudC5cbiAgICAgIGNvbnRlbnQgPSBKU09OLnN0cmluZ2lmeShuZXdQYWNrYWdlSnNvbiwgbnVsbCwgMik7XG4gICAgfVxuXG4gICAgd3JpdGVGaWxlKG91dHB1dFJlbGF0aXZlUGF0aCwgY29udGVudCk7XG4gIH1cblxuICAvKipcbiAgICogSW5zZXJ0cyBvciBlZGl0cyBwcm9wZXJ0aWVzIGludG8gdGhlIHBhY2thZ2UuanNvbiBmaWxlKHMpIGluIHRoZSBwYWNrYWdlIHNvIHRoYXRcbiAgICogdGhleSBwb2ludCB0byBhbGwgdGhlIHJpZ2h0IGdlbmVyYXRlZCBhcnRpZmFjdHMuXG4gICAqXG4gICAqIEBwYXJhbSBwYWNrYWdlSnNvbk91dFJlbGF0aXZlUGF0aCBQYXRoIHdoZXJlIHRoZSBgcGFja2FnZS5qc29uYCBpcyBzdG9yZWQgaW5cbiAgICogICB0aGUgcGFja2FnZSBvdXRwdXQuXG4gICAqIEBwYXJhbSBwYXJzZWRQYWNrYWdlIFBhcnNlZCBwYWNrYWdlLmpzb24gY29udGVudFxuICAgKiBAcGFyYW0gaXNHZW5lcmF0ZWRQYWNrYWdlSnNvbiBXaGV0aGVyIHRoZSBwYXNzZWQgcGFja2FnZS5qc29uIGhhcyBiZWVuIGdlbmVyYXRlZC5cbiAgICovXG4gIGZ1bmN0aW9uIGluc2VydEZvcm1hdEZpZWxkc0ludG9QYWNrYWdlSnNvbihcbiAgICBwYWNrYWdlSnNvbk91dFJlbGF0aXZlUGF0aDogc3RyaW5nLFxuICAgIHBhcnNlZFBhY2thZ2U6IFJlYWRvbmx5PFBhY2thZ2VKc29uPixcbiAgICBpc0dlbmVyYXRlZFBhY2thZ2VKc29uOiBib29sZWFuLFxuICApOiBQYWNrYWdlSnNvbiB7XG4gICAgY29uc3QgcGFja2FnZUpzb246IFBhY2thZ2VKc29uID0gey4uLnBhcnNlZFBhY2thZ2V9O1xuICAgIGNvbnN0IHBhY2thZ2VOYW1lID0gcGFja2FnZUpzb25bJ25hbWUnXTtcbiAgICBjb25zdCBlbnRyeVBvaW50SW5mbyA9IG1ldGFkYXRhLmVudHJ5UG9pbnRzW3BhY2thZ2VOYW1lXTtcbiAgICBjb25zdCBwYWNrYWdlSnNvbkNvbnRhaW5pbmdEaXIgPSBwYXRoLmRpcm5hbWUocGFja2FnZUpzb25PdXRSZWxhdGl2ZVBhdGgpO1xuXG4gICAgLy8gSWYgYSBwYWNrYWdlIGpzb24gZmlsZSBoYXMgYmVlbiBkaXNjb3ZlcmVkIHRoYXQgZG9lcyBub3QgbWF0Y2ggYW55XG4gICAgLy8gZW50cnktcG9pbnQgaW4gdGhlIG1ldGFkYXRhLCB3ZSByZXBvcnQgYSB3YXJuaW5nIGFzIG1vc3QgbGlrZWx5IHRoZSB0YXJnZXRcbiAgICAvLyBpcyBjb25maWd1cmVkIGluY29ycmVjdGx5IChlLmcuIG1pc3NpbmcgYG1vZHVsZV9uYW1lYCBhdHRyaWJ1dGUpLlxuICAgIGlmICghZW50cnlQb2ludEluZm8pIHtcbiAgICAgIC8vIElkZWFsbHkgd2Ugc2hvdWxkIHRocm93IGhlcmUsIGFzIHdlIGdvdCBhbiBlbnRyeSBwb2ludCB0aGF0IGRvZXNuJ3RcbiAgICAgIC8vIGhhdmUgZmxhdCBtb2R1bGUgbWV0YWRhdGEgLyBidW5kbGUgaW5kZXgsIHNvIGl0IG1heSBoYXZlIGJlZW4gYW5cbiAgICAgIC8vIG5nX21vZHVsZSB0aGF0J3MgbWlzc2luZyBhIG1vZHVsZV9uYW1lIGF0dHJpYnV0ZS5cbiAgICAgIC8vIEhvd2V2ZXIsIEBhbmd1bGFyL2NvbXBpbGVyIGNhbid0IGJlIGFuIG5nX21vZHVsZSwgYXMgaXQncyB0aGUgaW50ZXJuYWxzXG4gICAgICAvLyBvZiB0aGUgbmdjIGNvbXBpbGVyLCB5ZXQgd2Ugd2FudCB0byBidWlsZCBhbiBuZ19wYWNrYWdlIGZvciBpdC5cbiAgICAgIC8vIFNvIGlnbm9yZSBwYWNrYWdlLmpzb24gZmlsZXMgd2hlbiB3ZSBhcmUgbWlzc2luZyBkYXRhLlxuICAgICAgY29uc29sZS5lcnJvcignV0FSTklORzogbm8gbW9kdWxlIG1ldGFkYXRhIGZvciBwYWNrYWdlJywgcGFja2FnZU5hbWUpO1xuICAgICAgY29uc29sZS5lcnJvcignICAgTm90IHVwZGF0aW5nIHRoZSBwYWNrYWdlLmpzb24gZmlsZSB0byBwb2ludCB0byBpdCcpO1xuICAgICAgY29uc29sZS5lcnJvcihcbiAgICAgICAgJyAgIFRoZSBuZ19tb2R1bGUgZm9yIHRoaXMgcGFja2FnZSBpcyBwb3NzaWJseSBtaXNzaW5nIHRoZSBtb2R1bGVfbmFtZSBhdHRyaWJ1dGUgJyxcbiAgICAgICk7XG4gICAgICByZXR1cm4gcGFja2FnZUpzb247XG4gICAgfVxuXG4gICAgLy8gSWYgd2UgZ3Vlc3NlZCB0aGUgaW5kZXggcGF0aHMgZm9yIGEgbW9kdWxlLCBhbmQgaXQgY29udGFpbnMgYW4gZXhwbGljaXQgYHBhY2thZ2UuanNvbmBcbiAgICAvLyBmaWxlIHRoYXQgYWxyZWFkeSBzZXRzIGZvcm1hdCBwcm9wZXJ0aWVzLCB3ZSBza2lwIGF1dG9tYXRpYyBpbnNlcnRpb24gb2YgZm9ybWF0XG4gICAgLy8gcHJvcGVydGllcyBidXQgcmVwb3J0IGEgd2FybmluZyBpbiBjYXNlIHByb3BlcnRpZXMgaGF2ZSBiZWVuIHNldCBieSBhY2NpZGVudC5cbiAgICBpZiAoXG4gICAgICBlbnRyeVBvaW50SW5mby5ndWVzc2VkUGF0aHMgJiZcbiAgICAgICFpc0dlbmVyYXRlZFBhY2thZ2VKc29uICYmXG4gICAgICBoYXNFeHBsaWNpdEZvcm1hdFByb3BlcnRpZXMocGFja2FnZUpzb24pXG4gICAgKSB7XG4gICAgICBjb25zb2xlLmVycm9yKCdXQVJOSU5HOiBgcGFja2FnZS5qc29uYCBleHBsaWNpdGx5IHNldHMgZm9ybWF0IHByb3BlcnRpZXMgKGxpa2UgYG1haW5gKS4nKTtcbiAgICAgIGNvbnNvbGUuZXJyb3IoXG4gICAgICAgICcgICAgU2tpcHBpbmcgYXV0b21hdGljIGluc2VydGlvbiBvZiBmb3JtYXQgcHJvcGVydGllcyBhcyBleHBsaWNpdCAnICtcbiAgICAgICAgICAnZm9ybWF0IHByb3BlcnRpZXMgYXJlIHNldC4nLFxuICAgICAgKTtcbiAgICAgIGNvbnNvbGUuZXJyb3IoJyAgICBJZ25vcmUgdGhpcyB3YXJuaW5nIGlmIGV4cGxpY2l0IHByb3BlcnRpZXMgYXJlIHNldCBpbnRlbnRpb25hbGx5LicpO1xuICAgICAgcmV0dXJuIHBhY2thZ2VKc29uO1xuICAgIH1cblxuICAgIGNvbnN0IGZlc20yMDIyUmVsYXRpdmVPdXRQYXRoID0gZW50cnlQb2ludEluZm8uZmVzbTIwMjJSZWxhdGl2ZVBhdGg7XG4gICAgY29uc3QgdHlwaW5nc1JlbGF0aXZlT3V0UGF0aCA9IGdldFR5cGluZ091dHB1dFJlbGF0aXZlUGF0aChlbnRyeVBvaW50SW5mby50eXBpbmdzKTtcblxuICAgIHBhY2thZ2VKc29uLm1vZHVsZSA9IG5vcm1hbGl6ZVBhdGgoXG4gICAgICBwYXRoLnJlbGF0aXZlKHBhY2thZ2VKc29uQ29udGFpbmluZ0RpciwgZmVzbTIwMjJSZWxhdGl2ZU91dFBhdGgpLFxuICAgICk7XG4gICAgcGFja2FnZUpzb24udHlwaW5ncyA9IG5vcm1hbGl6ZVBhdGgoXG4gICAgICBwYXRoLnJlbGF0aXZlKHBhY2thZ2VKc29uQ29udGFpbmluZ0RpciwgdHlwaW5nc1JlbGF0aXZlT3V0UGF0aCksXG4gICAgKTtcblxuICAgIHJldHVybiBwYWNrYWdlSnNvbjtcbiAgfVxuXG4gIC8qKlxuICAgKiBVcGRhdGVzIHRoZSBwcmltYXJ5IGBwYWNrYWdlLmpzb25gIGZpbGUgb2YgdGhlIE5QTSBwYWNrYWdlIHRvIHNwZWNpZnlcbiAgICogdGhlIG1vZHVsZSBjb25kaXRpb25hbCBleHBvcnRzIGFuZCB0aGUgRVNNIG1vZHVsZSB0eXBlLlxuICAgKi9cbiAgZnVuY3Rpb24gdXBkYXRlUHJpbWFyeVBhY2thZ2VKc29uKHBhY2thZ2VKc29uOiBSZWFkb25seTxQYWNrYWdlSnNvbj4pOiBQYWNrYWdlSnNvbiB7XG4gICAgaWYgKHBhY2thZ2VKc29uLnR5cGUgIT09IHVuZGVmaW5lZCAmJiBwYWNrYWdlSnNvbi50eXBlICE9PSAnbW9kdWxlJykge1xuICAgICAgdGhyb3cgRXJyb3IoXG4gICAgICAgICdUaGUgcHJpbWFyeSBcInBhY2thZ2UuanNvblwiIGZpbGUgb2YgdGhlIHBhY2thZ2Ugc2V0cyB0aGUgXCJ0eXBlXCIgZmllbGQgJyArXG4gICAgICAgICAgJ3RoYXQgaXMgY29udHJvbGxlZCBieSB0aGUgcGFja2FnZXIuIFBsZWFzZSB1bnNldCBpdCBvciBzZXQgYHR5cGVgIHRvIGBtb2R1bGVgLicsXG4gICAgICApO1xuICAgIH1cblxuICAgIGNvbnN0IG5ld1BhY2thZ2VKc29uOiBQYWNrYWdlSnNvbiA9IHsuLi5wYWNrYWdlSnNvbn07XG5cbiAgICBuZXdQYWNrYWdlSnNvbi50eXBlID0gJ21vZHVsZSc7XG5cbiAgICAvLyBUaGUgYHBhY2thZ2UuanNvbmAgZmlsZSBpcyBtYWRlIHB1YmxpY2x5IGFjY2Vzc2libGUgZm9yIHRvb2xzIHRoYXRcbiAgICAvLyBtaWdodCB3YW50IHRvIHF1ZXJ5IGluZm9ybWF0aW9uIGZyb20gdGhlIEFuZ3VsYXIgTlBNIHBhY2thZ2UuXG4gICAgaW5zZXJ0RXhwb3J0TWFwcGluZ09yRXJyb3IobmV3UGFja2FnZUpzb24sICcuL3BhY2thZ2UuanNvbicsIHtkZWZhdWx0OiAnLi9wYWNrYWdlLmpzb24nfSk7XG5cbiAgICAvLyBDYXB0dXJlIGFsbCBlbnRyeS1wb2ludHMgaW4gdGhlIGBleHBvcnRzYCBmaWVsZCB1c2luZyB0aGUgc3VicGF0aCBleHBvcnQgZGVjbGFyYXRpb25zOlxuICAgIC8vIGh0dHBzOi8vbm9kZWpzLm9yZy9hcGkvcGFja2FnZXMuaHRtbCNwYWNrYWdlc19zdWJwYXRoX2V4cG9ydHMuXG4gICAgZm9yIChjb25zdCBbbW9kdWxlTmFtZSwgZW50cnlQb2ludF0gb2YgT2JqZWN0LmVudHJpZXMobWV0YWRhdGEuZW50cnlQb2ludHMpKSB7XG4gICAgICBjb25zdCBzdWJwYXRoID0gaXNTZWNvbmRhcnlFbnRyeVBvaW50KG1vZHVsZU5hbWUpXG4gICAgICAgID8gYC4vJHtnZXRFbnRyeVBvaW50U3VicGF0aChtb2R1bGVOYW1lKX1gXG4gICAgICAgIDogJy4nO1xuICAgICAgY29uc3QgZmVzbTIwMjJPdXRSZWxhdGl2ZVBhdGggPSBlbnRyeVBvaW50LmZlc20yMDIyUmVsYXRpdmVQYXRoO1xuICAgICAgY29uc3QgdHlwZXNPdXRSZWxhdGl2ZVBhdGggPSBnZXRUeXBpbmdPdXRwdXRSZWxhdGl2ZVBhdGgoZW50cnlQb2ludC50eXBpbmdzKTtcblxuICAgICAgLy8gSW5zZXJ0IHRoZSBleHBvcnQgbWFwcGluZyBmb3IgdGhlIGVudHJ5LXBvaW50LiBXZSBzZXQgYGRlZmF1bHRgIHRvIHRoZSBGRVNNIDIwMjJcbiAgICAgIC8vIG91dHB1dCwgYW5kIGFsc28gc2V0IHRoZSBgdHlwZXNgIGNvbmRpdGlvbiB3aGljaCB3aWxsIGJlIHJlc3BlY3RlZCBieSBUUyA0LjUuXG4gICAgICAvLyBodHRwczovL2dpdGh1Yi5jb20vbWljcm9zb2Z0L1R5cGVTY3JpcHQvcHVsbC80NTg4NC5cbiAgICAgIGluc2VydEV4cG9ydE1hcHBpbmdPckVycm9yKG5ld1BhY2thZ2VKc29uLCBzdWJwYXRoLCB7XG4gICAgICAgIHR5cGVzOiBub3JtYWxpemVQYXRoKHR5cGVzT3V0UmVsYXRpdmVQYXRoKSxcbiAgICAgICAgLy8gTm90ZTogVGhlIGRlZmF1bHQgY29uZGl0aW9ucyBuZWVkcyB0byBiZSB0aGUgbGFzdCBvbmUuXG4gICAgICAgIGRlZmF1bHQ6IG5vcm1hbGl6ZVBhdGgoZmVzbTIwMjJPdXRSZWxhdGl2ZVBhdGgpLFxuICAgICAgfSk7XG4gICAgfVxuXG4gICAgY2hlY2tQYWNrYWdlSnNvblNpZGVFZmZlY3RzKHBhY2thZ2VKc29uKTtcblxuICAgIHJldHVybiBuZXdQYWNrYWdlSnNvbjtcbiAgfVxuXG4gIGZ1bmN0aW9uIGNoZWNrUGFja2FnZUpzb25TaWRlRWZmZWN0cyhwYWNrYWdlSnNvbjogUGFja2FnZUpzb24pOiB2b2lkIHtcbiAgICAvLyBDb252ZW5pZW5jZSBpZiB0aGVyZSBhcmUgbm8gc2lkZSBlZmZlY3RzLCBhbmQgaXQncyBleHBsaWNpdGx5IG1hcmtlZC5cbiAgICAvLyBUaGlzIGlzIG9rYXkgYW5kIHdlIGRvbid0IGFzayB0aGUgZGV2ZWxvcGVyIHRvIGRyb3AgdGhlIGV4cGxpY2l0IGZpZWxkLlxuICAgIGlmIChwYWNrYWdlSnNvbi5zaWRlRWZmZWN0cyA9PT0gZmFsc2UgJiYgc2lkZUVmZmVjdEVudHJ5UG9pbnRzLmxlbmd0aCA9PT0gMCkge1xuICAgICAgcmV0dXJuO1xuICAgIH1cblxuICAgIGlmIChwYWNrYWdlSnNvbi5zaWRlRWZmZWN0cyA9PT0gdHJ1ZSkge1xuICAgICAgdGhyb3cgRXJyb3IoXG4gICAgICAgICdVbmV4cGVjdGVkIGBzaWRlRWZmZWN0c2AgZmllbGQgaW4gYHBhY2thZ2UuanNvbmAuICcgK1xuICAgICAgICAgICdTaWRlIGVmZmVjdHMgc2hvdWxkIGJlIGZpbmUtZ3JhaW5lZCBhbmQgbWFya2VkIHZpYSB0aGUgQmF6ZWwgYHNpZGVfZWZmZWN0X2VudHJ5X3BvaW50c2Agb3B0aW9uLicsXG4gICAgICApO1xuICAgIH1cblxuICAgIGNvbnN0IHNpZGVFZmZlY3RzID0gcGFja2FnZUpzb24uc2lkZUVmZmVjdHMgYXMgdW5kZWZpbmVkIHwgZmFsc2UgfCBzdHJpbmdbXTtcbiAgICBjb25zdCBuZWVkZWRTaWRlRWZmZWN0cyA9IHNpZGVFZmZlY3RFbnRyeVBvaW50cy5tYXAoXG4gICAgICAoZW50cnlQb2ludE1vZHVsZSkgPT4gYC4vJHttZXRhZGF0YS5lbnRyeVBvaW50c1tlbnRyeVBvaW50TW9kdWxlXS5mZXNtMjAyMlJlbGF0aXZlUGF0aH1gLFxuICAgICk7XG4gICAgY29uc3QgbWlzc2luZ1NpZGVFZmZlY3RzID0gbmVlZGVkU2lkZUVmZmVjdHMuZmlsdGVyKFxuICAgICAgKHApID0+XG4gICAgICAgIC8vIEl0J3MgbWlzc2luZywgaWYgdGhlIHdob2xlIHBhY2thZ2UgaXMgbWFya2VkIGFzIGhhdmluZyBubyBzaWRlIGVmZmVjdHMuXG4gICAgICAgIHNpZGVFZmZlY3RzID09PSBmYWxzZSB8fFxuICAgICAgICAvLyBBbHRlcm5hdGl2ZWx5LCBpdCdzIG1pc3NpbmcgaWYgdGhlIGV4cGxpY2l0IGxpc3QgZG9lc24ndCBjb250YWluIHRoZSBwYXR0ZXJuLlxuICAgICAgICAhKHNpZGVFZmZlY3RzID8/IFtdKS5pbmNsdWRlcyhwKSxcbiAgICApO1xuXG4gICAgaWYgKG1pc3NpbmdTaWRlRWZmZWN0cy5sZW5ndGggPiAwKSB7XG4gICAgICB0aHJvdyBFcnJvcihcbiAgICAgICAgJ01pc3Npbmcgc2lkZSBlZmZlY3RzIGluIGBwYWNrYWdlLmpzb25gIGBzaWRlRWZmZWN0c2AgZmllbGQuICcgK1xuICAgICAgICAgICdQbGVhc2UgYWRkIHRoZSBmb2xsb3dpbmcgc2lkZSBlZmZlY3QgZmlsZSBwYXR0ZXJuczpcXG4nICtcbiAgICAgICAgICBtaXNzaW5nU2lkZUVmZmVjdHMuam9pbignXFxuIC0gJyksXG4gICAgICApO1xuICAgIH1cblxuICAgIC8vIEZpbmQgcG90ZW50aWFsIHNpZGUtZWZmZWN0cyB0aGF0IHJlZmVyIHRvIG91ciBGRVNNIGJ1bmRsZXMsIGJ1dCBhcmVuJ3QgcGFydFxuICAgIC8vIG9mIHRoZSBgbmdfcGFja2FnZWAga25vd24gZW50cnkgcG9pbnRzLlxuICAgIGNvbnN0IHVuZXhwZWN0ZWRFeHRyYSA9XG4gICAgICBzaWRlRWZmZWN0cyAhPT0gZmFsc2VcbiAgICAgICAgPyAoc2lkZUVmZmVjdHMgPz8gW10pLmZpbHRlcihcbiAgICAgICAgICAgIChwKSA9PiBwLmluY2x1ZGVzKCdmZXNtMjAyMicpICYmICFuZWVkZWRTaWRlRWZmZWN0cy5pbmNsdWRlcyhwKSxcbiAgICAgICAgICApXG4gICAgICAgIDogW107XG4gICAgaWYgKHVuZXhwZWN0ZWRFeHRyYS5sZW5ndGggPiAwKSB7XG4gICAgICB0aHJvdyBFcnJvcihcbiAgICAgICAgJ1VuZXhwZWN0ZWQgc2lkZSBlZmZlY3RzIGluIGBwYWNrYWdlLmpzb25gIGBzaWRlRWZmZWN0c2AgZmllbGQgdGhhdCBpcyBub3Qga25vd24gdG8gYG5nX3BhY2thZ2VgLiAnICtcbiAgICAgICAgICAnUGxlYXNlIGFkZCB0aGUgc2lkZSBlZmZlY3QgZW50cnkgcG9pbnQgdG8gdGhlIEJhemVsIGBzaWRlX2VmZmVjdF9lbnRyeV9wb2ludHNgIG9wdGlvbi4gJyArXG4gICAgICAgICAgJ1VuZXhwZWN0ZWQgcGF0dGVybnM6XFxuJyArXG4gICAgICAgICAgdW5leHBlY3RlZEV4dHJhLmpvaW4oJ1xcbiAtICcpLFxuICAgICAgKTtcbiAgICB9XG4gIH1cblxuICAvKipcbiAgICogSW5zZXJ0cyBhIHN1YnBhdGggZXhwb3J0IG1hcHBpbmcgaW50byB0aGUgc3BlY2lmaWVkIGBwYWNrYWdlLmpzb25gIG9iamVjdC5cbiAgICogQHRocm93cyBBbiBlcnJvciBpZiB0aGUgbWFwcGluZyBpcyBhbHJlYWR5IGRlZmluZWQgYW5kIHdvdWxkIGNvbmZsaWN0LlxuICAgKi9cbiAgZnVuY3Rpb24gaW5zZXJ0RXhwb3J0TWFwcGluZ09yRXJyb3IoXG4gICAgcGFja2FnZUpzb246IFBhY2thZ2VKc29uLFxuICAgIHN1YnBhdGg6IHN0cmluZyxcbiAgICBtYXBwaW5nOiBDb25kaXRpb25hbEV4cG9ydCxcbiAgKSB7XG4gICAgaWYgKHBhY2thZ2VKc29uLmV4cG9ydHMgPT09IHVuZGVmaW5lZCkge1xuICAgICAgcGFja2FnZUpzb24uZXhwb3J0cyA9IHt9O1xuICAgIH1cbiAgICBpZiAocGFja2FnZUpzb24uZXhwb3J0c1tzdWJwYXRoXSA9PT0gdW5kZWZpbmVkKSB7XG4gICAgICBwYWNrYWdlSnNvbi5leHBvcnRzW3N1YnBhdGhdID0ge307XG4gICAgfVxuXG4gICAgY29uc3Qgc3VicGF0aEV4cG9ydCA9IHBhY2thZ2VKc29uLmV4cG9ydHNbc3VicGF0aF07XG5cbiAgICAvLyBHbyB0aHJvdWdoIGFsbCBjb25kaXRpb25zIHRoYXQgc2hvdWxkIGJlIGluc2VydGVkLiBJZiB0aGUgY29uZGl0aW9uIGlzIGFscmVhZHlcbiAgICAvLyBtYW51YWxseSBzZXQgb2YgdGhlIHN1YnBhdGggZXhwb3J0LCB3ZSB0aHJvdyBhbiBlcnJvci4gSW4gZ2VuZXJhbCwgd2UgYWxsb3cgZm9yXG4gICAgLy8gYWRkaXRpb25hbCBjb25kaXRpb25zIHRvIGJlIHNldC4gVGhlc2Ugd2lsbCBhbHdheXMgcHJlY2VkZSB0aGUgZ2VuZXJhdGVkIG9uZXMuXG4gICAgZm9yIChjb25zdCBjb25kaXRpb25OYW1lIG9mIE9iamVjdC5rZXlzKG1hcHBpbmcpIGFzIFtrZXlvZiBDb25kaXRpb25hbEV4cG9ydF0pIHtcbiAgICAgIGlmIChzdWJwYXRoRXhwb3J0W2NvbmRpdGlvbk5hbWVdICE9PSB1bmRlZmluZWQpIHtcbiAgICAgICAgdGhyb3cgRXJyb3IoXG4gICAgICAgICAgYEZvdW5kIGEgY29uZmxpY3RpbmcgZXhwb3J0IGNvbmRpdGlvbiBmb3IgXCIke3N1YnBhdGh9XCIuIFRoZSBcIiR7Y29uZGl0aW9uTmFtZX1cIiBgICtcbiAgICAgICAgICAgIGBjb25kaXRpb24gd291bGQgYmUgb3ZlcnJpZGRlbiBieSB0aGUgcGFja2FnZXIuIFBsZWFzZSB1bnNldCBpdC5gLFxuICAgICAgICApO1xuICAgICAgfVxuXG4gICAgICAvLyAqKk5vdGUqKjogVGhlIG9yZGVyIG9mIHRoZSBjb25kaXRpb25zIGlzIHByZXNlcnZlZCBldmVuIHRob3VnaCB3ZSBhcmUgc2V0dGluZ1xuICAgICAgLy8gdGhlIGNvbmRpdGlvbnMgb25jZSBhdCBhIHRpbWUgKHRoZSBsYXRlc3QgYXNzaWdubWVudCB3aWxsIGJlIGF0IHRoZSBlbmQpLlxuICAgICAgc3VicGF0aEV4cG9ydFtjb25kaXRpb25OYW1lXSA9IG1hcHBpbmdbY29uZGl0aW9uTmFtZV07XG4gICAgfVxuICB9XG5cbiAgLyoqIFdoZXRoZXIgdGhlIHBhY2thZ2UgZXhwbGljaXRseSBzZXRzIGFueSBvZiB0aGUgZm9ybWF0IHByb3BlcnRpZXMgKGxpa2UgYG1haW5gKS4gKi9cbiAgZnVuY3Rpb24gaGFzRXhwbGljaXRGb3JtYXRQcm9wZXJ0aWVzKHBhcnNlZFBhY2thZ2U6IFJlYWRvbmx5PFBhY2thZ2VKc29uPik6IGJvb2xlYW4ge1xuICAgIHJldHVybiBPYmplY3Qua2V5cyhwYXJzZWRQYWNrYWdlKS5zb21lKChmaWVsZE5hbWU6IHN0cmluZykgPT5cbiAgICAgIGtub3duRm9ybWF0UGFja2FnZUpzb25Gb3JtYXRGaWVsZHMuaW5jbHVkZXMoZmllbGROYW1lIGFzIEtub3duUGFja2FnZUpzb25Gb3JtYXRGaWVsZHMpLFxuICAgICk7XG4gIH1cblxuICAvKipcbiAgICogTm9ybWFsaXplcyB0aGUgc3BlY2lmaWVkIHBhdGggYnkgcmVwbGFjaW5nIGJhY2tzbGFzaCBzZXBhcmF0b3JzIHdpdGggUG9zaXhcbiAgICogZm9yd2FyZCBzbGFzaCBzZXBhcmF0b3JzLlxuICAgKi9cbiAgZnVuY3Rpb24gbm9ybWFsaXplUGF0aChwYXRoOiBzdHJpbmcpOiBzdHJpbmcge1xuICAgIGNvbnN0IHJlc3VsdCA9IHBhdGgucmVwbGFjZSgvXFxcXC9nLCAnLycpO1xuICAgIHJldHVybiByZXN1bHQuc3RhcnRzV2l0aCgnLicpID8gcmVzdWx0IDogYC4vJHtyZXN1bHR9YDtcbiAgfVxufVxuIl19