/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */
import * as fs from 'fs';
import * as path from 'path';
import { analyzeFileAndEnsureNoCrossImports } from './cross_entry_points_imports';
/**
 * List of known `package.json` fields which provide information about
 * supported package formats and their associated entry paths.
 */
const knownFormatPackageJsonFormatFields = ['main', 'typings', 'module'];
// Main entry-point.
main(process.argv.slice(2));
function main(args) {
    // This utility expects all of its arguments to be specified in a params file generated by
    // bazel (see https://docs.bazel.build/versions/master/skylark/lib/Args.html#use_param_file).
    const paramFilePath = args[0];
    // Bazel params may be surrounded with quotes
    function unquoteParameter(s) {
        return s.replace(/^'(.*)'$/, '$1');
    }
    // Parameters are specified in the file one per line.
    const params = fs.readFileSync(paramFilePath, 'utf-8').split('\n').map(unquoteParameter);
    const [
    // Output directory for the npm package.
    outputDirExecPath, 
    // The package segment of the ng_package rule's label (e.g. 'package/common').
    owningPackageName, 
    // JSON data capturing metadata of the package being built. See `PackageMetadata`.
    metadataArg, 
    // Path to the package's README.md.
    readmeMd, 
    // Path to the package's LICENSE file.
    licenseFile, 
    // List of rolled-up flat ES2022 modules
    fesm2022Arg, 
    // List of individual ES2022 modules
    esm2022Arg, 
    // List of static files that should be copied into the package.
    staticFilesArg, 
    // List of all type definitions that need to packaged into the ng_package.
    typeDefinitionsArg,] = params;
    const fesm2022 = JSON.parse(fesm2022Arg);
    const esm2022 = JSON.parse(esm2022Arg);
    const typeDefinitions = JSON.parse(typeDefinitionsArg);
    const staticFiles = JSON.parse(staticFilesArg);
    const metadata = JSON.parse(metadataArg);
    if (readmeMd) {
        copyFile(readmeMd, 'README.md');
    }
    if (licenseFile) {
        copyFile(licenseFile, 'LICENSE');
    }
    /**
     * Writes a file with the specified content into the package output.
     * @param outputRelativePath Relative path in the output directory where the
     *   file is written to.
     * @param fileContent Content of the file.
     */
    function writeFile(outputRelativePath, fileContent) {
        const outputPath = path.join(outputDirExecPath, outputRelativePath);
        // Always ensure that the target directory exists.
        fs.mkdirSync(path.dirname(outputPath), { recursive: true });
        fs.writeFileSync(outputPath, fileContent);
    }
    /**
     * Copies a file into the package output to the specified location.
     * @param inputPath File that should be copied.
     * @param outputRelativePath Relative path in the output directory where the
     *   file is written to.
     */
    function copyFile(inputPath, outputRelativePath) {
        const fileContent = fs.readFileSync(inputPath, 'utf8');
        writeFile(outputRelativePath, fileContent);
    }
    /**
     * Gets the relative path for the given file within the owning package. This
     * assumes the file is contained in the owning package.
     *
     * e.g. consider the owning package is `packages/core` and the input file
     * is `packages/core/testing/index.d.ts`. This function would return the
     * relative path as followed: `testing/index.d.ts`.
     */
    function getOwningPackageRelativePath(file) {
        return path.relative(owningPackageName, file.shortPath);
    }
    /** Gets the output-relative path where the given flat ESM file should be written to. */
    function getFlatEsmOutputRelativePath(file) {
        // Flat ESM files should be put into their owning package relative sub-path. e.g. if
        // there is a bundle in `packages/animations/fesm2022/browser/testing.mjs` then we
        // want the bundle to be stored in `fesm2022/browser/testing.mjs`. Same thing applies
        // for the `fesm2022` bundles. The directory name for `fesm` is already declared as
        // part of the Bazel action generating these files. See `ng_package.bzl`.
        return getOwningPackageRelativePath(file);
    }
    /** Gets the output-relative path where the typing file is being written to. */
    function getTypingOutputRelativePath(file) {
        // Type definitions are intended to be copied into the package output while preserving the
        // sub-path from the owning package. e.g. a file like `packages/animations/browser/__index.d.ts`
        // will end up being written to `<pkg-out>/browser/index.d.ts`. Note that types are bundled
        // as a separate action in the `ng_package` Starlark rule and prefixed with `__` to avoid
        // conflicts with source `index.d.ts` files. We remove this prefix here.
        return getOwningPackageRelativePath(file).replace(/__index\.d\.ts$/, 'index.d.ts');
    }
    /**
     * Gets the entry-point sub-path from the package root. e.g. if the package name
     * is `@angular/cdk`, then for `@angular/cdk/a11y` just `a11y` would be returned.
     */
    function getEntryPointSubpath(moduleName) {
        return moduleName.slice(`${metadata.npmPackageName}/`.length);
    }
    /**
     * Gets whether the given module name resolves to a secondary entry-point.
     * e.g. if the package name is `@angular/cdk`, then for `@angular/cdk/a11y`
     * this would return `true`.
     */
    function isSecondaryEntryPoint(moduleName) {
        return getEntryPointSubpath(moduleName) !== '';
    }
    const crossEntryPointFailures = esm2022.flatMap((file) => analyzeFileAndEnsureNoCrossImports(file, metadata));
    if (crossEntryPointFailures.length) {
        console.error(crossEntryPointFailures);
        process.exit(1);
    }
    // Copy all FESM files into the package output.
    fesm2022.forEach((f) => copyFile(f.path, getFlatEsmOutputRelativePath(f)));
    // Copy all type definitions into the package, preserving the sub-path from the
    // owning package. e.g. a file like `packages/animations/browser/__index.d.ts` will
    // end up in `browser/index.d.ts`
    typeDefinitions.forEach((f) => copyFile(f.path, getTypingOutputRelativePath(f)));
    for (const file of staticFiles) {
        // We copy all files into the package output while preserving the sub-path from
        // the owning package. e.g. `packages/core/package.json` ends up `<pkg-out>/package.json`.
        const outputRelativePath = getOwningPackageRelativePath(file);
        let content = fs.readFileSync(file.path, 'utf8');
        // Check and modify package.json files as necessary for publishing
        if (path.basename(file.path) === 'package.json') {
            const isPrimaryPackageJson = outputRelativePath === 'package.json';
            const packageJson = JSON.parse(content);
            const packageName = packageJson['name'];
            // Prevent non-primary `package.json` files which would throw-off resolution.
            // Resolution in the package should only be based on the top-level `package.json`.
            if (!isPrimaryPackageJson) {
                throw Error(`Found a nested "package.json" file in the package output: ${file.shortPath}.\n` +
                    `All information of the package should reside in the primary package file.`);
            }
            // Check if the `name` field of the `package.json` files are matching with
            // name of the NPM package. This is an additional safety check.
            if (packageName !== metadata.npmPackageName) {
                throw Error(`Primary "package.json" has mismatching package name. Expected the ` +
                    `package to be named "${metadata.npmPackageName}", but is set to: ${packageName}.`);
            }
            let newPackageJson = insertFormatFieldsIntoPackageJson(outputRelativePath, packageJson, false);
            newPackageJson = updatePrimaryPackageJson(newPackageJson);
            // Update the content with the new `package.json` file content.
            content = JSON.stringify(newPackageJson, null, 2);
        }
        writeFile(outputRelativePath, content);
    }
    /**
     * Inserts or edits properties into the package.json file(s) in the package so that
     * they point to all the right generated artifacts.
     *
     * @param packageJsonOutRelativePath Path where the `package.json` is stored in
     *   the package output.
     * @param parsedPackage Parsed package.json content
     * @param isGeneratedPackageJson Whether the passed package.json has been generated.
     */
    function insertFormatFieldsIntoPackageJson(packageJsonOutRelativePath, parsedPackage, isGeneratedPackageJson) {
        const packageJson = { ...parsedPackage };
        const packageName = packageJson['name'];
        const entryPointInfo = metadata.entryPoints[packageName];
        const packageJsonContainingDir = path.dirname(packageJsonOutRelativePath);
        // If a package json file has been discovered that does not match any
        // entry-point in the metadata, we report a warning as most likely the target
        // is configured incorrectly (e.g. missing `module_name` attribute).
        if (!entryPointInfo) {
            // Ideally we should throw here, as we got an entry point that doesn't
            // have flat module metadata / bundle index, so it may have been an
            // ng_module that's missing a module_name attribute.
            // However, @angular/compiler can't be an ng_module, as it's the internals
            // of the ngc compiler, yet we want to build an ng_package for it.
            // So ignore package.json files when we are missing data.
            console.error('WARNING: no module metadata for package', packageName);
            console.error('   Not updating the package.json file to point to it');
            console.error('   The ng_module for this package is possibly missing the module_name attribute ');
            return packageJson;
        }
        // If we guessed the index paths for a module, and it contains an explicit `package.json`
        // file that already sets format properties, we skip automatic insertion of format
        // properties but report a warning in case properties have been set by accident.
        if (entryPointInfo.guessedPaths &&
            !isGeneratedPackageJson &&
            hasExplicitFormatProperties(packageJson)) {
            console.error('WARNING: `package.json` explicitly sets format properties (like `main`).');
            console.error('    Skipping automatic insertion of format properties as explicit ' +
                'format properties are set.');
            console.error('    Ignore this warning if explicit properties are set intentionally.');
            return packageJson;
        }
        const fesm2022RelativeOutPath = getFlatEsmOutputRelativePath(entryPointInfo.fesm2022Bundle);
        const typingsRelativeOutPath = getTypingOutputRelativePath(entryPointInfo.typings);
        packageJson.module = normalizePath(path.relative(packageJsonContainingDir, fesm2022RelativeOutPath));
        packageJson.typings = normalizePath(path.relative(packageJsonContainingDir, typingsRelativeOutPath));
        return packageJson;
    }
    /**
     * Updates the primary `package.json` file of the NPM package to specify
     * the module conditional exports and the ESM module type.
     */
    function updatePrimaryPackageJson(packageJson) {
        if (packageJson.type !== undefined && packageJson.type !== 'module') {
            throw Error('The primary "package.json" file of the package sets the "type" field ' +
                'that is controlled by the packager. Please unset it or set `type` to `module`.');
        }
        const newPackageJson = { ...packageJson };
        newPackageJson.type = 'module';
        // The `package.json` file is made publicly accessible for tools that
        // might want to query information from the Angular NPM package.
        insertExportMappingOrError(newPackageJson, './package.json', { default: './package.json' });
        // Capture all entry-points in the `exports` field using the subpath export declarations:
        // https://nodejs.org/api/packages.html#packages_subpath_exports.
        for (const [moduleName, entryPoint] of Object.entries(metadata.entryPoints)) {
            const subpath = isSecondaryEntryPoint(moduleName)
                ? `./${getEntryPointSubpath(moduleName)}`
                : '.';
            const fesm2022OutRelativePath = getFlatEsmOutputRelativePath(entryPoint.fesm2022Bundle);
            const typesOutRelativePath = getTypingOutputRelativePath(entryPoint.typings);
            // Insert the export mapping for the entry-point. We set `default` to the FESM 2022
            // output, and also set the `types` condition which will be respected by TS 4.5.
            // https://github.com/microsoft/TypeScript/pull/45884.
            insertExportMappingOrError(newPackageJson, subpath, {
                types: normalizePath(typesOutRelativePath),
                // Note: The default conditions needs to be the last one.
                default: normalizePath(fesm2022OutRelativePath),
            });
        }
        return newPackageJson;
    }
    /**
     * Inserts a subpath export mapping into the specified `package.json` object.
     * @throws An error if the mapping is already defined and would conflict.
     */
    function insertExportMappingOrError(packageJson, subpath, mapping) {
        if (packageJson.exports === undefined) {
            packageJson.exports = {};
        }
        if (packageJson.exports[subpath] === undefined) {
            packageJson.exports[subpath] = {};
        }
        const subpathExport = packageJson.exports[subpath];
        // Go through all conditions that should be inserted. If the condition is already
        // manually set of the subpath export, we throw an error. In general, we allow for
        // additional conditions to be set. These will always precede the generated ones.
        for (const conditionName of Object.keys(mapping)) {
            if (subpathExport[conditionName] !== undefined) {
                throw Error(`Found a conflicting export condition for "${subpath}". The "${conditionName}" ` +
                    `condition would be overridden by the packager. Please unset it.`);
            }
            // **Note**: The order of the conditions is preserved even though we are setting
            // the conditions once at a time (the latest assignment will be at the end).
            subpathExport[conditionName] = mapping[conditionName];
        }
    }
    /** Whether the package explicitly sets any of the format properties (like `main`). */
    function hasExplicitFormatProperties(parsedPackage) {
        return Object.keys(parsedPackage).some((fieldName) => knownFormatPackageJsonFormatFields.includes(fieldName));
    }
    /**
     * Normalizes the specified path by replacing backslash separators with Posix
     * forward slash separators.
     */
    function normalizePath(path) {
        const result = path.replace(/\\/g, '/');
        return result.startsWith('.') ? result : `./${result}`;
    }
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGFja2FnZXIuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi8uLi8uLi8uLi9wYWNrYWdlcy9iYXplbC9zcmMvbmdfcGFja2FnZS9wYWNrYWdlci50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7O0dBTUc7QUFFSCxPQUFPLEtBQUssRUFBRSxNQUFNLElBQUksQ0FBQztBQUN6QixPQUFPLEtBQUssSUFBSSxNQUFNLE1BQU0sQ0FBQztBQUc3QixPQUFPLEVBQUMsa0NBQWtDLEVBQUMsTUFBTSw4QkFBOEIsQ0FBQztBQUVoRjs7O0dBR0c7QUFDSCxNQUFNLGtDQUFrQyxHQUFHLENBQUMsTUFBTSxFQUFFLFNBQVMsRUFBRSxRQUFRLENBQVUsQ0FBQztBQXVCbEYsb0JBQW9CO0FBQ3BCLElBQUksQ0FBQyxPQUFPLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO0FBRTVCLFNBQVMsSUFBSSxDQUFDLElBQWM7SUFDMUIsMEZBQTBGO0lBQzFGLDZGQUE2RjtJQUM3RixNQUFNLGFBQWEsR0FBRyxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFFOUIsNkNBQTZDO0lBQzdDLFNBQVMsZ0JBQWdCLENBQUMsQ0FBUztRQUNqQyxPQUFPLENBQUMsQ0FBQyxPQUFPLENBQUMsVUFBVSxFQUFFLElBQUksQ0FBQyxDQUFDO0lBQ3JDLENBQUM7SUFFRCxxREFBcUQ7SUFDckQsTUFBTSxNQUFNLEdBQUcsRUFBRSxDQUFDLFlBQVksQ0FBQyxhQUFhLEVBQUUsT0FBTyxDQUFDLENBQUMsS0FBSyxDQUFDLElBQUksQ0FBQyxDQUFDLEdBQUcsQ0FBQyxnQkFBZ0IsQ0FBQyxDQUFDO0lBRXpGLE1BQU07SUFDSix3Q0FBd0M7SUFDeEMsaUJBQWlCO0lBRWpCLDhFQUE4RTtJQUM5RSxpQkFBaUI7SUFFakIsa0ZBQWtGO0lBQ2xGLFdBQVc7SUFFWCxtQ0FBbUM7SUFDbkMsUUFBUTtJQUVSLHNDQUFzQztJQUN0QyxXQUFXO0lBRVgsd0NBQXdDO0lBQ3hDLFdBQVc7SUFFWCxvQ0FBb0M7SUFDcEMsVUFBVTtJQUVWLCtEQUErRDtJQUMvRCxjQUFjO0lBRWQsMEVBQTBFO0lBQzFFLGtCQUFrQixFQUNuQixHQUFHLE1BQU0sQ0FBQztJQUVYLE1BQU0sUUFBUSxHQUFHLElBQUksQ0FBQyxLQUFLLENBQUMsV0FBVyxDQUFvQixDQUFDO0lBQzVELE1BQU0sT0FBTyxHQUFHLElBQUksQ0FBQyxLQUFLLENBQUMsVUFBVSxDQUFvQixDQUFDO0lBQzFELE1BQU0sZUFBZSxHQUFHLElBQUksQ0FBQyxLQUFLLENBQUMsa0JBQWtCLENBQW9CLENBQUM7SUFDMUUsTUFBTSxXQUFXLEdBQUcsSUFBSSxDQUFDLEtBQUssQ0FBQyxjQUFjLENBQW9CLENBQUM7SUFDbEUsTUFBTSxRQUFRLEdBQUcsSUFBSSxDQUFDLEtBQUssQ0FBQyxXQUFXLENBQW9CLENBQUM7SUFFNUQsSUFBSSxRQUFRLEVBQUUsQ0FBQztRQUNiLFFBQVEsQ0FBQyxRQUFRLEVBQUUsV0FBVyxDQUFDLENBQUM7SUFDbEMsQ0FBQztJQUVELElBQUksV0FBVyxFQUFFLENBQUM7UUFDaEIsUUFBUSxDQUFDLFdBQVcsRUFBRSxTQUFTLENBQUMsQ0FBQztJQUNuQyxDQUFDO0lBRUQ7Ozs7O09BS0c7SUFDSCxTQUFTLFNBQVMsQ0FBQyxrQkFBMEIsRUFBRSxXQUE0QjtRQUN6RSxNQUFNLFVBQVUsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLGlCQUFpQixFQUFFLGtCQUFrQixDQUFDLENBQUM7UUFFcEUsa0RBQWtEO1FBQ2xELEVBQUUsQ0FBQyxTQUFTLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBQyxVQUFVLENBQUMsRUFBRSxFQUFDLFNBQVMsRUFBRSxJQUFJLEVBQUMsQ0FBQyxDQUFDO1FBQzFELEVBQUUsQ0FBQyxhQUFhLENBQUMsVUFBVSxFQUFFLFdBQVcsQ0FBQyxDQUFDO0lBQzVDLENBQUM7SUFFRDs7Ozs7T0FLRztJQUNILFNBQVMsUUFBUSxDQUFDLFNBQWlCLEVBQUUsa0JBQTBCO1FBQzdELE1BQU0sV0FBVyxHQUFHLEVBQUUsQ0FBQyxZQUFZLENBQUMsU0FBUyxFQUFFLE1BQU0sQ0FBQyxDQUFDO1FBQ3ZELFNBQVMsQ0FBQyxrQkFBa0IsRUFBRSxXQUFXLENBQUMsQ0FBQztJQUM3QyxDQUFDO0lBRUQ7Ozs7Ozs7T0FPRztJQUNILFNBQVMsNEJBQTRCLENBQUMsSUFBbUI7UUFDdkQsT0FBTyxJQUFJLENBQUMsUUFBUSxDQUFDLGlCQUFpQixFQUFFLElBQUksQ0FBQyxTQUFTLENBQUMsQ0FBQztJQUMxRCxDQUFDO0lBRUQsd0ZBQXdGO0lBQ3hGLFNBQVMsNEJBQTRCLENBQUMsSUFBbUI7UUFDdkQsb0ZBQW9GO1FBQ3BGLGtGQUFrRjtRQUNsRixxRkFBcUY7UUFDckYsbUZBQW1GO1FBQ25GLHlFQUF5RTtRQUN6RSxPQUFPLDRCQUE0QixDQUFDLElBQUksQ0FBQyxDQUFDO0lBQzVDLENBQUM7SUFFRCwrRUFBK0U7SUFDL0UsU0FBUywyQkFBMkIsQ0FBQyxJQUFtQjtRQUN0RCwwRkFBMEY7UUFDMUYsZ0dBQWdHO1FBQ2hHLDJGQUEyRjtRQUMzRix5RkFBeUY7UUFDekYsd0VBQXdFO1FBQ3hFLE9BQU8sNEJBQTRCLENBQUMsSUFBSSxDQUFDLENBQUMsT0FBTyxDQUFDLGlCQUFpQixFQUFFLFlBQVksQ0FBQyxDQUFDO0lBQ3JGLENBQUM7SUFFRDs7O09BR0c7SUFDSCxTQUFTLG9CQUFvQixDQUFDLFVBQWtCO1FBQzlDLE9BQU8sVUFBVSxDQUFDLEtBQUssQ0FBQyxHQUFHLFFBQVEsQ0FBQyxjQUFjLEdBQUcsQ0FBQyxNQUFNLENBQUMsQ0FBQztJQUNoRSxDQUFDO0lBRUQ7Ozs7T0FJRztJQUNILFNBQVMscUJBQXFCLENBQUMsVUFBa0I7UUFDL0MsT0FBTyxvQkFBb0IsQ0FBQyxVQUFVLENBQUMsS0FBSyxFQUFFLENBQUM7SUFDakQsQ0FBQztJQUVELE1BQU0sdUJBQXVCLEdBQUcsT0FBTyxDQUFDLE9BQU8sQ0FBQyxDQUFDLElBQUksRUFBRSxFQUFFLENBQ3ZELGtDQUFrQyxDQUFDLElBQUksRUFBRSxRQUFRLENBQUMsQ0FDbkQsQ0FBQztJQUVGLElBQUksdUJBQXVCLENBQUMsTUFBTSxFQUFFLENBQUM7UUFDbkMsT0FBTyxDQUFDLEtBQUssQ0FBQyx1QkFBdUIsQ0FBQyxDQUFDO1FBQ3ZDLE9BQU8sQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFDbEIsQ0FBQztJQUVELCtDQUErQztJQUMvQyxRQUFRLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQyxFQUFFLEVBQUUsQ0FBQyxRQUFRLENBQUMsQ0FBQyxDQUFDLElBQUksRUFBRSw0QkFBNEIsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFFM0UsK0VBQStFO0lBQy9FLG1GQUFtRjtJQUNuRixpQ0FBaUM7SUFDakMsZUFBZSxDQUFDLE9BQU8sQ0FBQyxDQUFDLENBQUMsRUFBRSxFQUFFLENBQUMsUUFBUSxDQUFDLENBQUMsQ0FBQyxJQUFJLEVBQUUsMkJBQTJCLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO0lBRWpGLEtBQUssTUFBTSxJQUFJLElBQUksV0FBVyxFQUFFLENBQUM7UUFDL0IsK0VBQStFO1FBQy9FLDBGQUEwRjtRQUMxRixNQUFNLGtCQUFrQixHQUFHLDRCQUE0QixDQUFDLElBQUksQ0FBQyxDQUFDO1FBQzlELElBQUksT0FBTyxHQUFHLEVBQUUsQ0FBQyxZQUFZLENBQUMsSUFBSSxDQUFDLElBQUksRUFBRSxNQUFNLENBQUMsQ0FBQztRQUVqRCxrRUFBa0U7UUFDbEUsSUFBSSxJQUFJLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxJQUFJLENBQUMsS0FBSyxjQUFjLEVBQUUsQ0FBQztZQUNoRCxNQUFNLG9CQUFvQixHQUFHLGtCQUFrQixLQUFLLGNBQWMsQ0FBQztZQUNuRSxNQUFNLFdBQVcsR0FBRyxJQUFJLENBQUMsS0FBSyxDQUFDLE9BQU8sQ0FBZ0IsQ0FBQztZQUN2RCxNQUFNLFdBQVcsR0FBRyxXQUFXLENBQUMsTUFBTSxDQUFDLENBQUM7WUFFeEMsNkVBQTZFO1lBQzdFLGtGQUFrRjtZQUNsRixJQUFJLENBQUMsb0JBQW9CLEVBQUUsQ0FBQztnQkFDMUIsTUFBTSxLQUFLLENBQ1QsNkRBQTZELElBQUksQ0FBQyxTQUFTLEtBQUs7b0JBQzlFLDJFQUEyRSxDQUM5RSxDQUFDO1lBQ0osQ0FBQztZQUVELDBFQUEwRTtZQUMxRSwrREFBK0Q7WUFDL0QsSUFBSSxXQUFXLEtBQUssUUFBUSxDQUFDLGNBQWMsRUFBRSxDQUFDO2dCQUM1QyxNQUFNLEtBQUssQ0FDVCxvRUFBb0U7b0JBQ2xFLHdCQUF3QixRQUFRLENBQUMsY0FBYyxxQkFBcUIsV0FBVyxHQUFHLENBQ3JGLENBQUM7WUFDSixDQUFDO1lBRUQsSUFBSSxjQUFjLEdBQUcsaUNBQWlDLENBQ3BELGtCQUFrQixFQUNsQixXQUFXLEVBQ1gsS0FBSyxDQUNOLENBQUM7WUFFRixjQUFjLEdBQUcsd0JBQXdCLENBQUMsY0FBYyxDQUFDLENBQUM7WUFFMUQsK0RBQStEO1lBQy9ELE9BQU8sR0FBRyxJQUFJLENBQUMsU0FBUyxDQUFDLGNBQWMsRUFBRSxJQUFJLEVBQUUsQ0FBQyxDQUFDLENBQUM7UUFDcEQsQ0FBQztRQUVELFNBQVMsQ0FBQyxrQkFBa0IsRUFBRSxPQUFPLENBQUMsQ0FBQztJQUN6QyxDQUFDO0lBRUQ7Ozs7Ozs7O09BUUc7SUFDSCxTQUFTLGlDQUFpQyxDQUN4QywwQkFBa0MsRUFDbEMsYUFBb0MsRUFDcEMsc0JBQStCO1FBRS9CLE1BQU0sV0FBVyxHQUFnQixFQUFDLEdBQUcsYUFBYSxFQUFDLENBQUM7UUFDcEQsTUFBTSxXQUFXLEdBQUcsV0FBVyxDQUFDLE1BQU0sQ0FBQyxDQUFDO1FBQ3hDLE1BQU0sY0FBYyxHQUFHLFFBQVEsQ0FBQyxXQUFXLENBQUMsV0FBVyxDQUFDLENBQUM7UUFDekQsTUFBTSx3QkFBd0IsR0FBRyxJQUFJLENBQUMsT0FBTyxDQUFDLDBCQUEwQixDQUFDLENBQUM7UUFFMUUscUVBQXFFO1FBQ3JFLDZFQUE2RTtRQUM3RSxvRUFBb0U7UUFDcEUsSUFBSSxDQUFDLGNBQWMsRUFBRSxDQUFDO1lBQ3BCLHNFQUFzRTtZQUN0RSxtRUFBbUU7WUFDbkUsb0RBQW9EO1lBQ3BELDBFQUEwRTtZQUMxRSxrRUFBa0U7WUFDbEUseURBQXlEO1lBQ3pELE9BQU8sQ0FBQyxLQUFLLENBQUMseUNBQXlDLEVBQUUsV0FBVyxDQUFDLENBQUM7WUFDdEUsT0FBTyxDQUFDLEtBQUssQ0FBQyxzREFBc0QsQ0FBQyxDQUFDO1lBQ3RFLE9BQU8sQ0FBQyxLQUFLLENBQ1gsa0ZBQWtGLENBQ25GLENBQUM7WUFDRixPQUFPLFdBQVcsQ0FBQztRQUNyQixDQUFDO1FBRUQseUZBQXlGO1FBQ3pGLGtGQUFrRjtRQUNsRixnRkFBZ0Y7UUFDaEYsSUFDRSxjQUFjLENBQUMsWUFBWTtZQUMzQixDQUFDLHNCQUFzQjtZQUN2QiwyQkFBMkIsQ0FBQyxXQUFXLENBQUMsRUFDeEMsQ0FBQztZQUNELE9BQU8sQ0FBQyxLQUFLLENBQUMsMEVBQTBFLENBQUMsQ0FBQztZQUMxRixPQUFPLENBQUMsS0FBSyxDQUNYLG9FQUFvRTtnQkFDbEUsNEJBQTRCLENBQy9CLENBQUM7WUFDRixPQUFPLENBQUMsS0FBSyxDQUFDLHVFQUF1RSxDQUFDLENBQUM7WUFDdkYsT0FBTyxXQUFXLENBQUM7UUFDckIsQ0FBQztRQUVELE1BQU0sdUJBQXVCLEdBQUcsNEJBQTRCLENBQUMsY0FBYyxDQUFDLGNBQWMsQ0FBQyxDQUFDO1FBQzVGLE1BQU0sc0JBQXNCLEdBQUcsMkJBQTJCLENBQUMsY0FBYyxDQUFDLE9BQU8sQ0FBQyxDQUFDO1FBRW5GLFdBQVcsQ0FBQyxNQUFNLEdBQUcsYUFBYSxDQUNoQyxJQUFJLENBQUMsUUFBUSxDQUFDLHdCQUF3QixFQUFFLHVCQUF1QixDQUFDLENBQ2pFLENBQUM7UUFDRixXQUFXLENBQUMsT0FBTyxHQUFHLGFBQWEsQ0FDakMsSUFBSSxDQUFDLFFBQVEsQ0FBQyx3QkFBd0IsRUFBRSxzQkFBc0IsQ0FBQyxDQUNoRSxDQUFDO1FBRUYsT0FBTyxXQUFXLENBQUM7SUFDckIsQ0FBQztJQUVEOzs7T0FHRztJQUNILFNBQVMsd0JBQXdCLENBQUMsV0FBa0M7UUFDbEUsSUFBSSxXQUFXLENBQUMsSUFBSSxLQUFLLFNBQVMsSUFBSSxXQUFXLENBQUMsSUFBSSxLQUFLLFFBQVEsRUFBRSxDQUFDO1lBQ3BFLE1BQU0sS0FBSyxDQUNULHVFQUF1RTtnQkFDckUsZ0ZBQWdGLENBQ25GLENBQUM7UUFDSixDQUFDO1FBRUQsTUFBTSxjQUFjLEdBQWdCLEVBQUMsR0FBRyxXQUFXLEVBQUMsQ0FBQztRQUVyRCxjQUFjLENBQUMsSUFBSSxHQUFHLFFBQVEsQ0FBQztRQUUvQixxRUFBcUU7UUFDckUsZ0VBQWdFO1FBQ2hFLDBCQUEwQixDQUFDLGNBQWMsRUFBRSxnQkFBZ0IsRUFBRSxFQUFDLE9BQU8sRUFBRSxnQkFBZ0IsRUFBQyxDQUFDLENBQUM7UUFFMUYseUZBQXlGO1FBQ3pGLGlFQUFpRTtRQUNqRSxLQUFLLE1BQU0sQ0FBQyxVQUFVLEVBQUUsVUFBVSxDQUFDLElBQUksTUFBTSxDQUFDLE9BQU8sQ0FBQyxRQUFRLENBQUMsV0FBVyxDQUFDLEVBQUUsQ0FBQztZQUM1RSxNQUFNLE9BQU8sR0FBRyxxQkFBcUIsQ0FBQyxVQUFVLENBQUM7Z0JBQy9DLENBQUMsQ0FBQyxLQUFLLG9CQUFvQixDQUFDLFVBQVUsQ0FBQyxFQUFFO2dCQUN6QyxDQUFDLENBQUMsR0FBRyxDQUFDO1lBQ1IsTUFBTSx1QkFBdUIsR0FBRyw0QkFBNEIsQ0FBQyxVQUFVLENBQUMsY0FBYyxDQUFDLENBQUM7WUFDeEYsTUFBTSxvQkFBb0IsR0FBRywyQkFBMkIsQ0FBQyxVQUFVLENBQUMsT0FBTyxDQUFDLENBQUM7WUFFN0UsbUZBQW1GO1lBQ25GLGdGQUFnRjtZQUNoRixzREFBc0Q7WUFDdEQsMEJBQTBCLENBQUMsY0FBYyxFQUFFLE9BQU8sRUFBRTtnQkFDbEQsS0FBSyxFQUFFLGFBQWEsQ0FBQyxvQkFBb0IsQ0FBQztnQkFDMUMseURBQXlEO2dCQUN6RCxPQUFPLEVBQUUsYUFBYSxDQUFDLHVCQUF1QixDQUFDO2FBQ2hELENBQUMsQ0FBQztRQUNMLENBQUM7UUFFRCxPQUFPLGNBQWMsQ0FBQztJQUN4QixDQUFDO0lBRUQ7OztPQUdHO0lBQ0gsU0FBUywwQkFBMEIsQ0FDakMsV0FBd0IsRUFDeEIsT0FBZSxFQUNmLE9BQTBCO1FBRTFCLElBQUksV0FBVyxDQUFDLE9BQU8sS0FBSyxTQUFTLEVBQUUsQ0FBQztZQUN0QyxXQUFXLENBQUMsT0FBTyxHQUFHLEVBQUUsQ0FBQztRQUMzQixDQUFDO1FBQ0QsSUFBSSxXQUFXLENBQUMsT0FBTyxDQUFDLE9BQU8sQ0FBQyxLQUFLLFNBQVMsRUFBRSxDQUFDO1lBQy9DLFdBQVcsQ0FBQyxPQUFPLENBQUMsT0FBTyxDQUFDLEdBQUcsRUFBRSxDQUFDO1FBQ3BDLENBQUM7UUFFRCxNQUFNLGFBQWEsR0FBRyxXQUFXLENBQUMsT0FBTyxDQUFDLE9BQU8sQ0FBQyxDQUFDO1FBRW5ELGlGQUFpRjtRQUNqRixrRkFBa0Y7UUFDbEYsaUZBQWlGO1FBQ2pGLEtBQUssTUFBTSxhQUFhLElBQUksTUFBTSxDQUFDLElBQUksQ0FBQyxPQUFPLENBQThCLEVBQUUsQ0FBQztZQUM5RSxJQUFJLGFBQWEsQ0FBQyxhQUFhLENBQUMsS0FBSyxTQUFTLEVBQUUsQ0FBQztnQkFDL0MsTUFBTSxLQUFLLENBQ1QsNkNBQTZDLE9BQU8sV0FBVyxhQUFhLElBQUk7b0JBQzlFLGlFQUFpRSxDQUNwRSxDQUFDO1lBQ0osQ0FBQztZQUVELGdGQUFnRjtZQUNoRiw0RUFBNEU7WUFDNUUsYUFBYSxDQUFDLGFBQWEsQ0FBQyxHQUFHLE9BQU8sQ0FBQyxhQUFhLENBQUMsQ0FBQztRQUN4RCxDQUFDO0lBQ0gsQ0FBQztJQUVELHNGQUFzRjtJQUN0RixTQUFTLDJCQUEyQixDQUFDLGFBQW9DO1FBQ3ZFLE9BQU8sTUFBTSxDQUFDLElBQUksQ0FBQyxhQUFhLENBQUMsQ0FBQyxJQUFJLENBQUMsQ0FBQyxTQUFpQixFQUFFLEVBQUUsQ0FDM0Qsa0NBQWtDLENBQUMsUUFBUSxDQUFDLFNBQXlDLENBQUMsQ0FDdkYsQ0FBQztJQUNKLENBQUM7SUFFRDs7O09BR0c7SUFDSCxTQUFTLGFBQWEsQ0FBQyxJQUFZO1FBQ2pDLE1BQU0sTUFBTSxHQUFHLElBQUksQ0FBQyxPQUFPLENBQUMsS0FBSyxFQUFFLEdBQUcsQ0FBQyxDQUFDO1FBQ3hDLE9BQU8sTUFBTSxDQUFDLFVBQVUsQ0FBQyxHQUFHLENBQUMsQ0FBQyxDQUFDLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxLQUFLLE1BQU0sRUFBRSxDQUFDO0lBQ3pELENBQUM7QUFDSCxDQUFDIiwic291cmNlc0NvbnRlbnQiOlsiLyoqXG4gKiBAbGljZW5zZVxuICogQ29weXJpZ2h0IEdvb2dsZSBMTEMgQWxsIFJpZ2h0cyBSZXNlcnZlZC5cbiAqXG4gKiBVc2Ugb2YgdGhpcyBzb3VyY2UgY29kZSBpcyBnb3Zlcm5lZCBieSBhbiBNSVQtc3R5bGUgbGljZW5zZSB0aGF0IGNhbiBiZVxuICogZm91bmQgaW4gdGhlIExJQ0VOU0UgZmlsZSBhdCBodHRwczovL2FuZ3VsYXIuZGV2L2xpY2Vuc2VcbiAqL1xuXG5pbXBvcnQgKiBhcyBmcyBmcm9tICdmcyc7XG5pbXBvcnQgKiBhcyBwYXRoIGZyb20gJ3BhdGgnO1xuXG5pbXBvcnQge0JhemVsRmlsZUluZm8sIFBhY2thZ2VNZXRhZGF0YX0gZnJvbSAnLi9hcGknO1xuaW1wb3J0IHthbmFseXplRmlsZUFuZEVuc3VyZU5vQ3Jvc3NJbXBvcnRzfSBmcm9tICcuL2Nyb3NzX2VudHJ5X3BvaW50c19pbXBvcnRzJztcblxuLyoqXG4gKiBMaXN0IG9mIGtub3duIGBwYWNrYWdlLmpzb25gIGZpZWxkcyB3aGljaCBwcm92aWRlIGluZm9ybWF0aW9uIGFib3V0XG4gKiBzdXBwb3J0ZWQgcGFja2FnZSBmb3JtYXRzIGFuZCB0aGVpciBhc3NvY2lhdGVkIGVudHJ5IHBhdGhzLlxuICovXG5jb25zdCBrbm93bkZvcm1hdFBhY2thZ2VKc29uRm9ybWF0RmllbGRzID0gWydtYWluJywgJ3R5cGluZ3MnLCAnbW9kdWxlJ10gYXMgY29uc3Q7XG5cbi8qKiBVbmlvbiB0eXBlIG1hdGNoaW5nIGtub3duIGBwYWNrYWdlLmpzb25gIGZvcm1hdCBmaWVsZHMuICovXG50eXBlIEtub3duUGFja2FnZUpzb25Gb3JtYXRGaWVsZHMgPSAodHlwZW9mIGtub3duRm9ybWF0UGFja2FnZUpzb25Gb3JtYXRGaWVsZHMpW251bWJlcl07XG5cbi8qKlxuICogVHlwZSBkZXNjcmliaW5nIHRoZSBjb25kaXRpb25hbCBleHBvcnRzIGRlc2NyaXB0b3IgZm9yIGFuIGVudHJ5LXBvaW50LlxuICogaHR0cHM6Ly9ub2RlanMub3JnL2FwaS9wYWNrYWdlcy5odG1sI3BhY2thZ2VzX2NvbmRpdGlvbmFsX2V4cG9ydHNcbiAqL1xudHlwZSBDb25kaXRpb25hbEV4cG9ydCA9IHtcbiAgdHlwZXM/OiBzdHJpbmc7XG4gIGRlZmF1bHQ/OiBzdHJpbmc7XG59O1xuXG4vKiogVHlwZSBkZXNjcmliaW5nIGEgYHBhY2thZ2UuanNvbmAgdGhlIHBhY2thZ2VyIGRlYWxzIHdpdGguICovXG50eXBlIFBhY2thZ2VKc29uID0ge1xuICBba2V5IGluIEtub3duUGFja2FnZUpzb25Gb3JtYXRGaWVsZHNdPzogc3RyaW5nO1xufSAmIHtcbiAgbmFtZTogc3RyaW5nO1xuICB0eXBlPzogc3RyaW5nO1xuICBleHBvcnRzPzogUmVjb3JkPHN0cmluZywgQ29uZGl0aW9uYWxFeHBvcnQ+O1xufTtcblxuLy8gTWFpbiBlbnRyeS1wb2ludC5cbm1haW4ocHJvY2Vzcy5hcmd2LnNsaWNlKDIpKTtcblxuZnVuY3Rpb24gbWFpbihhcmdzOiBzdHJpbmdbXSk6IHZvaWQge1xuICAvLyBUaGlzIHV0aWxpdHkgZXhwZWN0cyBhbGwgb2YgaXRzIGFyZ3VtZW50cyB0byBiZSBzcGVjaWZpZWQgaW4gYSBwYXJhbXMgZmlsZSBnZW5lcmF0ZWQgYnlcbiAgLy8gYmF6ZWwgKHNlZSBodHRwczovL2RvY3MuYmF6ZWwuYnVpbGQvdmVyc2lvbnMvbWFzdGVyL3NreWxhcmsvbGliL0FyZ3MuaHRtbCN1c2VfcGFyYW1fZmlsZSkuXG4gIGNvbnN0IHBhcmFtRmlsZVBhdGggPSBhcmdzWzBdO1xuXG4gIC8vIEJhemVsIHBhcmFtcyBtYXkgYmUgc3Vycm91bmRlZCB3aXRoIHF1b3Rlc1xuICBmdW5jdGlvbiB1bnF1b3RlUGFyYW1ldGVyKHM6IHN0cmluZykge1xuICAgIHJldHVybiBzLnJlcGxhY2UoL14nKC4qKSckLywgJyQxJyk7XG4gIH1cblxuICAvLyBQYXJhbWV0ZXJzIGFyZSBzcGVjaWZpZWQgaW4gdGhlIGZpbGUgb25lIHBlciBsaW5lLlxuICBjb25zdCBwYXJhbXMgPSBmcy5yZWFkRmlsZVN5bmMocGFyYW1GaWxlUGF0aCwgJ3V0Zi04Jykuc3BsaXQoJ1xcbicpLm1hcCh1bnF1b3RlUGFyYW1ldGVyKTtcblxuICBjb25zdCBbXG4gICAgLy8gT3V0cHV0IGRpcmVjdG9yeSBmb3IgdGhlIG5wbSBwYWNrYWdlLlxuICAgIG91dHB1dERpckV4ZWNQYXRoLFxuXG4gICAgLy8gVGhlIHBhY2thZ2Ugc2VnbWVudCBvZiB0aGUgbmdfcGFja2FnZSBydWxlJ3MgbGFiZWwgKGUuZy4gJ3BhY2thZ2UvY29tbW9uJykuXG4gICAgb3duaW5nUGFja2FnZU5hbWUsXG5cbiAgICAvLyBKU09OIGRhdGEgY2FwdHVyaW5nIG1ldGFkYXRhIG9mIHRoZSBwYWNrYWdlIGJlaW5nIGJ1aWx0LiBTZWUgYFBhY2thZ2VNZXRhZGF0YWAuXG4gICAgbWV0YWRhdGFBcmcsXG5cbiAgICAvLyBQYXRoIHRvIHRoZSBwYWNrYWdlJ3MgUkVBRE1FLm1kLlxuICAgIHJlYWRtZU1kLFxuXG4gICAgLy8gUGF0aCB0byB0aGUgcGFja2FnZSdzIExJQ0VOU0UgZmlsZS5cbiAgICBsaWNlbnNlRmlsZSxcblxuICAgIC8vIExpc3Qgb2Ygcm9sbGVkLXVwIGZsYXQgRVMyMDIyIG1vZHVsZXNcbiAgICBmZXNtMjAyMkFyZyxcblxuICAgIC8vIExpc3Qgb2YgaW5kaXZpZHVhbCBFUzIwMjIgbW9kdWxlc1xuICAgIGVzbTIwMjJBcmcsXG5cbiAgICAvLyBMaXN0IG9mIHN0YXRpYyBmaWxlcyB0aGF0IHNob3VsZCBiZSBjb3BpZWQgaW50byB0aGUgcGFja2FnZS5cbiAgICBzdGF0aWNGaWxlc0FyZyxcblxuICAgIC8vIExpc3Qgb2YgYWxsIHR5cGUgZGVmaW5pdGlvbnMgdGhhdCBuZWVkIHRvIHBhY2thZ2VkIGludG8gdGhlIG5nX3BhY2thZ2UuXG4gICAgdHlwZURlZmluaXRpb25zQXJnLFxuICBdID0gcGFyYW1zO1xuXG4gIGNvbnN0IGZlc20yMDIyID0gSlNPTi5wYXJzZShmZXNtMjAyMkFyZykgYXMgQmF6ZWxGaWxlSW5mb1tdO1xuICBjb25zdCBlc20yMDIyID0gSlNPTi5wYXJzZShlc20yMDIyQXJnKSBhcyBCYXplbEZpbGVJbmZvW107XG4gIGNvbnN0IHR5cGVEZWZpbml0aW9ucyA9IEpTT04ucGFyc2UodHlwZURlZmluaXRpb25zQXJnKSBhcyBCYXplbEZpbGVJbmZvW107XG4gIGNvbnN0IHN0YXRpY0ZpbGVzID0gSlNPTi5wYXJzZShzdGF0aWNGaWxlc0FyZykgYXMgQmF6ZWxGaWxlSW5mb1tdO1xuICBjb25zdCBtZXRhZGF0YSA9IEpTT04ucGFyc2UobWV0YWRhdGFBcmcpIGFzIFBhY2thZ2VNZXRhZGF0YTtcblxuICBpZiAocmVhZG1lTWQpIHtcbiAgICBjb3B5RmlsZShyZWFkbWVNZCwgJ1JFQURNRS5tZCcpO1xuICB9XG5cbiAgaWYgKGxpY2Vuc2VGaWxlKSB7XG4gICAgY29weUZpbGUobGljZW5zZUZpbGUsICdMSUNFTlNFJyk7XG4gIH1cblxuICAvKipcbiAgICogV3JpdGVzIGEgZmlsZSB3aXRoIHRoZSBzcGVjaWZpZWQgY29udGVudCBpbnRvIHRoZSBwYWNrYWdlIG91dHB1dC5cbiAgICogQHBhcmFtIG91dHB1dFJlbGF0aXZlUGF0aCBSZWxhdGl2ZSBwYXRoIGluIHRoZSBvdXRwdXQgZGlyZWN0b3J5IHdoZXJlIHRoZVxuICAgKiAgIGZpbGUgaXMgd3JpdHRlbiB0by5cbiAgICogQHBhcmFtIGZpbGVDb250ZW50IENvbnRlbnQgb2YgdGhlIGZpbGUuXG4gICAqL1xuICBmdW5jdGlvbiB3cml0ZUZpbGUob3V0cHV0UmVsYXRpdmVQYXRoOiBzdHJpbmcsIGZpbGVDb250ZW50OiBzdHJpbmcgfCBCdWZmZXIpIHtcbiAgICBjb25zdCBvdXRwdXRQYXRoID0gcGF0aC5qb2luKG91dHB1dERpckV4ZWNQYXRoLCBvdXRwdXRSZWxhdGl2ZVBhdGgpO1xuXG4gICAgLy8gQWx3YXlzIGVuc3VyZSB0aGF0IHRoZSB0YXJnZXQgZGlyZWN0b3J5IGV4aXN0cy5cbiAgICBmcy5ta2RpclN5bmMocGF0aC5kaXJuYW1lKG91dHB1dFBhdGgpLCB7cmVjdXJzaXZlOiB0cnVlfSk7XG4gICAgZnMud3JpdGVGaWxlU3luYyhvdXRwdXRQYXRoLCBmaWxlQ29udGVudCk7XG4gIH1cblxuICAvKipcbiAgICogQ29waWVzIGEgZmlsZSBpbnRvIHRoZSBwYWNrYWdlIG91dHB1dCB0byB0aGUgc3BlY2lmaWVkIGxvY2F0aW9uLlxuICAgKiBAcGFyYW0gaW5wdXRQYXRoIEZpbGUgdGhhdCBzaG91bGQgYmUgY29waWVkLlxuICAgKiBAcGFyYW0gb3V0cHV0UmVsYXRpdmVQYXRoIFJlbGF0aXZlIHBhdGggaW4gdGhlIG91dHB1dCBkaXJlY3Rvcnkgd2hlcmUgdGhlXG4gICAqICAgZmlsZSBpcyB3cml0dGVuIHRvLlxuICAgKi9cbiAgZnVuY3Rpb24gY29weUZpbGUoaW5wdXRQYXRoOiBzdHJpbmcsIG91dHB1dFJlbGF0aXZlUGF0aDogc3RyaW5nKSB7XG4gICAgY29uc3QgZmlsZUNvbnRlbnQgPSBmcy5yZWFkRmlsZVN5bmMoaW5wdXRQYXRoLCAndXRmOCcpO1xuICAgIHdyaXRlRmlsZShvdXRwdXRSZWxhdGl2ZVBhdGgsIGZpbGVDb250ZW50KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBHZXRzIHRoZSByZWxhdGl2ZSBwYXRoIGZvciB0aGUgZ2l2ZW4gZmlsZSB3aXRoaW4gdGhlIG93bmluZyBwYWNrYWdlLiBUaGlzXG4gICAqIGFzc3VtZXMgdGhlIGZpbGUgaXMgY29udGFpbmVkIGluIHRoZSBvd25pbmcgcGFja2FnZS5cbiAgICpcbiAgICogZS5nLiBjb25zaWRlciB0aGUgb3duaW5nIHBhY2thZ2UgaXMgYHBhY2thZ2VzL2NvcmVgIGFuZCB0aGUgaW5wdXQgZmlsZVxuICAgKiBpcyBgcGFja2FnZXMvY29yZS90ZXN0aW5nL2luZGV4LmQudHNgLiBUaGlzIGZ1bmN0aW9uIHdvdWxkIHJldHVybiB0aGVcbiAgICogcmVsYXRpdmUgcGF0aCBhcyBmb2xsb3dlZDogYHRlc3RpbmcvaW5kZXguZC50c2AuXG4gICAqL1xuICBmdW5jdGlvbiBnZXRPd25pbmdQYWNrYWdlUmVsYXRpdmVQYXRoKGZpbGU6IEJhemVsRmlsZUluZm8pOiBzdHJpbmcge1xuICAgIHJldHVybiBwYXRoLnJlbGF0aXZlKG93bmluZ1BhY2thZ2VOYW1lLCBmaWxlLnNob3J0UGF0aCk7XG4gIH1cblxuICAvKiogR2V0cyB0aGUgb3V0cHV0LXJlbGF0aXZlIHBhdGggd2hlcmUgdGhlIGdpdmVuIGZsYXQgRVNNIGZpbGUgc2hvdWxkIGJlIHdyaXR0ZW4gdG8uICovXG4gIGZ1bmN0aW9uIGdldEZsYXRFc21PdXRwdXRSZWxhdGl2ZVBhdGgoZmlsZTogQmF6ZWxGaWxlSW5mbykge1xuICAgIC8vIEZsYXQgRVNNIGZpbGVzIHNob3VsZCBiZSBwdXQgaW50byB0aGVpciBvd25pbmcgcGFja2FnZSByZWxhdGl2ZSBzdWItcGF0aC4gZS5nLiBpZlxuICAgIC8vIHRoZXJlIGlzIGEgYnVuZGxlIGluIGBwYWNrYWdlcy9hbmltYXRpb25zL2Zlc20yMDIyL2Jyb3dzZXIvdGVzdGluZy5tanNgIHRoZW4gd2VcbiAgICAvLyB3YW50IHRoZSBidW5kbGUgdG8gYmUgc3RvcmVkIGluIGBmZXNtMjAyMi9icm93c2VyL3Rlc3RpbmcubWpzYC4gU2FtZSB0aGluZyBhcHBsaWVzXG4gICAgLy8gZm9yIHRoZSBgZmVzbTIwMjJgIGJ1bmRsZXMuIFRoZSBkaXJlY3RvcnkgbmFtZSBmb3IgYGZlc21gIGlzIGFscmVhZHkgZGVjbGFyZWQgYXNcbiAgICAvLyBwYXJ0IG9mIHRoZSBCYXplbCBhY3Rpb24gZ2VuZXJhdGluZyB0aGVzZSBmaWxlcy4gU2VlIGBuZ19wYWNrYWdlLmJ6bGAuXG4gICAgcmV0dXJuIGdldE93bmluZ1BhY2thZ2VSZWxhdGl2ZVBhdGgoZmlsZSk7XG4gIH1cblxuICAvKiogR2V0cyB0aGUgb3V0cHV0LXJlbGF0aXZlIHBhdGggd2hlcmUgdGhlIHR5cGluZyBmaWxlIGlzIGJlaW5nIHdyaXR0ZW4gdG8uICovXG4gIGZ1bmN0aW9uIGdldFR5cGluZ091dHB1dFJlbGF0aXZlUGF0aChmaWxlOiBCYXplbEZpbGVJbmZvKSB7XG4gICAgLy8gVHlwZSBkZWZpbml0aW9ucyBhcmUgaW50ZW5kZWQgdG8gYmUgY29waWVkIGludG8gdGhlIHBhY2thZ2Ugb3V0cHV0IHdoaWxlIHByZXNlcnZpbmcgdGhlXG4gICAgLy8gc3ViLXBhdGggZnJvbSB0aGUgb3duaW5nIHBhY2thZ2UuIGUuZy4gYSBmaWxlIGxpa2UgYHBhY2thZ2VzL2FuaW1hdGlvbnMvYnJvd3Nlci9fX2luZGV4LmQudHNgXG4gICAgLy8gd2lsbCBlbmQgdXAgYmVpbmcgd3JpdHRlbiB0byBgPHBrZy1vdXQ+L2Jyb3dzZXIvaW5kZXguZC50c2AuIE5vdGUgdGhhdCB0eXBlcyBhcmUgYnVuZGxlZFxuICAgIC8vIGFzIGEgc2VwYXJhdGUgYWN0aW9uIGluIHRoZSBgbmdfcGFja2FnZWAgU3RhcmxhcmsgcnVsZSBhbmQgcHJlZml4ZWQgd2l0aCBgX19gIHRvIGF2b2lkXG4gICAgLy8gY29uZmxpY3RzIHdpdGggc291cmNlIGBpbmRleC5kLnRzYCBmaWxlcy4gV2UgcmVtb3ZlIHRoaXMgcHJlZml4IGhlcmUuXG4gICAgcmV0dXJuIGdldE93bmluZ1BhY2thZ2VSZWxhdGl2ZVBhdGgoZmlsZSkucmVwbGFjZSgvX19pbmRleFxcLmRcXC50cyQvLCAnaW5kZXguZC50cycpO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHMgdGhlIGVudHJ5LXBvaW50IHN1Yi1wYXRoIGZyb20gdGhlIHBhY2thZ2Ugcm9vdC4gZS5nLiBpZiB0aGUgcGFja2FnZSBuYW1lXG4gICAqIGlzIGBAYW5ndWxhci9jZGtgLCB0aGVuIGZvciBgQGFuZ3VsYXIvY2RrL2ExMXlgIGp1c3QgYGExMXlgIHdvdWxkIGJlIHJldHVybmVkLlxuICAgKi9cbiAgZnVuY3Rpb24gZ2V0RW50cnlQb2ludFN1YnBhdGgobW9kdWxlTmFtZTogc3RyaW5nKTogc3RyaW5nIHtcbiAgICByZXR1cm4gbW9kdWxlTmFtZS5zbGljZShgJHttZXRhZGF0YS5ucG1QYWNrYWdlTmFtZX0vYC5sZW5ndGgpO1xuICB9XG5cbiAgLyoqXG4gICAqIEdldHMgd2hldGhlciB0aGUgZ2l2ZW4gbW9kdWxlIG5hbWUgcmVzb2x2ZXMgdG8gYSBzZWNvbmRhcnkgZW50cnktcG9pbnQuXG4gICAqIGUuZy4gaWYgdGhlIHBhY2thZ2UgbmFtZSBpcyBgQGFuZ3VsYXIvY2RrYCwgdGhlbiBmb3IgYEBhbmd1bGFyL2Nkay9hMTF5YFxuICAgKiB0aGlzIHdvdWxkIHJldHVybiBgdHJ1ZWAuXG4gICAqL1xuICBmdW5jdGlvbiBpc1NlY29uZGFyeUVudHJ5UG9pbnQobW9kdWxlTmFtZTogc3RyaW5nKTogYm9vbGVhbiB7XG4gICAgcmV0dXJuIGdldEVudHJ5UG9pbnRTdWJwYXRoKG1vZHVsZU5hbWUpICE9PSAnJztcbiAgfVxuXG4gIGNvbnN0IGNyb3NzRW50cnlQb2ludEZhaWx1cmVzID0gZXNtMjAyMi5mbGF0TWFwKChmaWxlKSA9PlxuICAgIGFuYWx5emVGaWxlQW5kRW5zdXJlTm9Dcm9zc0ltcG9ydHMoZmlsZSwgbWV0YWRhdGEpLFxuICApO1xuXG4gIGlmIChjcm9zc0VudHJ5UG9pbnRGYWlsdXJlcy5sZW5ndGgpIHtcbiAgICBjb25zb2xlLmVycm9yKGNyb3NzRW50cnlQb2ludEZhaWx1cmVzKTtcbiAgICBwcm9jZXNzLmV4aXQoMSk7XG4gIH1cblxuICAvLyBDb3B5IGFsbCBGRVNNIGZpbGVzIGludG8gdGhlIHBhY2thZ2Ugb3V0cHV0LlxuICBmZXNtMjAyMi5mb3JFYWNoKChmKSA9PiBjb3B5RmlsZShmLnBhdGgsIGdldEZsYXRFc21PdXRwdXRSZWxhdGl2ZVBhdGgoZikpKTtcblxuICAvLyBDb3B5IGFsbCB0eXBlIGRlZmluaXRpb25zIGludG8gdGhlIHBhY2thZ2UsIHByZXNlcnZpbmcgdGhlIHN1Yi1wYXRoIGZyb20gdGhlXG4gIC8vIG93bmluZyBwYWNrYWdlLiBlLmcuIGEgZmlsZSBsaWtlIGBwYWNrYWdlcy9hbmltYXRpb25zL2Jyb3dzZXIvX19pbmRleC5kLnRzYCB3aWxsXG4gIC8vIGVuZCB1cCBpbiBgYnJvd3Nlci9pbmRleC5kLnRzYFxuICB0eXBlRGVmaW5pdGlvbnMuZm9yRWFjaCgoZikgPT4gY29weUZpbGUoZi5wYXRoLCBnZXRUeXBpbmdPdXRwdXRSZWxhdGl2ZVBhdGgoZikpKTtcblxuICBmb3IgKGNvbnN0IGZpbGUgb2Ygc3RhdGljRmlsZXMpIHtcbiAgICAvLyBXZSBjb3B5IGFsbCBmaWxlcyBpbnRvIHRoZSBwYWNrYWdlIG91dHB1dCB3aGlsZSBwcmVzZXJ2aW5nIHRoZSBzdWItcGF0aCBmcm9tXG4gICAgLy8gdGhlIG93bmluZyBwYWNrYWdlLiBlLmcuIGBwYWNrYWdlcy9jb3JlL3BhY2thZ2UuanNvbmAgZW5kcyB1cCBgPHBrZy1vdXQ+L3BhY2thZ2UuanNvbmAuXG4gICAgY29uc3Qgb3V0cHV0UmVsYXRpdmVQYXRoID0gZ2V0T3duaW5nUGFja2FnZVJlbGF0aXZlUGF0aChmaWxlKTtcbiAgICBsZXQgY29udGVudCA9IGZzLnJlYWRGaWxlU3luYyhmaWxlLnBhdGgsICd1dGY4Jyk7XG5cbiAgICAvLyBDaGVjayBhbmQgbW9kaWZ5IHBhY2thZ2UuanNvbiBmaWxlcyBhcyBuZWNlc3NhcnkgZm9yIHB1Ymxpc2hpbmdcbiAgICBpZiAocGF0aC5iYXNlbmFtZShmaWxlLnBhdGgpID09PSAncGFja2FnZS5qc29uJykge1xuICAgICAgY29uc3QgaXNQcmltYXJ5UGFja2FnZUpzb24gPSBvdXRwdXRSZWxhdGl2ZVBhdGggPT09ICdwYWNrYWdlLmpzb24nO1xuICAgICAgY29uc3QgcGFja2FnZUpzb24gPSBKU09OLnBhcnNlKGNvbnRlbnQpIGFzIFBhY2thZ2VKc29uO1xuICAgICAgY29uc3QgcGFja2FnZU5hbWUgPSBwYWNrYWdlSnNvblsnbmFtZSddO1xuXG4gICAgICAvLyBQcmV2ZW50IG5vbi1wcmltYXJ5IGBwYWNrYWdlLmpzb25gIGZpbGVzIHdoaWNoIHdvdWxkIHRocm93LW9mZiByZXNvbHV0aW9uLlxuICAgICAgLy8gUmVzb2x1dGlvbiBpbiB0aGUgcGFja2FnZSBzaG91bGQgb25seSBiZSBiYXNlZCBvbiB0aGUgdG9wLWxldmVsIGBwYWNrYWdlLmpzb25gLlxuICAgICAgaWYgKCFpc1ByaW1hcnlQYWNrYWdlSnNvbikge1xuICAgICAgICB0aHJvdyBFcnJvcihcbiAgICAgICAgICBgRm91bmQgYSBuZXN0ZWQgXCJwYWNrYWdlLmpzb25cIiBmaWxlIGluIHRoZSBwYWNrYWdlIG91dHB1dDogJHtmaWxlLnNob3J0UGF0aH0uXFxuYCArXG4gICAgICAgICAgICBgQWxsIGluZm9ybWF0aW9uIG9mIHRoZSBwYWNrYWdlIHNob3VsZCByZXNpZGUgaW4gdGhlIHByaW1hcnkgcGFja2FnZSBmaWxlLmAsXG4gICAgICAgICk7XG4gICAgICB9XG5cbiAgICAgIC8vIENoZWNrIGlmIHRoZSBgbmFtZWAgZmllbGQgb2YgdGhlIGBwYWNrYWdlLmpzb25gIGZpbGVzIGFyZSBtYXRjaGluZyB3aXRoXG4gICAgICAvLyBuYW1lIG9mIHRoZSBOUE0gcGFja2FnZS4gVGhpcyBpcyBhbiBhZGRpdGlvbmFsIHNhZmV0eSBjaGVjay5cbiAgICAgIGlmIChwYWNrYWdlTmFtZSAhPT0gbWV0YWRhdGEubnBtUGFja2FnZU5hbWUpIHtcbiAgICAgICAgdGhyb3cgRXJyb3IoXG4gICAgICAgICAgYFByaW1hcnkgXCJwYWNrYWdlLmpzb25cIiBoYXMgbWlzbWF0Y2hpbmcgcGFja2FnZSBuYW1lLiBFeHBlY3RlZCB0aGUgYCArXG4gICAgICAgICAgICBgcGFja2FnZSB0byBiZSBuYW1lZCBcIiR7bWV0YWRhdGEubnBtUGFja2FnZU5hbWV9XCIsIGJ1dCBpcyBzZXQgdG86ICR7cGFja2FnZU5hbWV9LmAsXG4gICAgICAgICk7XG4gICAgICB9XG5cbiAgICAgIGxldCBuZXdQYWNrYWdlSnNvbiA9IGluc2VydEZvcm1hdEZpZWxkc0ludG9QYWNrYWdlSnNvbihcbiAgICAgICAgb3V0cHV0UmVsYXRpdmVQYXRoLFxuICAgICAgICBwYWNrYWdlSnNvbixcbiAgICAgICAgZmFsc2UsXG4gICAgICApO1xuXG4gICAgICBuZXdQYWNrYWdlSnNvbiA9IHVwZGF0ZVByaW1hcnlQYWNrYWdlSnNvbihuZXdQYWNrYWdlSnNvbik7XG5cbiAgICAgIC8vIFVwZGF0ZSB0aGUgY29udGVudCB3aXRoIHRoZSBuZXcgYHBhY2thZ2UuanNvbmAgZmlsZSBjb250ZW50LlxuICAgICAgY29udGVudCA9IEpTT04uc3RyaW5naWZ5KG5ld1BhY2thZ2VKc29uLCBudWxsLCAyKTtcbiAgICB9XG5cbiAgICB3cml0ZUZpbGUob3V0cHV0UmVsYXRpdmVQYXRoLCBjb250ZW50KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBJbnNlcnRzIG9yIGVkaXRzIHByb3BlcnRpZXMgaW50byB0aGUgcGFja2FnZS5qc29uIGZpbGUocykgaW4gdGhlIHBhY2thZ2Ugc28gdGhhdFxuICAgKiB0aGV5IHBvaW50IHRvIGFsbCB0aGUgcmlnaHQgZ2VuZXJhdGVkIGFydGlmYWN0cy5cbiAgICpcbiAgICogQHBhcmFtIHBhY2thZ2VKc29uT3V0UmVsYXRpdmVQYXRoIFBhdGggd2hlcmUgdGhlIGBwYWNrYWdlLmpzb25gIGlzIHN0b3JlZCBpblxuICAgKiAgIHRoZSBwYWNrYWdlIG91dHB1dC5cbiAgICogQHBhcmFtIHBhcnNlZFBhY2thZ2UgUGFyc2VkIHBhY2thZ2UuanNvbiBjb250ZW50XG4gICAqIEBwYXJhbSBpc0dlbmVyYXRlZFBhY2thZ2VKc29uIFdoZXRoZXIgdGhlIHBhc3NlZCBwYWNrYWdlLmpzb24gaGFzIGJlZW4gZ2VuZXJhdGVkLlxuICAgKi9cbiAgZnVuY3Rpb24gaW5zZXJ0Rm9ybWF0RmllbGRzSW50b1BhY2thZ2VKc29uKFxuICAgIHBhY2thZ2VKc29uT3V0UmVsYXRpdmVQYXRoOiBzdHJpbmcsXG4gICAgcGFyc2VkUGFja2FnZTogUmVhZG9ubHk8UGFja2FnZUpzb24+LFxuICAgIGlzR2VuZXJhdGVkUGFja2FnZUpzb246IGJvb2xlYW4sXG4gICk6IFBhY2thZ2VKc29uIHtcbiAgICBjb25zdCBwYWNrYWdlSnNvbjogUGFja2FnZUpzb24gPSB7Li4ucGFyc2VkUGFja2FnZX07XG4gICAgY29uc3QgcGFja2FnZU5hbWUgPSBwYWNrYWdlSnNvblsnbmFtZSddO1xuICAgIGNvbnN0IGVudHJ5UG9pbnRJbmZvID0gbWV0YWRhdGEuZW50cnlQb2ludHNbcGFja2FnZU5hbWVdO1xuICAgIGNvbnN0IHBhY2thZ2VKc29uQ29udGFpbmluZ0RpciA9IHBhdGguZGlybmFtZShwYWNrYWdlSnNvbk91dFJlbGF0aXZlUGF0aCk7XG5cbiAgICAvLyBJZiBhIHBhY2thZ2UganNvbiBmaWxlIGhhcyBiZWVuIGRpc2NvdmVyZWQgdGhhdCBkb2VzIG5vdCBtYXRjaCBhbnlcbiAgICAvLyBlbnRyeS1wb2ludCBpbiB0aGUgbWV0YWRhdGEsIHdlIHJlcG9ydCBhIHdhcm5pbmcgYXMgbW9zdCBsaWtlbHkgdGhlIHRhcmdldFxuICAgIC8vIGlzIGNvbmZpZ3VyZWQgaW5jb3JyZWN0bHkgKGUuZy4gbWlzc2luZyBgbW9kdWxlX25hbWVgIGF0dHJpYnV0ZSkuXG4gICAgaWYgKCFlbnRyeVBvaW50SW5mbykge1xuICAgICAgLy8gSWRlYWxseSB3ZSBzaG91bGQgdGhyb3cgaGVyZSwgYXMgd2UgZ290IGFuIGVudHJ5IHBvaW50IHRoYXQgZG9lc24ndFxuICAgICAgLy8gaGF2ZSBmbGF0IG1vZHVsZSBtZXRhZGF0YSAvIGJ1bmRsZSBpbmRleCwgc28gaXQgbWF5IGhhdmUgYmVlbiBhblxuICAgICAgLy8gbmdfbW9kdWxlIHRoYXQncyBtaXNzaW5nIGEgbW9kdWxlX25hbWUgYXR0cmlidXRlLlxuICAgICAgLy8gSG93ZXZlciwgQGFuZ3VsYXIvY29tcGlsZXIgY2FuJ3QgYmUgYW4gbmdfbW9kdWxlLCBhcyBpdCdzIHRoZSBpbnRlcm5hbHNcbiAgICAgIC8vIG9mIHRoZSBuZ2MgY29tcGlsZXIsIHlldCB3ZSB3YW50IHRvIGJ1aWxkIGFuIG5nX3BhY2thZ2UgZm9yIGl0LlxuICAgICAgLy8gU28gaWdub3JlIHBhY2thZ2UuanNvbiBmaWxlcyB3aGVuIHdlIGFyZSBtaXNzaW5nIGRhdGEuXG4gICAgICBjb25zb2xlLmVycm9yKCdXQVJOSU5HOiBubyBtb2R1bGUgbWV0YWRhdGEgZm9yIHBhY2thZ2UnLCBwYWNrYWdlTmFtZSk7XG4gICAgICBjb25zb2xlLmVycm9yKCcgICBOb3QgdXBkYXRpbmcgdGhlIHBhY2thZ2UuanNvbiBmaWxlIHRvIHBvaW50IHRvIGl0Jyk7XG4gICAgICBjb25zb2xlLmVycm9yKFxuICAgICAgICAnICAgVGhlIG5nX21vZHVsZSBmb3IgdGhpcyBwYWNrYWdlIGlzIHBvc3NpYmx5IG1pc3NpbmcgdGhlIG1vZHVsZV9uYW1lIGF0dHJpYnV0ZSAnLFxuICAgICAgKTtcbiAgICAgIHJldHVybiBwYWNrYWdlSnNvbjtcbiAgICB9XG5cbiAgICAvLyBJZiB3ZSBndWVzc2VkIHRoZSBpbmRleCBwYXRocyBmb3IgYSBtb2R1bGUsIGFuZCBpdCBjb250YWlucyBhbiBleHBsaWNpdCBgcGFja2FnZS5qc29uYFxuICAgIC8vIGZpbGUgdGhhdCBhbHJlYWR5IHNldHMgZm9ybWF0IHByb3BlcnRpZXMsIHdlIHNraXAgYXV0b21hdGljIGluc2VydGlvbiBvZiBmb3JtYXRcbiAgICAvLyBwcm9wZXJ0aWVzIGJ1dCByZXBvcnQgYSB3YXJuaW5nIGluIGNhc2UgcHJvcGVydGllcyBoYXZlIGJlZW4gc2V0IGJ5IGFjY2lkZW50LlxuICAgIGlmIChcbiAgICAgIGVudHJ5UG9pbnRJbmZvLmd1ZXNzZWRQYXRocyAmJlxuICAgICAgIWlzR2VuZXJhdGVkUGFja2FnZUpzb24gJiZcbiAgICAgIGhhc0V4cGxpY2l0Rm9ybWF0UHJvcGVydGllcyhwYWNrYWdlSnNvbilcbiAgICApIHtcbiAgICAgIGNvbnNvbGUuZXJyb3IoJ1dBUk5JTkc6IGBwYWNrYWdlLmpzb25gIGV4cGxpY2l0bHkgc2V0cyBmb3JtYXQgcHJvcGVydGllcyAobGlrZSBgbWFpbmApLicpO1xuICAgICAgY29uc29sZS5lcnJvcihcbiAgICAgICAgJyAgICBTa2lwcGluZyBhdXRvbWF0aWMgaW5zZXJ0aW9uIG9mIGZvcm1hdCBwcm9wZXJ0aWVzIGFzIGV4cGxpY2l0ICcgK1xuICAgICAgICAgICdmb3JtYXQgcHJvcGVydGllcyBhcmUgc2V0LicsXG4gICAgICApO1xuICAgICAgY29uc29sZS5lcnJvcignICAgIElnbm9yZSB0aGlzIHdhcm5pbmcgaWYgZXhwbGljaXQgcHJvcGVydGllcyBhcmUgc2V0IGludGVudGlvbmFsbHkuJyk7XG4gICAgICByZXR1cm4gcGFja2FnZUpzb247XG4gICAgfVxuXG4gICAgY29uc3QgZmVzbTIwMjJSZWxhdGl2ZU91dFBhdGggPSBnZXRGbGF0RXNtT3V0cHV0UmVsYXRpdmVQYXRoKGVudHJ5UG9pbnRJbmZvLmZlc20yMDIyQnVuZGxlKTtcbiAgICBjb25zdCB0eXBpbmdzUmVsYXRpdmVPdXRQYXRoID0gZ2V0VHlwaW5nT3V0cHV0UmVsYXRpdmVQYXRoKGVudHJ5UG9pbnRJbmZvLnR5cGluZ3MpO1xuXG4gICAgcGFja2FnZUpzb24ubW9kdWxlID0gbm9ybWFsaXplUGF0aChcbiAgICAgIHBhdGgucmVsYXRpdmUocGFja2FnZUpzb25Db250YWluaW5nRGlyLCBmZXNtMjAyMlJlbGF0aXZlT3V0UGF0aCksXG4gICAgKTtcbiAgICBwYWNrYWdlSnNvbi50eXBpbmdzID0gbm9ybWFsaXplUGF0aChcbiAgICAgIHBhdGgucmVsYXRpdmUocGFja2FnZUpzb25Db250YWluaW5nRGlyLCB0eXBpbmdzUmVsYXRpdmVPdXRQYXRoKSxcbiAgICApO1xuXG4gICAgcmV0dXJuIHBhY2thZ2VKc29uO1xuICB9XG5cbiAgLyoqXG4gICAqIFVwZGF0ZXMgdGhlIHByaW1hcnkgYHBhY2thZ2UuanNvbmAgZmlsZSBvZiB0aGUgTlBNIHBhY2thZ2UgdG8gc3BlY2lmeVxuICAgKiB0aGUgbW9kdWxlIGNvbmRpdGlvbmFsIGV4cG9ydHMgYW5kIHRoZSBFU00gbW9kdWxlIHR5cGUuXG4gICAqL1xuICBmdW5jdGlvbiB1cGRhdGVQcmltYXJ5UGFja2FnZUpzb24ocGFja2FnZUpzb246IFJlYWRvbmx5PFBhY2thZ2VKc29uPik6IFBhY2thZ2VKc29uIHtcbiAgICBpZiAocGFja2FnZUpzb24udHlwZSAhPT0gdW5kZWZpbmVkICYmIHBhY2thZ2VKc29uLnR5cGUgIT09ICdtb2R1bGUnKSB7XG4gICAgICB0aHJvdyBFcnJvcihcbiAgICAgICAgJ1RoZSBwcmltYXJ5IFwicGFja2FnZS5qc29uXCIgZmlsZSBvZiB0aGUgcGFja2FnZSBzZXRzIHRoZSBcInR5cGVcIiBmaWVsZCAnICtcbiAgICAgICAgICAndGhhdCBpcyBjb250cm9sbGVkIGJ5IHRoZSBwYWNrYWdlci4gUGxlYXNlIHVuc2V0IGl0IG9yIHNldCBgdHlwZWAgdG8gYG1vZHVsZWAuJyxcbiAgICAgICk7XG4gICAgfVxuXG4gICAgY29uc3QgbmV3UGFja2FnZUpzb246IFBhY2thZ2VKc29uID0gey4uLnBhY2thZ2VKc29ufTtcblxuICAgIG5ld1BhY2thZ2VKc29uLnR5cGUgPSAnbW9kdWxlJztcblxuICAgIC8vIFRoZSBgcGFja2FnZS5qc29uYCBmaWxlIGlzIG1hZGUgcHVibGljbHkgYWNjZXNzaWJsZSBmb3IgdG9vbHMgdGhhdFxuICAgIC8vIG1pZ2h0IHdhbnQgdG8gcXVlcnkgaW5mb3JtYXRpb24gZnJvbSB0aGUgQW5ndWxhciBOUE0gcGFja2FnZS5cbiAgICBpbnNlcnRFeHBvcnRNYXBwaW5nT3JFcnJvcihuZXdQYWNrYWdlSnNvbiwgJy4vcGFja2FnZS5qc29uJywge2RlZmF1bHQ6ICcuL3BhY2thZ2UuanNvbid9KTtcblxuICAgIC8vIENhcHR1cmUgYWxsIGVudHJ5LXBvaW50cyBpbiB0aGUgYGV4cG9ydHNgIGZpZWxkIHVzaW5nIHRoZSBzdWJwYXRoIGV4cG9ydCBkZWNsYXJhdGlvbnM6XG4gICAgLy8gaHR0cHM6Ly9ub2RlanMub3JnL2FwaS9wYWNrYWdlcy5odG1sI3BhY2thZ2VzX3N1YnBhdGhfZXhwb3J0cy5cbiAgICBmb3IgKGNvbnN0IFttb2R1bGVOYW1lLCBlbnRyeVBvaW50XSBvZiBPYmplY3QuZW50cmllcyhtZXRhZGF0YS5lbnRyeVBvaW50cykpIHtcbiAgICAgIGNvbnN0IHN1YnBhdGggPSBpc1NlY29uZGFyeUVudHJ5UG9pbnQobW9kdWxlTmFtZSlcbiAgICAgICAgPyBgLi8ke2dldEVudHJ5UG9pbnRTdWJwYXRoKG1vZHVsZU5hbWUpfWBcbiAgICAgICAgOiAnLic7XG4gICAgICBjb25zdCBmZXNtMjAyMk91dFJlbGF0aXZlUGF0aCA9IGdldEZsYXRFc21PdXRwdXRSZWxhdGl2ZVBhdGgoZW50cnlQb2ludC5mZXNtMjAyMkJ1bmRsZSk7XG4gICAgICBjb25zdCB0eXBlc091dFJlbGF0aXZlUGF0aCA9IGdldFR5cGluZ091dHB1dFJlbGF0aXZlUGF0aChlbnRyeVBvaW50LnR5cGluZ3MpO1xuXG4gICAgICAvLyBJbnNlcnQgdGhlIGV4cG9ydCBtYXBwaW5nIGZvciB0aGUgZW50cnktcG9pbnQuIFdlIHNldCBgZGVmYXVsdGAgdG8gdGhlIEZFU00gMjAyMlxuICAgICAgLy8gb3V0cHV0LCBhbmQgYWxzbyBzZXQgdGhlIGB0eXBlc2AgY29uZGl0aW9uIHdoaWNoIHdpbGwgYmUgcmVzcGVjdGVkIGJ5IFRTIDQuNS5cbiAgICAgIC8vIGh0dHBzOi8vZ2l0aHViLmNvbS9taWNyb3NvZnQvVHlwZVNjcmlwdC9wdWxsLzQ1ODg0LlxuICAgICAgaW5zZXJ0RXhwb3J0TWFwcGluZ09yRXJyb3IobmV3UGFja2FnZUpzb24sIHN1YnBhdGgsIHtcbiAgICAgICAgdHlwZXM6IG5vcm1hbGl6ZVBhdGgodHlwZXNPdXRSZWxhdGl2ZVBhdGgpLFxuICAgICAgICAvLyBOb3RlOiBUaGUgZGVmYXVsdCBjb25kaXRpb25zIG5lZWRzIHRvIGJlIHRoZSBsYXN0IG9uZS5cbiAgICAgICAgZGVmYXVsdDogbm9ybWFsaXplUGF0aChmZXNtMjAyMk91dFJlbGF0aXZlUGF0aCksXG4gICAgICB9KTtcbiAgICB9XG5cbiAgICByZXR1cm4gbmV3UGFja2FnZUpzb247XG4gIH1cblxuICAvKipcbiAgICogSW5zZXJ0cyBhIHN1YnBhdGggZXhwb3J0IG1hcHBpbmcgaW50byB0aGUgc3BlY2lmaWVkIGBwYWNrYWdlLmpzb25gIG9iamVjdC5cbiAgICogQHRocm93cyBBbiBlcnJvciBpZiB0aGUgbWFwcGluZyBpcyBhbHJlYWR5IGRlZmluZWQgYW5kIHdvdWxkIGNvbmZsaWN0LlxuICAgKi9cbiAgZnVuY3Rpb24gaW5zZXJ0RXhwb3J0TWFwcGluZ09yRXJyb3IoXG4gICAgcGFja2FnZUpzb246IFBhY2thZ2VKc29uLFxuICAgIHN1YnBhdGg6IHN0cmluZyxcbiAgICBtYXBwaW5nOiBDb25kaXRpb25hbEV4cG9ydCxcbiAgKSB7XG4gICAgaWYgKHBhY2thZ2VKc29uLmV4cG9ydHMgPT09IHVuZGVmaW5lZCkge1xuICAgICAgcGFja2FnZUpzb24uZXhwb3J0cyA9IHt9O1xuICAgIH1cbiAgICBpZiAocGFja2FnZUpzb24uZXhwb3J0c1tzdWJwYXRoXSA9PT0gdW5kZWZpbmVkKSB7XG4gICAgICBwYWNrYWdlSnNvbi5leHBvcnRzW3N1YnBhdGhdID0ge307XG4gICAgfVxuXG4gICAgY29uc3Qgc3VicGF0aEV4cG9ydCA9IHBhY2thZ2VKc29uLmV4cG9ydHNbc3VicGF0aF07XG5cbiAgICAvLyBHbyB0aHJvdWdoIGFsbCBjb25kaXRpb25zIHRoYXQgc2hvdWxkIGJlIGluc2VydGVkLiBJZiB0aGUgY29uZGl0aW9uIGlzIGFscmVhZHlcbiAgICAvLyBtYW51YWxseSBzZXQgb2YgdGhlIHN1YnBhdGggZXhwb3J0LCB3ZSB0aHJvdyBhbiBlcnJvci4gSW4gZ2VuZXJhbCwgd2UgYWxsb3cgZm9yXG4gICAgLy8gYWRkaXRpb25hbCBjb25kaXRpb25zIHRvIGJlIHNldC4gVGhlc2Ugd2lsbCBhbHdheXMgcHJlY2VkZSB0aGUgZ2VuZXJhdGVkIG9uZXMuXG4gICAgZm9yIChjb25zdCBjb25kaXRpb25OYW1lIG9mIE9iamVjdC5rZXlzKG1hcHBpbmcpIGFzIFtrZXlvZiBDb25kaXRpb25hbEV4cG9ydF0pIHtcbiAgICAgIGlmIChzdWJwYXRoRXhwb3J0W2NvbmRpdGlvbk5hbWVdICE9PSB1bmRlZmluZWQpIHtcbiAgICAgICAgdGhyb3cgRXJyb3IoXG4gICAgICAgICAgYEZvdW5kIGEgY29uZmxpY3RpbmcgZXhwb3J0IGNvbmRpdGlvbiBmb3IgXCIke3N1YnBhdGh9XCIuIFRoZSBcIiR7Y29uZGl0aW9uTmFtZX1cIiBgICtcbiAgICAgICAgICAgIGBjb25kaXRpb24gd291bGQgYmUgb3ZlcnJpZGRlbiBieSB0aGUgcGFja2FnZXIuIFBsZWFzZSB1bnNldCBpdC5gLFxuICAgICAgICApO1xuICAgICAgfVxuXG4gICAgICAvLyAqKk5vdGUqKjogVGhlIG9yZGVyIG9mIHRoZSBjb25kaXRpb25zIGlzIHByZXNlcnZlZCBldmVuIHRob3VnaCB3ZSBhcmUgc2V0dGluZ1xuICAgICAgLy8gdGhlIGNvbmRpdGlvbnMgb25jZSBhdCBhIHRpbWUgKHRoZSBsYXRlc3QgYXNzaWdubWVudCB3aWxsIGJlIGF0IHRoZSBlbmQpLlxuICAgICAgc3VicGF0aEV4cG9ydFtjb25kaXRpb25OYW1lXSA9IG1hcHBpbmdbY29uZGl0aW9uTmFtZV07XG4gICAgfVxuICB9XG5cbiAgLyoqIFdoZXRoZXIgdGhlIHBhY2thZ2UgZXhwbGljaXRseSBzZXRzIGFueSBvZiB0aGUgZm9ybWF0IHByb3BlcnRpZXMgKGxpa2UgYG1haW5gKS4gKi9cbiAgZnVuY3Rpb24gaGFzRXhwbGljaXRGb3JtYXRQcm9wZXJ0aWVzKHBhcnNlZFBhY2thZ2U6IFJlYWRvbmx5PFBhY2thZ2VKc29uPik6IGJvb2xlYW4ge1xuICAgIHJldHVybiBPYmplY3Qua2V5cyhwYXJzZWRQYWNrYWdlKS5zb21lKChmaWVsZE5hbWU6IHN0cmluZykgPT5cbiAgICAgIGtub3duRm9ybWF0UGFja2FnZUpzb25Gb3JtYXRGaWVsZHMuaW5jbHVkZXMoZmllbGROYW1lIGFzIEtub3duUGFja2FnZUpzb25Gb3JtYXRGaWVsZHMpLFxuICAgICk7XG4gIH1cblxuICAvKipcbiAgICogTm9ybWFsaXplcyB0aGUgc3BlY2lmaWVkIHBhdGggYnkgcmVwbGFjaW5nIGJhY2tzbGFzaCBzZXBhcmF0b3JzIHdpdGggUG9zaXhcbiAgICogZm9yd2FyZCBzbGFzaCBzZXBhcmF0b3JzLlxuICAgKi9cbiAgZnVuY3Rpb24gbm9ybWFsaXplUGF0aChwYXRoOiBzdHJpbmcpOiBzdHJpbmcge1xuICAgIGNvbnN0IHJlc3VsdCA9IHBhdGgucmVwbGFjZSgvXFxcXC9nLCAnLycpO1xuICAgIHJldHVybiByZXN1bHQuc3RhcnRzV2l0aCgnLicpID8gcmVzdWx0IDogYC4vJHtyZXN1bHR9YDtcbiAgfVxufVxuIl19