/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define("angular/packages/bazel/src/ng_package/packager", ["require", "exports", "fs", "path", "shelljs"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.newArray = void 0;
    const fs = require("fs");
    const path = require("path");
    const shx = require("shelljs");
    function main(args) {
        // Exit immediately when encountering an error.
        shx.set('-e');
        // Keep track of whether an error has occured so that we can return an appropriate exit code.
        let errorHasOccured = false;
        // This utility expects all of its arguments to be specified in a params file generated by
        // bazel (see https://docs.bazel.build/versions/master/skylark/lib/Args.html#use_param_file).
        const paramFilePath = args[0];
        // Bazel params may be surrounded with quotes
        function unquoteParameter(s) {
            return s.replace(/^'(.*)'$/, '$1');
        }
        // Parameters are specified in the file one per line.
        const params = fs.readFileSync(paramFilePath, 'utf-8').split('\n').map(unquoteParameter);
        const [
        // Output directory for the npm package.
        out, 
        // The package segment of the ng_package rule's label (e.g. 'package/common').
        srcDir, 
        // The bazel-bin dir joined with the srcDir (e.g. 'bazel-bin/package.common').
        // This is the intended output location for package artifacts.
        binDir, 
        // The bazel-genfiles dir joined with the srcDir (e.g. 'bazel-bin/package.common').
        genfilesDir, 
        // JSON data mapping each entry point to the generated bundle index and
        // flat module metadata, for example
        // {"@angular/core": {
        //     "index": "bazel-bin/packages/core/core.js",
        //     "typings": "bazel-bin/packages/core/core.d.ts",
        //     "metadata": "bazel-bin/packages/core/core.metadata.json"
        //  },
        // ...
        // }
        modulesManifestArg, 
        // Path to the package's README.md.
        readmeMd, 
        // List of rolled-up flat ES2015 modules
        fesm2015Arg, 
        // List of individual ES2015 modules
        esm2015Arg, 
        // List of all UMD bundles generated by rollup.
        bundlesArg, 
        // List of all files in the ng_package rule's srcs.
        srcsArg, 
        // List of all type definitions that need to packaged into the ng_package.
        typeDefinitionsArg, 
        // List of all files in the ng_package rule's data.
        dataArg, 
        // Path to the package's LICENSE.
        licenseFile, 
        // List of all dts bundles generated by the API extractor.
        dtsBundleArg, 
        // The dts bundle file suffix example: '.bundle.d.ts'
        dtsBundleFileSuffix,] = params;
        const fesm2015 = fesm2015Arg.split(',').filter(s => !!s);
        const esm2015 = esm2015Arg.split(',').filter(s => !!s);
        const bundles = bundlesArg.split(',').filter(s => !!s);
        const typeDefinitions = typeDefinitionsArg.split(',').filter(s => !!s);
        const srcs = srcsArg.split(',').filter(s => !!s);
        const dataFiles = dataArg.split(',').filter(s => !!s);
        const modulesManifest = JSON.parse(modulesManifestArg);
        const dtsBundles = dtsBundleArg.split(',').filter(s => !!s);
        /**
         * List of known `package.json` fields which provide information about
         * supported package formats and their associated entry paths.
         */
        const knownFormatPackageJsonFields = ['main', 'fesm2015', 'esm2015', 'typings', 'module', 'es2015'];
        if (readmeMd) {
            copyFile(readmeMd, out);
        }
        /**
         * Writes a file into the package based on its input path, relativizing to the package path.
         * @param inputPath Path to the file in the input tree.
         * @param fileContent Content of the file.
         */
        function writeFileFromInputPath(inputPath, fileContent) {
            // We want the relative path from the given file to its ancestor "root" directory.
            // This root depends on whether the file lives in the source tree (srcDir) as a basic file
            // input to ng_package, the bin output tree (binDir) as the output of another rule, or
            // the genfiles output tree (genfilesDir) as the output of a genrule.
            let rootDir;
            if (inputPath.includes(binDir)) {
                rootDir = binDir;
            }
            else if (inputPath.includes(genfilesDir)) {
                rootDir = genfilesDir;
            }
            else {
                rootDir = srcDir;
            }
            const outputPath = path.join(out, path.relative(rootDir, inputPath));
            // Always ensure that the target directory exists.
            shx.mkdir('-p', path.dirname(outputPath));
            fs.writeFileSync(outputPath, fileContent);
        }
        /**
         * Copies a file into the package based on its input path, relativizing to the package path.
         * @param inputPath a path relative to the binDir, typically from a file in the deps[]
         */
        function copyFileFromInputPath(inputPath) {
            writeFileFromInputPath(inputPath, fs.readFileSync(inputPath));
        }
        /**
         * Relativize the path where a file is written.
         * @param file a path containing a re-rooted segment like `.esm2015`
         * @param outDir path where we copy the file, relative to the out
         */
        function writeEsmFile(file, outDir) {
            // Path computed relative to the current package in bazel-bin. e.g. a ES2015 output file
            // in `bazel-out/<..>/packages/core/src/di.js` should be stored in `{out_dir}/src/di.js`
            // if the package target has been declared in `<..>/packages/core`.
            const packageRelativePath = path.dirname(path.relative(binDir, file));
            if (!packageRelativePath.startsWith('..')) {
                copyFile(file, path.join(out, outDir), packageRelativePath);
            }
        }
        esm2015.forEach(file => writeEsmFile(file, 'esm2015'));
        bundles.forEach(bundle => {
            copyFile(bundle, out, 'bundles');
        });
        fesm2015.forEach(file => {
            copyFile(file, out, 'fesm2015');
        });
        // Copy all type definitions into the package. This is necessary so that developers can use
        // the package with type definitions.
        typeDefinitions.forEach(f => writeFileFromInputPath(f, readTypingsAndStripAmdModule(f)));
        // Copy all `data` files into the package. These are files that aren't built by the ng_package
        // rule, but instead are just straight copied into the package, e.g. global CSS assets.
        dataFiles.forEach(f => copyFileFromInputPath(f));
        // Iterate through the entry point modules
        // We do this first because we also record new paths for the esm5 and esm2015 copies
        // of the index JS file, which we need to amend the package.json.
        Object.keys(modulesManifest).forEach(moduleName => {
            const moduleFiles = modulesManifest[moduleName];
            const relative = path.relative(binDir, moduleFiles['index']);
            moduleFiles['esm2015_index'] = path.join(binDir, 'esm2015', relative);
            // Metadata file is optional as entry-points can be built with the `ts_library`
            // rule or `ng_module` rule in Ivy mode.
            const metadataFile = moduleFiles['metadata'];
            if (!metadataFile) {
                return;
            }
            const typingsOutFile = moduleFiles['typings'];
            // We only support all modules within a package to be dts bundled
            // ie: if @angular/common/http has flat dts, so should @angular/common
            if (dtsBundles.length) {
                const metadataContent = rewireMetadata(metadataFile, typingsOutFile);
                writeFileFromInputPath(metadataFile, metadataContent);
            }
            else {
                copyFileFromInputPath(metadataFile);
            }
        });
        const licenseBanner = licenseFile ? fs.readFileSync(licenseFile, 'utf-8') : '';
        dtsBundles.forEach(bundleFile => {
            const cleanDistPath = bundleFile.replace(dtsBundleFileSuffix, '.d.ts');
            // API extractor will not dedupe license comments from various files
            // this will remove all the license comments and append the license banner.
            const content = licenseBanner + '\n' +
                readTypingsAndStripAmdModule(bundleFile)
                    .replace(/(\/\*\*\s+\*\s\@license(((?!\*\/).|\s)*)\*\/)/gm, '');
            writeFileFromInputPath(cleanDistPath, content);
        });
        // Root package name (e.g. '@angular/common'), captures as we iterate through sources below.
        let rootPackageName = '';
        const packagesWithExistingPackageJson = new Set();
        for (const src of srcs) {
            if (src.includes(binDir) || src.includes(genfilesDir)) {
                errorHasOccured = true;
                console.error('The "srcs" for ng_package should not include output of other rules. Found:\n' +
                    `  ${src}`);
            }
            let content = fs.readFileSync(src, 'utf-8');
            // Modify package.json files as necessary for publishing
            if (path.basename(src) === 'package.json') {
                const packageJson = JSON.parse(content);
                content = amendPackageJson(src, packageJson, false);
                const packageName = packageJson['name'];
                packagesWithExistingPackageJson.add(packageName);
                // Keep track of the root package name, e.g. "@angular/common". We assume that the
                // root name will be shortest because secondary entry-points will append to it
                // (e.g. "@angular/common/http").
                if (!rootPackageName || packageName.length < rootPackageName.length) {
                    rootPackageName = packageJson['name'];
                }
            }
            writeFileFromInputPath(src, content);
        }
        // Generate extra files for secondary entry-points.
        Object.keys(modulesManifest).forEach(entryPointPackageName => {
            const entryPointName = entryPointPackageName.substr(rootPackageName.length + 1);
            if (!entryPointName)
                return;
            const metadataFilePath = modulesManifest[entryPointPackageName]['metadata'];
            if (metadataFilePath) {
                createMetadataReexportFile(entryPointName, modulesManifest[entryPointPackageName]['metadata'], entryPointPackageName);
            }
            createTypingsReexportFile(entryPointName, licenseBanner, modulesManifest[entryPointPackageName]['typings']);
            if (!packagesWithExistingPackageJson.has(entryPointPackageName)) {
                createEntryPointPackageJson(entryPointName, entryPointPackageName);
            }
        });
        return errorHasOccured ? 1 : 0;
        /**
         * Convert a binDir-relative path to srcDir-relative
         * @param from path to a file under the srcDir, like packages/core/testing/package.json
         * @param file path to a file under the binDir, like bazel-bin/core/testing/generated.js
         */
        function srcDirRelative(from, file) {
            const result = normalizeSeparators(path.relative(path.dirname(from), path.join(srcDir, path.relative(binDir, file))));
            if (result.startsWith('..'))
                return result;
            return `./${result}`;
        }
        function copyFile(file, baseDir, relative = '.') {
            const dir = path.join(baseDir, relative);
            // output file is .js if the input file is .mjs
            const outFile = path.posix.join(dir, path.basename(file.endsWith('.mjs') ? file.replace(/\.mjs$/, '.js') : file));
            shx.mkdir('-p', dir);
            shx.cp(file, outFile);
            // Double-underscore is used to escape forward slash in FESM filenames.
            // See ng_package.bzl:
            //   fesm_output_filename = entry_point.replace("/", "__")
            // We need to unescape these.
            if (outFile.indexOf('__') >= 0) {
                const outputPath = path.join(dir, ...path.basename(outFile).split('__'));
                shx.mkdir('-p', path.dirname(outputPath));
                shx.mv(path.join(dir, path.basename(file)), outputPath);
                // if we are renaming the .js file, we'll also need to update the sourceMappingURL in the file
                if (outFile.endsWith('.js')) {
                    shx.chmod('+w', outputPath);
                    shx.sed('-i', `${path.basename(file)}.map`, `${path.basename(outputPath)}.map`, outputPath);
                }
            }
        }
        /**
         * Inserts or edits properties into the package.json file(s) in the package so that
         * they point to all the right generated artifacts.
         *
         * @param packageJson The path to the package.json file.
         * @param parsedPackage Parsed package.json content
         * @param isGeneratedPackageJson Whether the passed package.json has been generated.
         */
        function amendPackageJson(packageJson, parsedPackage, isGeneratedPackageJson) {
            const packageName = parsedPackage['name'];
            const moduleData = modulesManifest[packageName];
            // If a package json file has been discovered that does not match any
            // module in the manifest, we report a warning as most likely the target
            // is configured incorrectly (e.g. missing `module_name` attribute).
            if (!moduleData) {
                // Ideally we should throw here, as we got an entry point that doesn't
                // have flat module metadata / bundle index, so it may have been an
                // ng_module that's missing a module_name attribute.
                // However, @angular/compiler can't be an ng_module, as it's the internals
                // of the ngc compiler, yet we want to build an ng_package for it.
                // So ignore package.json files when we are missing data.
                console.error('WARNING: no module metadata for package', packageName);
                console.error('   Not updating the package.json file to point to it');
                console.error('   The ng_module for this package is possibly missing the module_name attribute ');
                return JSON.stringify(parsedPackage, null, 2);
            }
            // If we guessed the index paths for a module, and it contains an explicit `package.json`
            // file that already sets format properties, we skip automatic insertion of format
            // properties but report a warning in case properties have been set by accident.
            if (moduleData.guessedPaths && !isGeneratedPackageJson &&
                hasExplicitFormatProperties(parsedPackage)) {
                console.error('WARNING: `package.json` explicitly sets format properties (like `main`).');
                console.error('    Skipping automatic insertion of format properties as explicit ' +
                    'format properties are set.');
                console.error('    Ignore this warning if explicit properties are set intentionally.');
                return JSON.stringify(parsedPackage, null, 2);
            }
            // Derive the paths to the files from the hard-coded names we gave them.
            // TODO(alexeagle): it would be better to transfer this information from the place
            // where we created the filenames, via the modulesManifestArg
            parsedPackage['main'] = getBundleName(packageName, 'bundles');
            parsedPackage['fesm2015'] = getBundleName(packageName, 'fesm2015');
            parsedPackage['esm2015'] = srcDirRelative(packageJson, moduleData['esm2015_index']);
            parsedPackage['typings'] = srcDirRelative(packageJson, moduleData['typings']);
            // For now, we point the primary entry points at the fesm files, because of Webpack
            // performance issues with a large number of individual files.
            parsedPackage['module'] = parsedPackage['fesm2015'];
            parsedPackage['es2015'] = parsedPackage['fesm2015'];
            return JSON.stringify(parsedPackage, null, 2);
        }
        // e.g. @angular/common/http/testing -> ../../bundles/common-http-testing.umd.js
        // or   @angular/common/http/testing -> ../../fesm2015/http/testing.js
        function getBundleName(packageName, dir) {
            const parts = packageName.split('/');
            // Remove the scoped package part, like @angular if present
            const nameParts = packageName.startsWith('@') ? parts.splice(1) : parts;
            const relativePath = newArray(nameParts.length - 1, '..').join('/') || '.';
            let basename;
            if (dir === 'bundles') {
                basename = nameParts.join('-') + '.umd';
            }
            else if (nameParts.length === 1) {
                basename = nameParts[0];
            }
            else {
                basename = nameParts.slice(1).join('/');
            }
            return [relativePath, dir, basename + '.js'].join('/');
        }
        /** Whether the package explicitly sets any of the format properties (like `main`). */
        function hasExplicitFormatProperties(parsedPackage) {
            return Object.keys(parsedPackage)
                .some(propertyName => knownFormatPackageJsonFields.includes(propertyName));
        }
        /** Creates metadata re-export file for a secondary entry-point. */
        function createMetadataReexportFile(entryPointName, metadataFile, packageName) {
            const inputPath = path.join(srcDir, `${entryPointName}.metadata.json`);
            writeFileFromInputPath(inputPath, JSON.stringify({
                '__symbolic': 'module',
                'version': 3,
                'metadata': {},
                'exports': [{ 'from': `${srcDirRelative(inputPath, metadataFile.replace(/.metadata.json$/, ''))}` }],
                'flatModuleIndexRedirect': true,
                'importAs': packageName
            }) + '\n');
        }
        /**
         * Creates a typings (d.ts) re-export file for a secondary-entry point,
         * e.g., `export * from './common/common'`
         */
        function createTypingsReexportFile(entryPointName, license, typingsFile) {
            const inputPath = path.join(srcDir, `${entryPointName}.d.ts`);
            const content = `${license}
export * from '${srcDirRelative(inputPath, typingsFile.replace(/\.d\.tsx?$/, ''))}';
`;
            writeFileFromInputPath(inputPath, content);
        }
        /**
         * Creates a package.json for a secondary entry-point.
         * @param dir The directory under which the package.json should be written.
         * @param entryPointPackageName The full package name for the entry point,
         *     e.g. '@angular/common/http'.
         */
        function createEntryPointPackageJson(dir, entryPointPackageName) {
            const pkgJson = path.join(srcDir, dir, 'package.json');
            const content = amendPackageJson(pkgJson, { name: entryPointPackageName }, true);
            writeFileFromInputPath(pkgJson, content);
        }
        /**
         * Normalizes the specified path by replacing backslash separators with Posix
         * forward slash separators.
         */
        function normalizeSeparators(path) {
            return path.replace(/\\/g, '/');
        }
        /**
         * Rewires metadata to point to the flattened dts file.
         *
         * @param metadataPath the metadata file path
         * @param typingsPath the typings bundle entrypoint
         */
        function rewireMetadata(metadataPath, typingsPath) {
            const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf-8'));
            let typingsRelativePath = normalizeSeparators(path.relative(path.dirname(metadataPath), typingsPath));
            if (!typingsRelativePath.startsWith('..')) {
                typingsRelativePath = `./${typingsRelativePath}`;
            }
            typingsRelativePath = typingsRelativePath.replace('.d.ts', '');
            // the regexp here catches all relative paths such as:
            // ./src/core/foo.d.ts and ../src/core/foo.d.ts
            const relativePathRegex = /\.?\.\/[\w\.\-_\/]+/g;
            if (metadata.exports) {
                // Strip re-exports which are now self-references
                metadata.exports =
                    metadata.exports.filter((e) => !e.from.match(relativePathRegex));
            }
            return JSON.stringify(metadata).replace(relativePathRegex, typingsRelativePath);
        }
        /**
         * Strip the named AMD module for compatibility with non-bazel users from typings content
         * @param filePath dts file path
         */
        function readTypingsAndStripAmdModule(filePath) {
            return fs
                .readFileSync(filePath, 'utf-8')
                // Strip the named AMD module for compatibility with non-bazel users
                .replace(/^\/\/\/ <amd-module name=.*\/>[\r\n]+/gm, '');
        }
    }
    if (require.main === module) {
        process.exitCode = main(process.argv.slice(2));
    }
    function newArray(size, value) {
        const list = [];
        for (let i = 0; i < size; i++) {
            list.push(value);
        }
        return list;
    }
    exports.newArray = newArray;
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGFja2FnZXIuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi8uLi8uLi8uLi9wYWNrYWdlcy9iYXplbC9zcmMvbmdfcGFja2FnZS9wYWNrYWdlci50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7O0dBTUc7Ozs7Ozs7Ozs7Ozs7SUFFSCx5QkFBeUI7SUFDekIsNkJBQTZCO0lBQzdCLCtCQUErQjtJQUUvQixTQUFTLElBQUksQ0FBQyxJQUFjO1FBQzFCLCtDQUErQztRQUMvQyxHQUFHLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDO1FBRWQsNkZBQTZGO1FBQzdGLElBQUksZUFBZSxHQUFHLEtBQUssQ0FBQztRQUU1QiwwRkFBMEY7UUFDMUYsNkZBQTZGO1FBQzdGLE1BQU0sYUFBYSxHQUFHLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUU5Qiw2Q0FBNkM7UUFDN0MsU0FBUyxnQkFBZ0IsQ0FBQyxDQUFTO1lBQ2pDLE9BQU8sQ0FBQyxDQUFDLE9BQU8sQ0FBQyxVQUFVLEVBQUUsSUFBSSxDQUFDLENBQUM7UUFDckMsQ0FBQztRQUVELHFEQUFxRDtRQUNyRCxNQUFNLE1BQU0sR0FBRyxFQUFFLENBQUMsWUFBWSxDQUFDLGFBQWEsRUFBRSxPQUFPLENBQUMsQ0FBQyxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUMsR0FBRyxDQUFDLGdCQUFnQixDQUFDLENBQUM7UUFFekYsTUFBTTtRQUNGLHdDQUF3QztRQUN4QyxHQUFHO1FBRUgsOEVBQThFO1FBQzlFLE1BQU07UUFFTiw4RUFBOEU7UUFDOUUsOERBQThEO1FBQzlELE1BQU07UUFFTixtRkFBbUY7UUFDbkYsV0FBVztRQUVYLHVFQUF1RTtRQUN2RSxvQ0FBb0M7UUFDcEMsc0JBQXNCO1FBQ3RCLGtEQUFrRDtRQUNsRCxzREFBc0Q7UUFDdEQsK0RBQStEO1FBQy9ELE1BQU07UUFDTixNQUFNO1FBQ04sSUFBSTtRQUNKLGtCQUFrQjtRQUVsQixtQ0FBbUM7UUFDbkMsUUFBUTtRQUVSLHdDQUF3QztRQUN4QyxXQUFXO1FBRVgsb0NBQW9DO1FBQ3BDLFVBQVU7UUFFViwrQ0FBK0M7UUFDL0MsVUFBVTtRQUVWLG1EQUFtRDtRQUNuRCxPQUFPO1FBRVAsMEVBQTBFO1FBQzFFLGtCQUFrQjtRQUVsQixtREFBbUQ7UUFDbkQsT0FBTztRQUVQLGlDQUFpQztRQUNqQyxXQUFXO1FBRVgsMERBQTBEO1FBQzFELFlBQVk7UUFFWixxREFBcUQ7UUFDckQsbUJBQW1CLEVBQ3RCLEdBQUcsTUFBTSxDQUFDO1FBRVgsTUFBTSxRQUFRLEdBQUcsV0FBVyxDQUFDLEtBQUssQ0FBQyxHQUFHLENBQUMsQ0FBQyxNQUFNLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7UUFDekQsTUFBTSxPQUFPLEdBQUcsVUFBVSxDQUFDLEtBQUssQ0FBQyxHQUFHLENBQUMsQ0FBQyxNQUFNLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7UUFDdkQsTUFBTSxPQUFPLEdBQUcsVUFBVSxDQUFDLEtBQUssQ0FBQyxHQUFHLENBQUMsQ0FBQyxNQUFNLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7UUFDdkQsTUFBTSxlQUFlLEdBQUcsa0JBQWtCLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUN2RSxNQUFNLElBQUksR0FBRyxPQUFPLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUNqRCxNQUFNLFNBQVMsR0FBYSxPQUFPLENBQUMsS0FBSyxDQUFDLEdBQUcsQ0FBQyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUNoRSxNQUFNLGVBQWUsR0FBRyxJQUFJLENBQUMsS0FBSyxDQUFDLGtCQUFrQixDQUF5QixDQUFDO1FBQy9FLE1BQU0sVUFBVSxHQUFhLFlBQVksQ0FBQyxLQUFLLENBQUMsR0FBRyxDQUFDLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBRXRFOzs7V0FHRztRQUNILE1BQU0sNEJBQTRCLEdBQzlCLENBQUMsTUFBTSxFQUFFLFVBQVUsRUFBRSxTQUFTLEVBQUUsU0FBUyxFQUFFLFFBQVEsRUFBRSxRQUFRLENBQUMsQ0FBQztRQUVuRSxJQUFJLFFBQVEsRUFBRTtZQUNaLFFBQVEsQ0FBQyxRQUFRLEVBQUUsR0FBRyxDQUFDLENBQUM7U0FDekI7UUFFRDs7OztXQUlHO1FBQ0gsU0FBUyxzQkFBc0IsQ0FBQyxTQUFpQixFQUFFLFdBQTBCO1lBQzNFLGtGQUFrRjtZQUNsRiwwRkFBMEY7WUFDMUYsc0ZBQXNGO1lBQ3RGLHFFQUFxRTtZQUNyRSxJQUFJLE9BQWUsQ0FBQztZQUNwQixJQUFJLFNBQVMsQ0FBQyxRQUFRLENBQUMsTUFBTSxDQUFDLEVBQUU7Z0JBQzlCLE9BQU8sR0FBRyxNQUFNLENBQUM7YUFDbEI7aUJBQU0sSUFBSSxTQUFTLENBQUMsUUFBUSxDQUFDLFdBQVcsQ0FBQyxFQUFFO2dCQUMxQyxPQUFPLEdBQUcsV0FBVyxDQUFDO2FBQ3ZCO2lCQUFNO2dCQUNMLE9BQU8sR0FBRyxNQUFNLENBQUM7YUFDbEI7WUFFRCxNQUFNLFVBQVUsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLEdBQUcsRUFBRSxJQUFJLENBQUMsUUFBUSxDQUFDLE9BQU8sRUFBRSxTQUFTLENBQUMsQ0FBQyxDQUFDO1lBRXJFLGtEQUFrRDtZQUNsRCxHQUFHLENBQUMsS0FBSyxDQUFDLElBQUksRUFBRSxJQUFJLENBQUMsT0FBTyxDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUM7WUFDMUMsRUFBRSxDQUFDLGFBQWEsQ0FBQyxVQUFVLEVBQUUsV0FBVyxDQUFDLENBQUM7UUFDNUMsQ0FBQztRQUVEOzs7V0FHRztRQUNILFNBQVMscUJBQXFCLENBQUMsU0FBaUI7WUFDOUMsc0JBQXNCLENBQUMsU0FBUyxFQUFFLEVBQUUsQ0FBQyxZQUFZLENBQUMsU0FBUyxDQUFDLENBQUMsQ0FBQztRQUNoRSxDQUFDO1FBRUQ7Ozs7V0FJRztRQUNILFNBQVMsWUFBWSxDQUFDLElBQVksRUFBRSxNQUFjO1lBQ2hELHdGQUF3RjtZQUN4Rix3RkFBd0Y7WUFDeEYsbUVBQW1FO1lBQ25FLE1BQU0sbUJBQW1CLEdBQUcsSUFBSSxDQUFDLE9BQU8sQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxJQUFJLENBQUMsQ0FBQyxDQUFDO1lBQ3RFLElBQUksQ0FBQyxtQkFBbUIsQ0FBQyxVQUFVLENBQUMsSUFBSSxDQUFDLEVBQUU7Z0JBQ3pDLFFBQVEsQ0FBQyxJQUFJLEVBQUUsSUFBSSxDQUFDLElBQUksQ0FBQyxHQUFHLEVBQUUsTUFBTSxDQUFDLEVBQUUsbUJBQW1CLENBQUMsQ0FBQzthQUM3RDtRQUNILENBQUM7UUFFRCxPQUFPLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxFQUFFLENBQUMsWUFBWSxDQUFDLElBQUksRUFBRSxTQUFTLENBQUMsQ0FBQyxDQUFDO1FBRXZELE9BQU8sQ0FBQyxPQUFPLENBQUMsTUFBTSxDQUFDLEVBQUU7WUFDdkIsUUFBUSxDQUFDLE1BQU0sRUFBRSxHQUFHLEVBQUUsU0FBUyxDQUFDLENBQUM7UUFDbkMsQ0FBQyxDQUFDLENBQUM7UUFDSCxRQUFRLENBQUMsT0FBTyxDQUFDLElBQUksQ0FBQyxFQUFFO1lBQ3RCLFFBQVEsQ0FBQyxJQUFJLEVBQUUsR0FBRyxFQUFFLFVBQVUsQ0FBQyxDQUFDO1FBQ2xDLENBQUMsQ0FBQyxDQUFDO1FBRUgsMkZBQTJGO1FBQzNGLHFDQUFxQztRQUNyQyxlQUFlLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsc0JBQXNCLENBQUMsQ0FBQyxFQUFFLDRCQUE0QixDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUV6Riw4RkFBOEY7UUFDOUYsdUZBQXVGO1FBQ3ZGLFNBQVMsQ0FBQyxPQUFPLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxxQkFBcUIsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO1FBRWpELDBDQUEwQztRQUMxQyxvRkFBb0Y7UUFDcEYsaUVBQWlFO1FBQ2pFLE1BQU0sQ0FBQyxJQUFJLENBQUMsZUFBZSxDQUFDLENBQUMsT0FBTyxDQUFDLFVBQVUsQ0FBQyxFQUFFO1lBQ2hELE1BQU0sV0FBVyxHQUFHLGVBQWUsQ0FBQyxVQUFVLENBQUMsQ0FBQztZQUNoRCxNQUFNLFFBQVEsR0FBRyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxXQUFXLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQztZQUU3RCxXQUFXLENBQUMsZUFBZSxDQUFDLEdBQUcsSUFBSSxDQUFDLElBQUksQ0FBQyxNQUFNLEVBQUUsU0FBUyxFQUFFLFFBQVEsQ0FBQyxDQUFDO1lBRXRFLCtFQUErRTtZQUMvRSx3Q0FBd0M7WUFDeEMsTUFBTSxZQUFZLEdBQUcsV0FBVyxDQUFDLFVBQVUsQ0FBQyxDQUFDO1lBQzdDLElBQUksQ0FBQyxZQUFZLEVBQUU7Z0JBQ2pCLE9BQU87YUFDUjtZQUVELE1BQU0sY0FBYyxHQUFHLFdBQVcsQ0FBQyxTQUFTLENBQUMsQ0FBQztZQUM5QyxpRUFBaUU7WUFDakUsc0VBQXNFO1lBQ3RFLElBQUksVUFBVSxDQUFDLE1BQU0sRUFBRTtnQkFDckIsTUFBTSxlQUFlLEdBQUcsY0FBYyxDQUFDLFlBQVksRUFBRSxjQUFjLENBQUMsQ0FBQztnQkFDckUsc0JBQXNCLENBQUMsWUFBWSxFQUFFLGVBQWUsQ0FBQyxDQUFDO2FBQ3ZEO2lCQUFNO2dCQUNMLHFCQUFxQixDQUFDLFlBQVksQ0FBQyxDQUFDO2FBQ3JDO1FBQ0gsQ0FBQyxDQUFDLENBQUM7UUFFSCxNQUFNLGFBQWEsR0FBRyxXQUFXLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxZQUFZLENBQUMsV0FBVyxFQUFFLE9BQU8sQ0FBQyxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUM7UUFFL0UsVUFBVSxDQUFDLE9BQU8sQ0FBQyxVQUFVLENBQUMsRUFBRTtZQUM5QixNQUFNLGFBQWEsR0FBRyxVQUFVLENBQUMsT0FBTyxDQUFDLG1CQUFtQixFQUFFLE9BQU8sQ0FBQyxDQUFDO1lBQ3ZFLG9FQUFvRTtZQUNwRSwyRUFBMkU7WUFDM0UsTUFBTSxPQUFPLEdBQUcsYUFBYSxHQUFHLElBQUk7Z0JBQ2hDLDRCQUE0QixDQUFDLFVBQVUsQ0FBQztxQkFDbkMsT0FBTyxDQUFDLGlEQUFpRCxFQUFFLEVBQUUsQ0FBQyxDQUFDO1lBRXhFLHNCQUFzQixDQUFDLGFBQWEsRUFBRSxPQUFPLENBQUMsQ0FBQztRQUNqRCxDQUFDLENBQUMsQ0FBQztRQUVILDRGQUE0RjtRQUM1RixJQUFJLGVBQWUsR0FBRyxFQUFFLENBQUM7UUFDekIsTUFBTSwrQkFBK0IsR0FBRyxJQUFJLEdBQUcsRUFBVSxDQUFDO1FBRTFELEtBQUssTUFBTSxHQUFHLElBQUksSUFBSSxFQUFFO1lBQ3RCLElBQUksR0FBRyxDQUFDLFFBQVEsQ0FBQyxNQUFNLENBQUMsSUFBSSxHQUFHLENBQUMsUUFBUSxDQUFDLFdBQVcsQ0FBQyxFQUFFO2dCQUNyRCxlQUFlLEdBQUcsSUFBSSxDQUFDO2dCQUN2QixPQUFPLENBQUMsS0FBSyxDQUNULDhFQUE4RTtvQkFDOUUsS0FBSyxHQUFHLEVBQUUsQ0FBQyxDQUFDO2FBQ2pCO1lBRUQsSUFBSSxPQUFPLEdBQUcsRUFBRSxDQUFDLFlBQVksQ0FBQyxHQUFHLEVBQUUsT0FBTyxDQUFDLENBQUM7WUFDNUMsd0RBQXdEO1lBQ3hELElBQUksSUFBSSxDQUFDLFFBQVEsQ0FBQyxHQUFHLENBQUMsS0FBSyxjQUFjLEVBQUU7Z0JBQ3pDLE1BQU0sV0FBVyxHQUFHLElBQUksQ0FBQyxLQUFLLENBQUMsT0FBTyxDQUE0QixDQUFDO2dCQUNuRSxPQUFPLEdBQUcsZ0JBQWdCLENBQUMsR0FBRyxFQUFFLFdBQVcsRUFBRSxLQUFLLENBQUMsQ0FBQztnQkFFcEQsTUFBTSxXQUFXLEdBQUcsV0FBVyxDQUFDLE1BQU0sQ0FBQyxDQUFDO2dCQUN4QywrQkFBK0IsQ0FBQyxHQUFHLENBQUMsV0FBVyxDQUFDLENBQUM7Z0JBRWpELGtGQUFrRjtnQkFDbEYsOEVBQThFO2dCQUM5RSxpQ0FBaUM7Z0JBQ2pDLElBQUksQ0FBQyxlQUFlLElBQUksV0FBVyxDQUFDLE1BQU0sR0FBRyxlQUFlLENBQUMsTUFBTSxFQUFFO29CQUNuRSxlQUFlLEdBQUcsV0FBVyxDQUFDLE1BQU0sQ0FBQyxDQUFDO2lCQUN2QzthQUNGO1lBQ0Qsc0JBQXNCLENBQUMsR0FBRyxFQUFFLE9BQU8sQ0FBQyxDQUFDO1NBQ3RDO1FBRUQsbURBQW1EO1FBQ25ELE1BQU0sQ0FBQyxJQUFJLENBQUMsZUFBZSxDQUFDLENBQUMsT0FBTyxDQUFDLHFCQUFxQixDQUFDLEVBQUU7WUFDM0QsTUFBTSxjQUFjLEdBQUcscUJBQXFCLENBQUMsTUFBTSxDQUFDLGVBQWUsQ0FBQyxNQUFNLEdBQUcsQ0FBQyxDQUFDLENBQUM7WUFDaEYsSUFBSSxDQUFDLGNBQWM7Z0JBQUUsT0FBTztZQUU1QixNQUFNLGdCQUFnQixHQUFHLGVBQWUsQ0FBQyxxQkFBcUIsQ0FBQyxDQUFDLFVBQVUsQ0FBQyxDQUFDO1lBQzVFLElBQUksZ0JBQWdCLEVBQUU7Z0JBQ3BCLDBCQUEwQixDQUN0QixjQUFjLEVBQUUsZUFBZSxDQUFDLHFCQUFxQixDQUFDLENBQUMsVUFBVSxDQUFDLEVBQ2xFLHFCQUFxQixDQUFDLENBQUM7YUFDNUI7WUFFRCx5QkFBeUIsQ0FDckIsY0FBYyxFQUFFLGFBQWEsRUFBRSxlQUFlLENBQUMscUJBQXFCLENBQUMsQ0FBQyxTQUFTLENBQUMsQ0FBQyxDQUFDO1lBRXRGLElBQUksQ0FBQywrQkFBK0IsQ0FBQyxHQUFHLENBQUMscUJBQXFCLENBQUMsRUFBRTtnQkFDL0QsMkJBQTJCLENBQUMsY0FBYyxFQUFFLHFCQUFxQixDQUFDLENBQUM7YUFDcEU7UUFDSCxDQUFDLENBQUMsQ0FBQztRQUVILE9BQU8sZUFBZSxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztRQUUvQjs7OztXQUlHO1FBQ0gsU0FBUyxjQUFjLENBQUMsSUFBWSxFQUFFLElBQVk7WUFDaEQsTUFBTSxNQUFNLEdBQUcsbUJBQW1CLENBQzlCLElBQUksQ0FBQyxRQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBQyxJQUFJLENBQUMsRUFBRSxJQUFJLENBQUMsSUFBSSxDQUFDLE1BQU0sRUFBRSxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxJQUFJLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztZQUN2RixJQUFJLE1BQU0sQ0FBQyxVQUFVLENBQUMsSUFBSSxDQUFDO2dCQUFFLE9BQU8sTUFBTSxDQUFDO1lBQzNDLE9BQU8sS0FBSyxNQUFNLEVBQUUsQ0FBQztRQUN2QixDQUFDO1FBRUQsU0FBUyxRQUFRLENBQUMsSUFBWSxFQUFFLE9BQWUsRUFBRSxRQUFRLEdBQUcsR0FBRztZQUM3RCxNQUFNLEdBQUcsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLE9BQU8sRUFBRSxRQUFRLENBQUMsQ0FBQztZQUN6QywrQ0FBK0M7WUFDL0MsTUFBTSxPQUFPLEdBQUcsSUFBSSxDQUFDLEtBQUssQ0FBQyxJQUFJLENBQzNCLEdBQUcsRUFBRSxJQUFJLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxRQUFRLENBQUMsTUFBTSxDQUFDLENBQUMsQ0FBQyxDQUFDLElBQUksQ0FBQyxPQUFPLENBQUMsUUFBUSxFQUFFLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDO1lBQ3RGLEdBQUcsQ0FBQyxLQUFLLENBQUMsSUFBSSxFQUFFLEdBQUcsQ0FBQyxDQUFDO1lBQ3JCLEdBQUcsQ0FBQyxFQUFFLENBQUMsSUFBSSxFQUFFLE9BQU8sQ0FBQyxDQUFDO1lBQ3RCLHVFQUF1RTtZQUN2RSxzQkFBc0I7WUFDdEIsMERBQTBEO1lBQzFELDZCQUE2QjtZQUM3QixJQUFJLE9BQU8sQ0FBQyxPQUFPLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxFQUFFO2dCQUM5QixNQUFNLFVBQVUsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLEdBQUcsRUFBRSxHQUFHLElBQUksQ0FBQyxRQUFRLENBQUMsT0FBTyxDQUFDLENBQUMsS0FBSyxDQUFDLElBQUksQ0FBQyxDQUFDLENBQUM7Z0JBQ3pFLEdBQUcsQ0FBQyxLQUFLLENBQUMsSUFBSSxFQUFFLElBQUksQ0FBQyxPQUFPLENBQUMsVUFBVSxDQUFDLENBQUMsQ0FBQztnQkFDMUMsR0FBRyxDQUFDLEVBQUUsQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLEdBQUcsRUFBRSxJQUFJLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxDQUFDLEVBQUUsVUFBVSxDQUFDLENBQUM7Z0JBRXhELDhGQUE4RjtnQkFDOUYsSUFBSSxPQUFPLENBQUMsUUFBUSxDQUFDLEtBQUssQ0FBQyxFQUFFO29CQUMzQixHQUFHLENBQUMsS0FBSyxDQUFDLElBQUksRUFBRSxVQUFVLENBQUMsQ0FBQztvQkFDNUIsR0FBRyxDQUFDLEdBQUcsQ0FBQyxJQUFJLEVBQUUsR0FBRyxJQUFJLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxNQUFNLEVBQUUsR0FBRyxJQUFJLENBQUMsUUFBUSxDQUFDLFVBQVUsQ0FBQyxNQUFNLEVBQUUsVUFBVSxDQUFDLENBQUM7aUJBQzdGO2FBQ0Y7UUFDSCxDQUFDO1FBRUQ7Ozs7Ozs7V0FPRztRQUNILFNBQVMsZ0JBQWdCLENBQ3JCLFdBQW1CLEVBQUUsYUFBc0MsRUFDM0Qsc0JBQStCO1lBQ2pDLE1BQU0sV0FBVyxHQUFHLGFBQWEsQ0FBQyxNQUFNLENBQUMsQ0FBQztZQUMxQyxNQUFNLFVBQVUsR0FBRyxlQUFlLENBQUMsV0FBVyxDQUFDLENBQUM7WUFFaEQscUVBQXFFO1lBQ3JFLHdFQUF3RTtZQUN4RSxvRUFBb0U7WUFDcEUsSUFBSSxDQUFDLFVBQVUsRUFBRTtnQkFDZixzRUFBc0U7Z0JBQ3RFLG1FQUFtRTtnQkFDbkUsb0RBQW9EO2dCQUNwRCwwRUFBMEU7Z0JBQzFFLGtFQUFrRTtnQkFDbEUseURBQXlEO2dCQUN6RCxPQUFPLENBQUMsS0FBSyxDQUFDLHlDQUF5QyxFQUFFLFdBQVcsQ0FBQyxDQUFDO2dCQUN0RSxPQUFPLENBQUMsS0FBSyxDQUFDLHNEQUFzRCxDQUFDLENBQUM7Z0JBQ3RFLE9BQU8sQ0FBQyxLQUFLLENBQ1Qsa0ZBQWtGLENBQUMsQ0FBQztnQkFDeEYsT0FBTyxJQUFJLENBQUMsU0FBUyxDQUFDLGFBQWEsRUFBRSxJQUFJLEVBQUUsQ0FBQyxDQUFDLENBQUM7YUFDL0M7WUFFRCx5RkFBeUY7WUFDekYsa0ZBQWtGO1lBQ2xGLGdGQUFnRjtZQUNoRixJQUFJLFVBQVUsQ0FBQyxZQUFZLElBQUksQ0FBQyxzQkFBc0I7Z0JBQ2xELDJCQUEyQixDQUFDLGFBQWEsQ0FBQyxFQUFFO2dCQUM5QyxPQUFPLENBQUMsS0FBSyxDQUFDLDBFQUEwRSxDQUFDLENBQUM7Z0JBQzFGLE9BQU8sQ0FBQyxLQUFLLENBQ1Qsb0VBQW9FO29CQUNwRSw0QkFBNEIsQ0FBQyxDQUFDO2dCQUNsQyxPQUFPLENBQUMsS0FBSyxDQUFDLHVFQUF1RSxDQUFDLENBQUM7Z0JBQ3ZGLE9BQU8sSUFBSSxDQUFDLFNBQVMsQ0FBQyxhQUFhLEVBQUUsSUFBSSxFQUFFLENBQUMsQ0FBQyxDQUFDO2FBQy9DO1lBRUQsd0VBQXdFO1lBQ3hFLGtGQUFrRjtZQUNsRiw2REFBNkQ7WUFDN0QsYUFBYSxDQUFDLE1BQU0sQ0FBQyxHQUFHLGFBQWEsQ0FBQyxXQUFXLEVBQUUsU0FBUyxDQUFDLENBQUM7WUFDOUQsYUFBYSxDQUFDLFVBQVUsQ0FBQyxHQUFHLGFBQWEsQ0FBQyxXQUFXLEVBQUUsVUFBVSxDQUFDLENBQUM7WUFFbkUsYUFBYSxDQUFDLFNBQVMsQ0FBQyxHQUFHLGNBQWMsQ0FBQyxXQUFXLEVBQUUsVUFBVSxDQUFDLGVBQWUsQ0FBQyxDQUFDLENBQUM7WUFDcEYsYUFBYSxDQUFDLFNBQVMsQ0FBQyxHQUFHLGNBQWMsQ0FBQyxXQUFXLEVBQUUsVUFBVSxDQUFDLFNBQVMsQ0FBQyxDQUFDLENBQUM7WUFFOUUsbUZBQW1GO1lBQ25GLDhEQUE4RDtZQUM5RCxhQUFhLENBQUMsUUFBUSxDQUFDLEdBQUcsYUFBYSxDQUFDLFVBQVUsQ0FBQyxDQUFDO1lBQ3BELGFBQWEsQ0FBQyxRQUFRLENBQUMsR0FBRyxhQUFhLENBQUMsVUFBVSxDQUFDLENBQUM7WUFFcEQsT0FBTyxJQUFJLENBQUMsU0FBUyxDQUFDLGFBQWEsRUFBRSxJQUFJLEVBQUUsQ0FBQyxDQUFDLENBQUM7UUFDaEQsQ0FBQztRQUVELGdGQUFnRjtRQUNoRixzRUFBc0U7UUFDdEUsU0FBUyxhQUFhLENBQUMsV0FBbUIsRUFBRSxHQUFXO1lBQ3JELE1BQU0sS0FBSyxHQUFHLFdBQVcsQ0FBQyxLQUFLLENBQUMsR0FBRyxDQUFDLENBQUM7WUFDckMsMkRBQTJEO1lBQzNELE1BQU0sU0FBUyxHQUFHLFdBQVcsQ0FBQyxVQUFVLENBQUMsR0FBRyxDQUFDLENBQUMsQ0FBQyxDQUFDLEtBQUssQ0FBQyxNQUFNLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEtBQUssQ0FBQztZQUN4RSxNQUFNLFlBQVksR0FBRyxRQUFRLENBQUMsU0FBUyxDQUFDLE1BQU0sR0FBRyxDQUFDLEVBQUUsSUFBSSxDQUFDLENBQUMsSUFBSSxDQUFDLEdBQUcsQ0FBQyxJQUFJLEdBQUcsQ0FBQztZQUMzRSxJQUFJLFFBQWdCLENBQUM7WUFDckIsSUFBSSxHQUFHLEtBQUssU0FBUyxFQUFFO2dCQUNyQixRQUFRLEdBQUcsU0FBUyxDQUFDLElBQUksQ0FBQyxHQUFHLENBQUMsR0FBRyxNQUFNLENBQUM7YUFDekM7aUJBQU0sSUFBSSxTQUFTLENBQUMsTUFBTSxLQUFLLENBQUMsRUFBRTtnQkFDakMsUUFBUSxHQUFHLFNBQVMsQ0FBQyxDQUFDLENBQUMsQ0FBQzthQUN6QjtpQkFBTTtnQkFDTCxRQUFRLEdBQUcsU0FBUyxDQUFDLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQyxJQUFJLENBQUMsR0FBRyxDQUFDLENBQUM7YUFDekM7WUFDRCxPQUFPLENBQUMsWUFBWSxFQUFFLEdBQUcsRUFBRSxRQUFRLEdBQUcsS0FBSyxDQUFDLENBQUMsSUFBSSxDQUFDLEdBQUcsQ0FBQyxDQUFDO1FBQ3pELENBQUM7UUFFRCxzRkFBc0Y7UUFDdEYsU0FBUywyQkFBMkIsQ0FBQyxhQUFzQztZQUN6RSxPQUFPLE1BQU0sQ0FBQyxJQUFJLENBQUMsYUFBYSxDQUFDO2lCQUM1QixJQUFJLENBQUMsWUFBWSxDQUFDLEVBQUUsQ0FBQyw0QkFBNEIsQ0FBQyxRQUFRLENBQUMsWUFBWSxDQUFDLENBQUMsQ0FBQztRQUNqRixDQUFDO1FBRUQsbUVBQW1FO1FBQ25FLFNBQVMsMEJBQTBCLENBQy9CLGNBQXNCLEVBQUUsWUFBb0IsRUFBRSxXQUFtQjtZQUNuRSxNQUFNLFNBQVMsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLE1BQU0sRUFBRSxHQUFHLGNBQWMsZ0JBQWdCLENBQUMsQ0FBQztZQUN2RSxzQkFBc0IsQ0FBQyxTQUFTLEVBQUUsSUFBSSxDQUFDLFNBQVMsQ0FBQztnQkFDL0MsWUFBWSxFQUFFLFFBQVE7Z0JBQ3RCLFNBQVMsRUFBRSxDQUFDO2dCQUNaLFVBQVUsRUFBRSxFQUFFO2dCQUNkLFNBQVMsRUFDTCxDQUFDLEVBQUMsTUFBTSxFQUFFLEdBQUcsY0FBYyxDQUFDLFNBQVMsRUFBRSxZQUFZLENBQUMsT0FBTyxDQUFDLGlCQUFpQixFQUFFLEVBQUUsQ0FBQyxDQUFDLEVBQUUsRUFBQyxDQUFDO2dCQUMzRix5QkFBeUIsRUFBRSxJQUFJO2dCQUMvQixVQUFVLEVBQUUsV0FBVzthQUN4QixDQUFDLEdBQUcsSUFBSSxDQUFDLENBQUM7UUFDYixDQUFDO1FBRUQ7OztXQUdHO1FBQ0gsU0FBUyx5QkFBeUIsQ0FBQyxjQUFzQixFQUFFLE9BQWUsRUFBRSxXQUFtQjtZQUM3RixNQUFNLFNBQVMsR0FBRyxJQUFJLENBQUMsSUFBSSxDQUFDLE1BQU0sRUFBRSxHQUFHLGNBQWMsT0FBTyxDQUFDLENBQUM7WUFDOUQsTUFBTSxPQUFPLEdBQUcsR0FBRyxPQUFPO2lCQUNiLGNBQWMsQ0FBQyxTQUFTLEVBQUUsV0FBVyxDQUFDLE9BQU8sQ0FBQyxZQUFZLEVBQUUsRUFBRSxDQUFDLENBQUM7Q0FDaEYsQ0FBQztZQUNFLHNCQUFzQixDQUFDLFNBQVMsRUFBRSxPQUFPLENBQUMsQ0FBQztRQUM3QyxDQUFDO1FBRUQ7Ozs7O1dBS0c7UUFDSCxTQUFTLDJCQUEyQixDQUFDLEdBQVcsRUFBRSxxQkFBNkI7WUFDN0UsTUFBTSxPQUFPLEdBQUcsSUFBSSxDQUFDLElBQUksQ0FBQyxNQUFNLEVBQUUsR0FBRyxFQUFFLGNBQWMsQ0FBQyxDQUFDO1lBQ3ZELE1BQU0sT0FBTyxHQUFHLGdCQUFnQixDQUFDLE9BQU8sRUFBRSxFQUFDLElBQUksRUFBRSxxQkFBcUIsRUFBQyxFQUFFLElBQUksQ0FBQyxDQUFDO1lBQy9FLHNCQUFzQixDQUFDLE9BQU8sRUFBRSxPQUFPLENBQUMsQ0FBQztRQUMzQyxDQUFDO1FBRUQ7OztXQUdHO1FBQ0gsU0FBUyxtQkFBbUIsQ0FBQyxJQUFZO1lBQ3ZDLE9BQU8sSUFBSSxDQUFDLE9BQU8sQ0FBQyxLQUFLLEVBQUUsR0FBRyxDQUFDLENBQUM7UUFDbEMsQ0FBQztRQUVEOzs7OztXQUtHO1FBQ0gsU0FBUyxjQUFjLENBQUMsWUFBb0IsRUFBRSxXQUFtQjtZQUMvRCxNQUFNLFFBQVEsR0FBRyxJQUFJLENBQUMsS0FBSyxDQUFDLEVBQUUsQ0FBQyxZQUFZLENBQUMsWUFBWSxFQUFFLE9BQU8sQ0FBQyxDQUF5QixDQUFDO1lBRTVGLElBQUksbUJBQW1CLEdBQ25CLG1CQUFtQixDQUFDLElBQUksQ0FBQyxRQUFRLENBQUMsSUFBSSxDQUFDLE9BQU8sQ0FBQyxZQUFZLENBQUMsRUFBRSxXQUFXLENBQUMsQ0FBQyxDQUFDO1lBQ2hGLElBQUksQ0FBQyxtQkFBbUIsQ0FBQyxVQUFVLENBQUMsSUFBSSxDQUFDLEVBQUU7Z0JBQ3pDLG1CQUFtQixHQUFHLEtBQUssbUJBQW1CLEVBQUUsQ0FBQzthQUNsRDtZQUVELG1CQUFtQixHQUFHLG1CQUFtQixDQUFDLE9BQU8sQ0FBQyxPQUFPLEVBQUUsRUFBRSxDQUFDLENBQUM7WUFFL0Qsc0RBQXNEO1lBQ3RELCtDQUErQztZQUMvQyxNQUFNLGlCQUFpQixHQUFHLHNCQUFzQixDQUFDO1lBQ2pELElBQUksUUFBUSxDQUFDLE9BQU8sRUFBRTtnQkFDcEIsaURBQWlEO2dCQUNqRCxRQUFRLENBQUMsT0FBTztvQkFDWixRQUFRLENBQUMsT0FBTyxDQUFDLE1BQU0sQ0FBQyxDQUFDLENBQWlCLEVBQUUsRUFBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLElBQUksQ0FBQyxLQUFLLENBQUMsaUJBQWlCLENBQUMsQ0FBQyxDQUFDO2FBQ3RGO1lBQ0QsT0FBTyxJQUFJLENBQUMsU0FBUyxDQUFDLFFBQVEsQ0FBQyxDQUFDLE9BQU8sQ0FBQyxpQkFBaUIsRUFBRSxtQkFBbUIsQ0FBQyxDQUFDO1FBQ2xGLENBQUM7UUFFRDs7O1dBR0c7UUFDSCxTQUFTLDRCQUE0QixDQUFDLFFBQWdCO1lBQ3BELE9BQU8sRUFBRTtpQkFDSixZQUFZLENBQUMsUUFBUSxFQUFFLE9BQU8sQ0FBQztnQkFDaEMsb0VBQW9FO2lCQUNuRSxPQUFPLENBQUMseUNBQXlDLEVBQUUsRUFBRSxDQUFDLENBQUM7UUFDOUQsQ0FBQztJQUNILENBQUM7SUFFRCxJQUFJLE9BQU8sQ0FBQyxJQUFJLEtBQUssTUFBTSxFQUFFO1FBQzNCLE9BQU8sQ0FBQyxRQUFRLEdBQUcsSUFBSSxDQUFDLE9BQU8sQ0FBQyxJQUFJLENBQUMsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7S0FDaEQ7SUFJRCxTQUFnQixRQUFRLENBQUksSUFBWSxFQUFFLEtBQVM7UUFDakQsTUFBTSxJQUFJLEdBQVEsRUFBRSxDQUFDO1FBQ3JCLEtBQUssSUFBSSxDQUFDLEdBQUcsQ0FBQyxFQUFFLENBQUMsR0FBRyxJQUFJLEVBQUUsQ0FBQyxFQUFFLEVBQUU7WUFDN0IsSUFBSSxDQUFDLElBQUksQ0FBQyxLQUFNLENBQUMsQ0FBQztTQUNuQjtRQUNELE9BQU8sSUFBSSxDQUFDO0lBQ2QsQ0FBQztJQU5ELDRCQU1DIiwic291cmNlc0NvbnRlbnQiOlsiLyoqXG4gKiBAbGljZW5zZVxuICogQ29weXJpZ2h0IEdvb2dsZSBMTEMgQWxsIFJpZ2h0cyBSZXNlcnZlZC5cbiAqXG4gKiBVc2Ugb2YgdGhpcyBzb3VyY2UgY29kZSBpcyBnb3Zlcm5lZCBieSBhbiBNSVQtc3R5bGUgbGljZW5zZSB0aGF0IGNhbiBiZVxuICogZm91bmQgaW4gdGhlIExJQ0VOU0UgZmlsZSBhdCBodHRwczovL2FuZ3VsYXIuaW8vbGljZW5zZVxuICovXG5cbmltcG9ydCAqIGFzIGZzIGZyb20gJ2ZzJztcbmltcG9ydCAqIGFzIHBhdGggZnJvbSAncGF0aCc7XG5pbXBvcnQgKiBhcyBzaHggZnJvbSAnc2hlbGxqcyc7XG5cbmZ1bmN0aW9uIG1haW4oYXJnczogc3RyaW5nW10pOiBudW1iZXIge1xuICAvLyBFeGl0IGltbWVkaWF0ZWx5IHdoZW4gZW5jb3VudGVyaW5nIGFuIGVycm9yLlxuICBzaHguc2V0KCctZScpO1xuXG4gIC8vIEtlZXAgdHJhY2sgb2Ygd2hldGhlciBhbiBlcnJvciBoYXMgb2NjdXJlZCBzbyB0aGF0IHdlIGNhbiByZXR1cm4gYW4gYXBwcm9wcmlhdGUgZXhpdCBjb2RlLlxuICBsZXQgZXJyb3JIYXNPY2N1cmVkID0gZmFsc2U7XG5cbiAgLy8gVGhpcyB1dGlsaXR5IGV4cGVjdHMgYWxsIG9mIGl0cyBhcmd1bWVudHMgdG8gYmUgc3BlY2lmaWVkIGluIGEgcGFyYW1zIGZpbGUgZ2VuZXJhdGVkIGJ5XG4gIC8vIGJhemVsIChzZWUgaHR0cHM6Ly9kb2NzLmJhemVsLmJ1aWxkL3ZlcnNpb25zL21hc3Rlci9za3lsYXJrL2xpYi9BcmdzLmh0bWwjdXNlX3BhcmFtX2ZpbGUpLlxuICBjb25zdCBwYXJhbUZpbGVQYXRoID0gYXJnc1swXTtcblxuICAvLyBCYXplbCBwYXJhbXMgbWF5IGJlIHN1cnJvdW5kZWQgd2l0aCBxdW90ZXNcbiAgZnVuY3Rpb24gdW5xdW90ZVBhcmFtZXRlcihzOiBzdHJpbmcpIHtcbiAgICByZXR1cm4gcy5yZXBsYWNlKC9eJyguKiknJC8sICckMScpO1xuICB9XG5cbiAgLy8gUGFyYW1ldGVycyBhcmUgc3BlY2lmaWVkIGluIHRoZSBmaWxlIG9uZSBwZXIgbGluZS5cbiAgY29uc3QgcGFyYW1zID0gZnMucmVhZEZpbGVTeW5jKHBhcmFtRmlsZVBhdGgsICd1dGYtOCcpLnNwbGl0KCdcXG4nKS5tYXAodW5xdW90ZVBhcmFtZXRlcik7XG5cbiAgY29uc3QgW1xuICAgICAgLy8gT3V0cHV0IGRpcmVjdG9yeSBmb3IgdGhlIG5wbSBwYWNrYWdlLlxuICAgICAgb3V0LFxuXG4gICAgICAvLyBUaGUgcGFja2FnZSBzZWdtZW50IG9mIHRoZSBuZ19wYWNrYWdlIHJ1bGUncyBsYWJlbCAoZS5nLiAncGFja2FnZS9jb21tb24nKS5cbiAgICAgIHNyY0RpcixcblxuICAgICAgLy8gVGhlIGJhemVsLWJpbiBkaXIgam9pbmVkIHdpdGggdGhlIHNyY0RpciAoZS5nLiAnYmF6ZWwtYmluL3BhY2thZ2UuY29tbW9uJykuXG4gICAgICAvLyBUaGlzIGlzIHRoZSBpbnRlbmRlZCBvdXRwdXQgbG9jYXRpb24gZm9yIHBhY2thZ2UgYXJ0aWZhY3RzLlxuICAgICAgYmluRGlyLFxuXG4gICAgICAvLyBUaGUgYmF6ZWwtZ2VuZmlsZXMgZGlyIGpvaW5lZCB3aXRoIHRoZSBzcmNEaXIgKGUuZy4gJ2JhemVsLWJpbi9wYWNrYWdlLmNvbW1vbicpLlxuICAgICAgZ2VuZmlsZXNEaXIsXG5cbiAgICAgIC8vIEpTT04gZGF0YSBtYXBwaW5nIGVhY2ggZW50cnkgcG9pbnQgdG8gdGhlIGdlbmVyYXRlZCBidW5kbGUgaW5kZXggYW5kXG4gICAgICAvLyBmbGF0IG1vZHVsZSBtZXRhZGF0YSwgZm9yIGV4YW1wbGVcbiAgICAgIC8vIHtcIkBhbmd1bGFyL2NvcmVcIjoge1xuICAgICAgLy8gICAgIFwiaW5kZXhcIjogXCJiYXplbC1iaW4vcGFja2FnZXMvY29yZS9jb3JlLmpzXCIsXG4gICAgICAvLyAgICAgXCJ0eXBpbmdzXCI6IFwiYmF6ZWwtYmluL3BhY2thZ2VzL2NvcmUvY29yZS5kLnRzXCIsXG4gICAgICAvLyAgICAgXCJtZXRhZGF0YVwiOiBcImJhemVsLWJpbi9wYWNrYWdlcy9jb3JlL2NvcmUubWV0YWRhdGEuanNvblwiXG4gICAgICAvLyAgfSxcbiAgICAgIC8vIC4uLlxuICAgICAgLy8gfVxuICAgICAgbW9kdWxlc01hbmlmZXN0QXJnLFxuXG4gICAgICAvLyBQYXRoIHRvIHRoZSBwYWNrYWdlJ3MgUkVBRE1FLm1kLlxuICAgICAgcmVhZG1lTWQsXG5cbiAgICAgIC8vIExpc3Qgb2Ygcm9sbGVkLXVwIGZsYXQgRVMyMDE1IG1vZHVsZXNcbiAgICAgIGZlc20yMDE1QXJnLFxuXG4gICAgICAvLyBMaXN0IG9mIGluZGl2aWR1YWwgRVMyMDE1IG1vZHVsZXNcbiAgICAgIGVzbTIwMTVBcmcsXG5cbiAgICAgIC8vIExpc3Qgb2YgYWxsIFVNRCBidW5kbGVzIGdlbmVyYXRlZCBieSByb2xsdXAuXG4gICAgICBidW5kbGVzQXJnLFxuXG4gICAgICAvLyBMaXN0IG9mIGFsbCBmaWxlcyBpbiB0aGUgbmdfcGFja2FnZSBydWxlJ3Mgc3Jjcy5cbiAgICAgIHNyY3NBcmcsXG5cbiAgICAgIC8vIExpc3Qgb2YgYWxsIHR5cGUgZGVmaW5pdGlvbnMgdGhhdCBuZWVkIHRvIHBhY2thZ2VkIGludG8gdGhlIG5nX3BhY2thZ2UuXG4gICAgICB0eXBlRGVmaW5pdGlvbnNBcmcsXG5cbiAgICAgIC8vIExpc3Qgb2YgYWxsIGZpbGVzIGluIHRoZSBuZ19wYWNrYWdlIHJ1bGUncyBkYXRhLlxuICAgICAgZGF0YUFyZyxcblxuICAgICAgLy8gUGF0aCB0byB0aGUgcGFja2FnZSdzIExJQ0VOU0UuXG4gICAgICBsaWNlbnNlRmlsZSxcblxuICAgICAgLy8gTGlzdCBvZiBhbGwgZHRzIGJ1bmRsZXMgZ2VuZXJhdGVkIGJ5IHRoZSBBUEkgZXh0cmFjdG9yLlxuICAgICAgZHRzQnVuZGxlQXJnLFxuXG4gICAgICAvLyBUaGUgZHRzIGJ1bmRsZSBmaWxlIHN1ZmZpeCBleGFtcGxlOiAnLmJ1bmRsZS5kLnRzJ1xuICAgICAgZHRzQnVuZGxlRmlsZVN1ZmZpeCxcbiAgXSA9IHBhcmFtcztcblxuICBjb25zdCBmZXNtMjAxNSA9IGZlc20yMDE1QXJnLnNwbGl0KCcsJykuZmlsdGVyKHMgPT4gISFzKTtcbiAgY29uc3QgZXNtMjAxNSA9IGVzbTIwMTVBcmcuc3BsaXQoJywnKS5maWx0ZXIocyA9PiAhIXMpO1xuICBjb25zdCBidW5kbGVzID0gYnVuZGxlc0FyZy5zcGxpdCgnLCcpLmZpbHRlcihzID0+ICEhcyk7XG4gIGNvbnN0IHR5cGVEZWZpbml0aW9ucyA9IHR5cGVEZWZpbml0aW9uc0FyZy5zcGxpdCgnLCcpLmZpbHRlcihzID0+ICEhcyk7XG4gIGNvbnN0IHNyY3MgPSBzcmNzQXJnLnNwbGl0KCcsJykuZmlsdGVyKHMgPT4gISFzKTtcbiAgY29uc3QgZGF0YUZpbGVzOiBzdHJpbmdbXSA9IGRhdGFBcmcuc3BsaXQoJywnKS5maWx0ZXIocyA9PiAhIXMpO1xuICBjb25zdCBtb2R1bGVzTWFuaWZlc3QgPSBKU09OLnBhcnNlKG1vZHVsZXNNYW5pZmVzdEFyZykgYXMge1trZXk6IHN0cmluZ106IGFueX07XG4gIGNvbnN0IGR0c0J1bmRsZXM6IHN0cmluZ1tdID0gZHRzQnVuZGxlQXJnLnNwbGl0KCcsJykuZmlsdGVyKHMgPT4gISFzKTtcblxuICAvKipcbiAgICogTGlzdCBvZiBrbm93biBgcGFja2FnZS5qc29uYCBmaWVsZHMgd2hpY2ggcHJvdmlkZSBpbmZvcm1hdGlvbiBhYm91dFxuICAgKiBzdXBwb3J0ZWQgcGFja2FnZSBmb3JtYXRzIGFuZCB0aGVpciBhc3NvY2lhdGVkIGVudHJ5IHBhdGhzLlxuICAgKi9cbiAgY29uc3Qga25vd25Gb3JtYXRQYWNrYWdlSnNvbkZpZWxkcyA9XG4gICAgICBbJ21haW4nLCAnZmVzbTIwMTUnLCAnZXNtMjAxNScsICd0eXBpbmdzJywgJ21vZHVsZScsICdlczIwMTUnXTtcblxuICBpZiAocmVhZG1lTWQpIHtcbiAgICBjb3B5RmlsZShyZWFkbWVNZCwgb3V0KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBXcml0ZXMgYSBmaWxlIGludG8gdGhlIHBhY2thZ2UgYmFzZWQgb24gaXRzIGlucHV0IHBhdGgsIHJlbGF0aXZpemluZyB0byB0aGUgcGFja2FnZSBwYXRoLlxuICAgKiBAcGFyYW0gaW5wdXRQYXRoIFBhdGggdG8gdGhlIGZpbGUgaW4gdGhlIGlucHV0IHRyZWUuXG4gICAqIEBwYXJhbSBmaWxlQ29udGVudCBDb250ZW50IG9mIHRoZSBmaWxlLlxuICAgKi9cbiAgZnVuY3Rpb24gd3JpdGVGaWxlRnJvbUlucHV0UGF0aChpbnB1dFBhdGg6IHN0cmluZywgZmlsZUNvbnRlbnQ6IHN0cmluZ3xCdWZmZXIpIHtcbiAgICAvLyBXZSB3YW50IHRoZSByZWxhdGl2ZSBwYXRoIGZyb20gdGhlIGdpdmVuIGZpbGUgdG8gaXRzIGFuY2VzdG9yIFwicm9vdFwiIGRpcmVjdG9yeS5cbiAgICAvLyBUaGlzIHJvb3QgZGVwZW5kcyBvbiB3aGV0aGVyIHRoZSBmaWxlIGxpdmVzIGluIHRoZSBzb3VyY2UgdHJlZSAoc3JjRGlyKSBhcyBhIGJhc2ljIGZpbGVcbiAgICAvLyBpbnB1dCB0byBuZ19wYWNrYWdlLCB0aGUgYmluIG91dHB1dCB0cmVlIChiaW5EaXIpIGFzIHRoZSBvdXRwdXQgb2YgYW5vdGhlciBydWxlLCBvclxuICAgIC8vIHRoZSBnZW5maWxlcyBvdXRwdXQgdHJlZSAoZ2VuZmlsZXNEaXIpIGFzIHRoZSBvdXRwdXQgb2YgYSBnZW5ydWxlLlxuICAgIGxldCByb290RGlyOiBzdHJpbmc7XG4gICAgaWYgKGlucHV0UGF0aC5pbmNsdWRlcyhiaW5EaXIpKSB7XG4gICAgICByb290RGlyID0gYmluRGlyO1xuICAgIH0gZWxzZSBpZiAoaW5wdXRQYXRoLmluY2x1ZGVzKGdlbmZpbGVzRGlyKSkge1xuICAgICAgcm9vdERpciA9IGdlbmZpbGVzRGlyO1xuICAgIH0gZWxzZSB7XG4gICAgICByb290RGlyID0gc3JjRGlyO1xuICAgIH1cblxuICAgIGNvbnN0IG91dHB1dFBhdGggPSBwYXRoLmpvaW4ob3V0LCBwYXRoLnJlbGF0aXZlKHJvb3REaXIsIGlucHV0UGF0aCkpO1xuXG4gICAgLy8gQWx3YXlzIGVuc3VyZSB0aGF0IHRoZSB0YXJnZXQgZGlyZWN0b3J5IGV4aXN0cy5cbiAgICBzaHgubWtkaXIoJy1wJywgcGF0aC5kaXJuYW1lKG91dHB1dFBhdGgpKTtcbiAgICBmcy53cml0ZUZpbGVTeW5jKG91dHB1dFBhdGgsIGZpbGVDb250ZW50KTtcbiAgfVxuXG4gIC8qKlxuICAgKiBDb3BpZXMgYSBmaWxlIGludG8gdGhlIHBhY2thZ2UgYmFzZWQgb24gaXRzIGlucHV0IHBhdGgsIHJlbGF0aXZpemluZyB0byB0aGUgcGFja2FnZSBwYXRoLlxuICAgKiBAcGFyYW0gaW5wdXRQYXRoIGEgcGF0aCByZWxhdGl2ZSB0byB0aGUgYmluRGlyLCB0eXBpY2FsbHkgZnJvbSBhIGZpbGUgaW4gdGhlIGRlcHNbXVxuICAgKi9cbiAgZnVuY3Rpb24gY29weUZpbGVGcm9tSW5wdXRQYXRoKGlucHV0UGF0aDogc3RyaW5nKSB7XG4gICAgd3JpdGVGaWxlRnJvbUlucHV0UGF0aChpbnB1dFBhdGgsIGZzLnJlYWRGaWxlU3luYyhpbnB1dFBhdGgpKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBSZWxhdGl2aXplIHRoZSBwYXRoIHdoZXJlIGEgZmlsZSBpcyB3cml0dGVuLlxuICAgKiBAcGFyYW0gZmlsZSBhIHBhdGggY29udGFpbmluZyBhIHJlLXJvb3RlZCBzZWdtZW50IGxpa2UgYC5lc20yMDE1YFxuICAgKiBAcGFyYW0gb3V0RGlyIHBhdGggd2hlcmUgd2UgY29weSB0aGUgZmlsZSwgcmVsYXRpdmUgdG8gdGhlIG91dFxuICAgKi9cbiAgZnVuY3Rpb24gd3JpdGVFc21GaWxlKGZpbGU6IHN0cmluZywgb3V0RGlyOiBzdHJpbmcpIHtcbiAgICAvLyBQYXRoIGNvbXB1dGVkIHJlbGF0aXZlIHRvIHRoZSBjdXJyZW50IHBhY2thZ2UgaW4gYmF6ZWwtYmluLiBlLmcuIGEgRVMyMDE1IG91dHB1dCBmaWxlXG4gICAgLy8gaW4gYGJhemVsLW91dC88Li4+L3BhY2thZ2VzL2NvcmUvc3JjL2RpLmpzYCBzaG91bGQgYmUgc3RvcmVkIGluIGB7b3V0X2Rpcn0vc3JjL2RpLmpzYFxuICAgIC8vIGlmIHRoZSBwYWNrYWdlIHRhcmdldCBoYXMgYmVlbiBkZWNsYXJlZCBpbiBgPC4uPi9wYWNrYWdlcy9jb3JlYC5cbiAgICBjb25zdCBwYWNrYWdlUmVsYXRpdmVQYXRoID0gcGF0aC5kaXJuYW1lKHBhdGgucmVsYXRpdmUoYmluRGlyLCBmaWxlKSk7XG4gICAgaWYgKCFwYWNrYWdlUmVsYXRpdmVQYXRoLnN0YXJ0c1dpdGgoJy4uJykpIHtcbiAgICAgIGNvcHlGaWxlKGZpbGUsIHBhdGguam9pbihvdXQsIG91dERpciksIHBhY2thZ2VSZWxhdGl2ZVBhdGgpO1xuICAgIH1cbiAgfVxuXG4gIGVzbTIwMTUuZm9yRWFjaChmaWxlID0+IHdyaXRlRXNtRmlsZShmaWxlLCAnZXNtMjAxNScpKTtcblxuICBidW5kbGVzLmZvckVhY2goYnVuZGxlID0+IHtcbiAgICBjb3B5RmlsZShidW5kbGUsIG91dCwgJ2J1bmRsZXMnKTtcbiAgfSk7XG4gIGZlc20yMDE1LmZvckVhY2goZmlsZSA9PiB7XG4gICAgY29weUZpbGUoZmlsZSwgb3V0LCAnZmVzbTIwMTUnKTtcbiAgfSk7XG5cbiAgLy8gQ29weSBhbGwgdHlwZSBkZWZpbml0aW9ucyBpbnRvIHRoZSBwYWNrYWdlLiBUaGlzIGlzIG5lY2Vzc2FyeSBzbyB0aGF0IGRldmVsb3BlcnMgY2FuIHVzZVxuICAvLyB0aGUgcGFja2FnZSB3aXRoIHR5cGUgZGVmaW5pdGlvbnMuXG4gIHR5cGVEZWZpbml0aW9ucy5mb3JFYWNoKGYgPT4gd3JpdGVGaWxlRnJvbUlucHV0UGF0aChmLCByZWFkVHlwaW5nc0FuZFN0cmlwQW1kTW9kdWxlKGYpKSk7XG5cbiAgLy8gQ29weSBhbGwgYGRhdGFgIGZpbGVzIGludG8gdGhlIHBhY2thZ2UuIFRoZXNlIGFyZSBmaWxlcyB0aGF0IGFyZW4ndCBidWlsdCBieSB0aGUgbmdfcGFja2FnZVxuICAvLyBydWxlLCBidXQgaW5zdGVhZCBhcmUganVzdCBzdHJhaWdodCBjb3BpZWQgaW50byB0aGUgcGFja2FnZSwgZS5nLiBnbG9iYWwgQ1NTIGFzc2V0cy5cbiAgZGF0YUZpbGVzLmZvckVhY2goZiA9PiBjb3B5RmlsZUZyb21JbnB1dFBhdGgoZikpO1xuXG4gIC8vIEl0ZXJhdGUgdGhyb3VnaCB0aGUgZW50cnkgcG9pbnQgbW9kdWxlc1xuICAvLyBXZSBkbyB0aGlzIGZpcnN0IGJlY2F1c2Ugd2UgYWxzbyByZWNvcmQgbmV3IHBhdGhzIGZvciB0aGUgZXNtNSBhbmQgZXNtMjAxNSBjb3BpZXNcbiAgLy8gb2YgdGhlIGluZGV4IEpTIGZpbGUsIHdoaWNoIHdlIG5lZWQgdG8gYW1lbmQgdGhlIHBhY2thZ2UuanNvbi5cbiAgT2JqZWN0LmtleXMobW9kdWxlc01hbmlmZXN0KS5mb3JFYWNoKG1vZHVsZU5hbWUgPT4ge1xuICAgIGNvbnN0IG1vZHVsZUZpbGVzID0gbW9kdWxlc01hbmlmZXN0W21vZHVsZU5hbWVdO1xuICAgIGNvbnN0IHJlbGF0aXZlID0gcGF0aC5yZWxhdGl2ZShiaW5EaXIsIG1vZHVsZUZpbGVzWydpbmRleCddKTtcblxuICAgIG1vZHVsZUZpbGVzWydlc20yMDE1X2luZGV4J10gPSBwYXRoLmpvaW4oYmluRGlyLCAnZXNtMjAxNScsIHJlbGF0aXZlKTtcblxuICAgIC8vIE1ldGFkYXRhIGZpbGUgaXMgb3B0aW9uYWwgYXMgZW50cnktcG9pbnRzIGNhbiBiZSBidWlsdCB3aXRoIHRoZSBgdHNfbGlicmFyeWBcbiAgICAvLyBydWxlIG9yIGBuZ19tb2R1bGVgIHJ1bGUgaW4gSXZ5IG1vZGUuXG4gICAgY29uc3QgbWV0YWRhdGFGaWxlID0gbW9kdWxlRmlsZXNbJ21ldGFkYXRhJ107XG4gICAgaWYgKCFtZXRhZGF0YUZpbGUpIHtcbiAgICAgIHJldHVybjtcbiAgICB9XG5cbiAgICBjb25zdCB0eXBpbmdzT3V0RmlsZSA9IG1vZHVsZUZpbGVzWyd0eXBpbmdzJ107XG4gICAgLy8gV2Ugb25seSBzdXBwb3J0IGFsbCBtb2R1bGVzIHdpdGhpbiBhIHBhY2thZ2UgdG8gYmUgZHRzIGJ1bmRsZWRcbiAgICAvLyBpZTogaWYgQGFuZ3VsYXIvY29tbW9uL2h0dHAgaGFzIGZsYXQgZHRzLCBzbyBzaG91bGQgQGFuZ3VsYXIvY29tbW9uXG4gICAgaWYgKGR0c0J1bmRsZXMubGVuZ3RoKSB7XG4gICAgICBjb25zdCBtZXRhZGF0YUNvbnRlbnQgPSByZXdpcmVNZXRhZGF0YShtZXRhZGF0YUZpbGUsIHR5cGluZ3NPdXRGaWxlKTtcbiAgICAgIHdyaXRlRmlsZUZyb21JbnB1dFBhdGgobWV0YWRhdGFGaWxlLCBtZXRhZGF0YUNvbnRlbnQpO1xuICAgIH0gZWxzZSB7XG4gICAgICBjb3B5RmlsZUZyb21JbnB1dFBhdGgobWV0YWRhdGFGaWxlKTtcbiAgICB9XG4gIH0pO1xuXG4gIGNvbnN0IGxpY2Vuc2VCYW5uZXIgPSBsaWNlbnNlRmlsZSA/IGZzLnJlYWRGaWxlU3luYyhsaWNlbnNlRmlsZSwgJ3V0Zi04JykgOiAnJztcblxuICBkdHNCdW5kbGVzLmZvckVhY2goYnVuZGxlRmlsZSA9PiB7XG4gICAgY29uc3QgY2xlYW5EaXN0UGF0aCA9IGJ1bmRsZUZpbGUucmVwbGFjZShkdHNCdW5kbGVGaWxlU3VmZml4LCAnLmQudHMnKTtcbiAgICAvLyBBUEkgZXh0cmFjdG9yIHdpbGwgbm90IGRlZHVwZSBsaWNlbnNlIGNvbW1lbnRzIGZyb20gdmFyaW91cyBmaWxlc1xuICAgIC8vIHRoaXMgd2lsbCByZW1vdmUgYWxsIHRoZSBsaWNlbnNlIGNvbW1lbnRzIGFuZCBhcHBlbmQgdGhlIGxpY2Vuc2UgYmFubmVyLlxuICAgIGNvbnN0IGNvbnRlbnQgPSBsaWNlbnNlQmFubmVyICsgJ1xcbicgK1xuICAgICAgICByZWFkVHlwaW5nc0FuZFN0cmlwQW1kTW9kdWxlKGJ1bmRsZUZpbGUpXG4gICAgICAgICAgICAucmVwbGFjZSgvKFxcL1xcKlxcKlxccytcXCpcXHNcXEBsaWNlbnNlKCgoPyFcXCpcXC8pLnxcXHMpKilcXCpcXC8pL2dtLCAnJyk7XG5cbiAgICB3cml0ZUZpbGVGcm9tSW5wdXRQYXRoKGNsZWFuRGlzdFBhdGgsIGNvbnRlbnQpO1xuICB9KTtcblxuICAvLyBSb290IHBhY2thZ2UgbmFtZSAoZS5nLiAnQGFuZ3VsYXIvY29tbW9uJyksIGNhcHR1cmVzIGFzIHdlIGl0ZXJhdGUgdGhyb3VnaCBzb3VyY2VzIGJlbG93LlxuICBsZXQgcm9vdFBhY2thZ2VOYW1lID0gJyc7XG4gIGNvbnN0IHBhY2thZ2VzV2l0aEV4aXN0aW5nUGFja2FnZUpzb24gPSBuZXcgU2V0PHN0cmluZz4oKTtcblxuICBmb3IgKGNvbnN0IHNyYyBvZiBzcmNzKSB7XG4gICAgaWYgKHNyYy5pbmNsdWRlcyhiaW5EaXIpIHx8IHNyYy5pbmNsdWRlcyhnZW5maWxlc0RpcikpIHtcbiAgICAgIGVycm9ySGFzT2NjdXJlZCA9IHRydWU7XG4gICAgICBjb25zb2xlLmVycm9yKFxuICAgICAgICAgICdUaGUgXCJzcmNzXCIgZm9yIG5nX3BhY2thZ2Ugc2hvdWxkIG5vdCBpbmNsdWRlIG91dHB1dCBvZiBvdGhlciBydWxlcy4gRm91bmQ6XFxuJyArXG4gICAgICAgICAgYCAgJHtzcmN9YCk7XG4gICAgfVxuXG4gICAgbGV0IGNvbnRlbnQgPSBmcy5yZWFkRmlsZVN5bmMoc3JjLCAndXRmLTgnKTtcbiAgICAvLyBNb2RpZnkgcGFja2FnZS5qc29uIGZpbGVzIGFzIG5lY2Vzc2FyeSBmb3IgcHVibGlzaGluZ1xuICAgIGlmIChwYXRoLmJhc2VuYW1lKHNyYykgPT09ICdwYWNrYWdlLmpzb24nKSB7XG4gICAgICBjb25zdCBwYWNrYWdlSnNvbiA9IEpTT04ucGFyc2UoY29udGVudCkgYXMge1trZXk6IHN0cmluZ106IHN0cmluZ307XG4gICAgICBjb250ZW50ID0gYW1lbmRQYWNrYWdlSnNvbihzcmMsIHBhY2thZ2VKc29uLCBmYWxzZSk7XG5cbiAgICAgIGNvbnN0IHBhY2thZ2VOYW1lID0gcGFja2FnZUpzb25bJ25hbWUnXTtcbiAgICAgIHBhY2thZ2VzV2l0aEV4aXN0aW5nUGFja2FnZUpzb24uYWRkKHBhY2thZ2VOYW1lKTtcblxuICAgICAgLy8gS2VlcCB0cmFjayBvZiB0aGUgcm9vdCBwYWNrYWdlIG5hbWUsIGUuZy4gXCJAYW5ndWxhci9jb21tb25cIi4gV2UgYXNzdW1lIHRoYXQgdGhlXG4gICAgICAvLyByb290IG5hbWUgd2lsbCBiZSBzaG9ydGVzdCBiZWNhdXNlIHNlY29uZGFyeSBlbnRyeS1wb2ludHMgd2lsbCBhcHBlbmQgdG8gaXRcbiAgICAgIC8vIChlLmcuIFwiQGFuZ3VsYXIvY29tbW9uL2h0dHBcIikuXG4gICAgICBpZiAoIXJvb3RQYWNrYWdlTmFtZSB8fCBwYWNrYWdlTmFtZS5sZW5ndGggPCByb290UGFja2FnZU5hbWUubGVuZ3RoKSB7XG4gICAgICAgIHJvb3RQYWNrYWdlTmFtZSA9IHBhY2thZ2VKc29uWyduYW1lJ107XG4gICAgICB9XG4gICAgfVxuICAgIHdyaXRlRmlsZUZyb21JbnB1dFBhdGgoc3JjLCBjb250ZW50KTtcbiAgfVxuXG4gIC8vIEdlbmVyYXRlIGV4dHJhIGZpbGVzIGZvciBzZWNvbmRhcnkgZW50cnktcG9pbnRzLlxuICBPYmplY3Qua2V5cyhtb2R1bGVzTWFuaWZlc3QpLmZvckVhY2goZW50cnlQb2ludFBhY2thZ2VOYW1lID0+IHtcbiAgICBjb25zdCBlbnRyeVBvaW50TmFtZSA9IGVudHJ5UG9pbnRQYWNrYWdlTmFtZS5zdWJzdHIocm9vdFBhY2thZ2VOYW1lLmxlbmd0aCArIDEpO1xuICAgIGlmICghZW50cnlQb2ludE5hbWUpIHJldHVybjtcblxuICAgIGNvbnN0IG1ldGFkYXRhRmlsZVBhdGggPSBtb2R1bGVzTWFuaWZlc3RbZW50cnlQb2ludFBhY2thZ2VOYW1lXVsnbWV0YWRhdGEnXTtcbiAgICBpZiAobWV0YWRhdGFGaWxlUGF0aCkge1xuICAgICAgY3JlYXRlTWV0YWRhdGFSZWV4cG9ydEZpbGUoXG4gICAgICAgICAgZW50cnlQb2ludE5hbWUsIG1vZHVsZXNNYW5pZmVzdFtlbnRyeVBvaW50UGFja2FnZU5hbWVdWydtZXRhZGF0YSddLFxuICAgICAgICAgIGVudHJ5UG9pbnRQYWNrYWdlTmFtZSk7XG4gICAgfVxuXG4gICAgY3JlYXRlVHlwaW5nc1JlZXhwb3J0RmlsZShcbiAgICAgICAgZW50cnlQb2ludE5hbWUsIGxpY2Vuc2VCYW5uZXIsIG1vZHVsZXNNYW5pZmVzdFtlbnRyeVBvaW50UGFja2FnZU5hbWVdWyd0eXBpbmdzJ10pO1xuXG4gICAgaWYgKCFwYWNrYWdlc1dpdGhFeGlzdGluZ1BhY2thZ2VKc29uLmhhcyhlbnRyeVBvaW50UGFja2FnZU5hbWUpKSB7XG4gICAgICBjcmVhdGVFbnRyeVBvaW50UGFja2FnZUpzb24oZW50cnlQb2ludE5hbWUsIGVudHJ5UG9pbnRQYWNrYWdlTmFtZSk7XG4gICAgfVxuICB9KTtcblxuICByZXR1cm4gZXJyb3JIYXNPY2N1cmVkID8gMSA6IDA7XG5cbiAgLyoqXG4gICAqIENvbnZlcnQgYSBiaW5EaXItcmVsYXRpdmUgcGF0aCB0byBzcmNEaXItcmVsYXRpdmVcbiAgICogQHBhcmFtIGZyb20gcGF0aCB0byBhIGZpbGUgdW5kZXIgdGhlIHNyY0RpciwgbGlrZSBwYWNrYWdlcy9jb3JlL3Rlc3RpbmcvcGFja2FnZS5qc29uXG4gICAqIEBwYXJhbSBmaWxlIHBhdGggdG8gYSBmaWxlIHVuZGVyIHRoZSBiaW5EaXIsIGxpa2UgYmF6ZWwtYmluL2NvcmUvdGVzdGluZy9nZW5lcmF0ZWQuanNcbiAgICovXG4gIGZ1bmN0aW9uIHNyY0RpclJlbGF0aXZlKGZyb206IHN0cmluZywgZmlsZTogc3RyaW5nKSB7XG4gICAgY29uc3QgcmVzdWx0ID0gbm9ybWFsaXplU2VwYXJhdG9ycyhcbiAgICAgICAgcGF0aC5yZWxhdGl2ZShwYXRoLmRpcm5hbWUoZnJvbSksIHBhdGguam9pbihzcmNEaXIsIHBhdGgucmVsYXRpdmUoYmluRGlyLCBmaWxlKSkpKTtcbiAgICBpZiAocmVzdWx0LnN0YXJ0c1dpdGgoJy4uJykpIHJldHVybiByZXN1bHQ7XG4gICAgcmV0dXJuIGAuLyR7cmVzdWx0fWA7XG4gIH1cblxuICBmdW5jdGlvbiBjb3B5RmlsZShmaWxlOiBzdHJpbmcsIGJhc2VEaXI6IHN0cmluZywgcmVsYXRpdmUgPSAnLicpIHtcbiAgICBjb25zdCBkaXIgPSBwYXRoLmpvaW4oYmFzZURpciwgcmVsYXRpdmUpO1xuICAgIC8vIG91dHB1dCBmaWxlIGlzIC5qcyBpZiB0aGUgaW5wdXQgZmlsZSBpcyAubWpzXG4gICAgY29uc3Qgb3V0RmlsZSA9IHBhdGgucG9zaXguam9pbihcbiAgICAgICAgZGlyLCBwYXRoLmJhc2VuYW1lKGZpbGUuZW5kc1dpdGgoJy5tanMnKSA/IGZpbGUucmVwbGFjZSgvXFwubWpzJC8sICcuanMnKSA6IGZpbGUpKTtcbiAgICBzaHgubWtkaXIoJy1wJywgZGlyKTtcbiAgICBzaHguY3AoZmlsZSwgb3V0RmlsZSk7XG4gICAgLy8gRG91YmxlLXVuZGVyc2NvcmUgaXMgdXNlZCB0byBlc2NhcGUgZm9yd2FyZCBzbGFzaCBpbiBGRVNNIGZpbGVuYW1lcy5cbiAgICAvLyBTZWUgbmdfcGFja2FnZS5iemw6XG4gICAgLy8gICBmZXNtX291dHB1dF9maWxlbmFtZSA9IGVudHJ5X3BvaW50LnJlcGxhY2UoXCIvXCIsIFwiX19cIilcbiAgICAvLyBXZSBuZWVkIHRvIHVuZXNjYXBlIHRoZXNlLlxuICAgIGlmIChvdXRGaWxlLmluZGV4T2YoJ19fJykgPj0gMCkge1xuICAgICAgY29uc3Qgb3V0cHV0UGF0aCA9IHBhdGguam9pbihkaXIsIC4uLnBhdGguYmFzZW5hbWUob3V0RmlsZSkuc3BsaXQoJ19fJykpO1xuICAgICAgc2h4Lm1rZGlyKCctcCcsIHBhdGguZGlybmFtZShvdXRwdXRQYXRoKSk7XG4gICAgICBzaHgubXYocGF0aC5qb2luKGRpciwgcGF0aC5iYXNlbmFtZShmaWxlKSksIG91dHB1dFBhdGgpO1xuXG4gICAgICAvLyBpZiB3ZSBhcmUgcmVuYW1pbmcgdGhlIC5qcyBmaWxlLCB3ZSdsbCBhbHNvIG5lZWQgdG8gdXBkYXRlIHRoZSBzb3VyY2VNYXBwaW5nVVJMIGluIHRoZSBmaWxlXG4gICAgICBpZiAob3V0RmlsZS5lbmRzV2l0aCgnLmpzJykpIHtcbiAgICAgICAgc2h4LmNobW9kKCcrdycsIG91dHB1dFBhdGgpO1xuICAgICAgICBzaHguc2VkKCctaScsIGAke3BhdGguYmFzZW5hbWUoZmlsZSl9Lm1hcGAsIGAke3BhdGguYmFzZW5hbWUob3V0cHV0UGF0aCl9Lm1hcGAsIG91dHB1dFBhdGgpO1xuICAgICAgfVxuICAgIH1cbiAgfVxuXG4gIC8qKlxuICAgKiBJbnNlcnRzIG9yIGVkaXRzIHByb3BlcnRpZXMgaW50byB0aGUgcGFja2FnZS5qc29uIGZpbGUocykgaW4gdGhlIHBhY2thZ2Ugc28gdGhhdFxuICAgKiB0aGV5IHBvaW50IHRvIGFsbCB0aGUgcmlnaHQgZ2VuZXJhdGVkIGFydGlmYWN0cy5cbiAgICpcbiAgICogQHBhcmFtIHBhY2thZ2VKc29uIFRoZSBwYXRoIHRvIHRoZSBwYWNrYWdlLmpzb24gZmlsZS5cbiAgICogQHBhcmFtIHBhcnNlZFBhY2thZ2UgUGFyc2VkIHBhY2thZ2UuanNvbiBjb250ZW50XG4gICAqIEBwYXJhbSBpc0dlbmVyYXRlZFBhY2thZ2VKc29uIFdoZXRoZXIgdGhlIHBhc3NlZCBwYWNrYWdlLmpzb24gaGFzIGJlZW4gZ2VuZXJhdGVkLlxuICAgKi9cbiAgZnVuY3Rpb24gYW1lbmRQYWNrYWdlSnNvbihcbiAgICAgIHBhY2thZ2VKc29uOiBzdHJpbmcsIHBhcnNlZFBhY2thZ2U6IHtba2V5OiBzdHJpbmddOiBzdHJpbmd9LFxuICAgICAgaXNHZW5lcmF0ZWRQYWNrYWdlSnNvbjogYm9vbGVhbikge1xuICAgIGNvbnN0IHBhY2thZ2VOYW1lID0gcGFyc2VkUGFja2FnZVsnbmFtZSddO1xuICAgIGNvbnN0IG1vZHVsZURhdGEgPSBtb2R1bGVzTWFuaWZlc3RbcGFja2FnZU5hbWVdO1xuXG4gICAgLy8gSWYgYSBwYWNrYWdlIGpzb24gZmlsZSBoYXMgYmVlbiBkaXNjb3ZlcmVkIHRoYXQgZG9lcyBub3QgbWF0Y2ggYW55XG4gICAgLy8gbW9kdWxlIGluIHRoZSBtYW5pZmVzdCwgd2UgcmVwb3J0IGEgd2FybmluZyBhcyBtb3N0IGxpa2VseSB0aGUgdGFyZ2V0XG4gICAgLy8gaXMgY29uZmlndXJlZCBpbmNvcnJlY3RseSAoZS5nLiBtaXNzaW5nIGBtb2R1bGVfbmFtZWAgYXR0cmlidXRlKS5cbiAgICBpZiAoIW1vZHVsZURhdGEpIHtcbiAgICAgIC8vIElkZWFsbHkgd2Ugc2hvdWxkIHRocm93IGhlcmUsIGFzIHdlIGdvdCBhbiBlbnRyeSBwb2ludCB0aGF0IGRvZXNuJ3RcbiAgICAgIC8vIGhhdmUgZmxhdCBtb2R1bGUgbWV0YWRhdGEgLyBidW5kbGUgaW5kZXgsIHNvIGl0IG1heSBoYXZlIGJlZW4gYW5cbiAgICAgIC8vIG5nX21vZHVsZSB0aGF0J3MgbWlzc2luZyBhIG1vZHVsZV9uYW1lIGF0dHJpYnV0ZS5cbiAgICAgIC8vIEhvd2V2ZXIsIEBhbmd1bGFyL2NvbXBpbGVyIGNhbid0IGJlIGFuIG5nX21vZHVsZSwgYXMgaXQncyB0aGUgaW50ZXJuYWxzXG4gICAgICAvLyBvZiB0aGUgbmdjIGNvbXBpbGVyLCB5ZXQgd2Ugd2FudCB0byBidWlsZCBhbiBuZ19wYWNrYWdlIGZvciBpdC5cbiAgICAgIC8vIFNvIGlnbm9yZSBwYWNrYWdlLmpzb24gZmlsZXMgd2hlbiB3ZSBhcmUgbWlzc2luZyBkYXRhLlxuICAgICAgY29uc29sZS5lcnJvcignV0FSTklORzogbm8gbW9kdWxlIG1ldGFkYXRhIGZvciBwYWNrYWdlJywgcGFja2FnZU5hbWUpO1xuICAgICAgY29uc29sZS5lcnJvcignICAgTm90IHVwZGF0aW5nIHRoZSBwYWNrYWdlLmpzb24gZmlsZSB0byBwb2ludCB0byBpdCcpO1xuICAgICAgY29uc29sZS5lcnJvcihcbiAgICAgICAgICAnICAgVGhlIG5nX21vZHVsZSBmb3IgdGhpcyBwYWNrYWdlIGlzIHBvc3NpYmx5IG1pc3NpbmcgdGhlIG1vZHVsZV9uYW1lIGF0dHJpYnV0ZSAnKTtcbiAgICAgIHJldHVybiBKU09OLnN0cmluZ2lmeShwYXJzZWRQYWNrYWdlLCBudWxsLCAyKTtcbiAgICB9XG5cbiAgICAvLyBJZiB3ZSBndWVzc2VkIHRoZSBpbmRleCBwYXRocyBmb3IgYSBtb2R1bGUsIGFuZCBpdCBjb250YWlucyBhbiBleHBsaWNpdCBgcGFja2FnZS5qc29uYFxuICAgIC8vIGZpbGUgdGhhdCBhbHJlYWR5IHNldHMgZm9ybWF0IHByb3BlcnRpZXMsIHdlIHNraXAgYXV0b21hdGljIGluc2VydGlvbiBvZiBmb3JtYXRcbiAgICAvLyBwcm9wZXJ0aWVzIGJ1dCByZXBvcnQgYSB3YXJuaW5nIGluIGNhc2UgcHJvcGVydGllcyBoYXZlIGJlZW4gc2V0IGJ5IGFjY2lkZW50LlxuICAgIGlmIChtb2R1bGVEYXRhLmd1ZXNzZWRQYXRocyAmJiAhaXNHZW5lcmF0ZWRQYWNrYWdlSnNvbiAmJlxuICAgICAgICBoYXNFeHBsaWNpdEZvcm1hdFByb3BlcnRpZXMocGFyc2VkUGFja2FnZSkpIHtcbiAgICAgIGNvbnNvbGUuZXJyb3IoJ1dBUk5JTkc6IGBwYWNrYWdlLmpzb25gIGV4cGxpY2l0bHkgc2V0cyBmb3JtYXQgcHJvcGVydGllcyAobGlrZSBgbWFpbmApLicpO1xuICAgICAgY29uc29sZS5lcnJvcihcbiAgICAgICAgICAnICAgIFNraXBwaW5nIGF1dG9tYXRpYyBpbnNlcnRpb24gb2YgZm9ybWF0IHByb3BlcnRpZXMgYXMgZXhwbGljaXQgJyArXG4gICAgICAgICAgJ2Zvcm1hdCBwcm9wZXJ0aWVzIGFyZSBzZXQuJyk7XG4gICAgICBjb25zb2xlLmVycm9yKCcgICAgSWdub3JlIHRoaXMgd2FybmluZyBpZiBleHBsaWNpdCBwcm9wZXJ0aWVzIGFyZSBzZXQgaW50ZW50aW9uYWxseS4nKTtcbiAgICAgIHJldHVybiBKU09OLnN0cmluZ2lmeShwYXJzZWRQYWNrYWdlLCBudWxsLCAyKTtcbiAgICB9XG5cbiAgICAvLyBEZXJpdmUgdGhlIHBhdGhzIHRvIHRoZSBmaWxlcyBmcm9tIHRoZSBoYXJkLWNvZGVkIG5hbWVzIHdlIGdhdmUgdGhlbS5cbiAgICAvLyBUT0RPKGFsZXhlYWdsZSk6IGl0IHdvdWxkIGJlIGJldHRlciB0byB0cmFuc2ZlciB0aGlzIGluZm9ybWF0aW9uIGZyb20gdGhlIHBsYWNlXG4gICAgLy8gd2hlcmUgd2UgY3JlYXRlZCB0aGUgZmlsZW5hbWVzLCB2aWEgdGhlIG1vZHVsZXNNYW5pZmVzdEFyZ1xuICAgIHBhcnNlZFBhY2thZ2VbJ21haW4nXSA9IGdldEJ1bmRsZU5hbWUocGFja2FnZU5hbWUsICdidW5kbGVzJyk7XG4gICAgcGFyc2VkUGFja2FnZVsnZmVzbTIwMTUnXSA9IGdldEJ1bmRsZU5hbWUocGFja2FnZU5hbWUsICdmZXNtMjAxNScpO1xuXG4gICAgcGFyc2VkUGFja2FnZVsnZXNtMjAxNSddID0gc3JjRGlyUmVsYXRpdmUocGFja2FnZUpzb24sIG1vZHVsZURhdGFbJ2VzbTIwMTVfaW5kZXgnXSk7XG4gICAgcGFyc2VkUGFja2FnZVsndHlwaW5ncyddID0gc3JjRGlyUmVsYXRpdmUocGFja2FnZUpzb24sIG1vZHVsZURhdGFbJ3R5cGluZ3MnXSk7XG5cbiAgICAvLyBGb3Igbm93LCB3ZSBwb2ludCB0aGUgcHJpbWFyeSBlbnRyeSBwb2ludHMgYXQgdGhlIGZlc20gZmlsZXMsIGJlY2F1c2Ugb2YgV2VicGFja1xuICAgIC8vIHBlcmZvcm1hbmNlIGlzc3VlcyB3aXRoIGEgbGFyZ2UgbnVtYmVyIG9mIGluZGl2aWR1YWwgZmlsZXMuXG4gICAgcGFyc2VkUGFja2FnZVsnbW9kdWxlJ10gPSBwYXJzZWRQYWNrYWdlWydmZXNtMjAxNSddO1xuICAgIHBhcnNlZFBhY2thZ2VbJ2VzMjAxNSddID0gcGFyc2VkUGFja2FnZVsnZmVzbTIwMTUnXTtcblxuICAgIHJldHVybiBKU09OLnN0cmluZ2lmeShwYXJzZWRQYWNrYWdlLCBudWxsLCAyKTtcbiAgfVxuXG4gIC8vIGUuZy4gQGFuZ3VsYXIvY29tbW9uL2h0dHAvdGVzdGluZyAtPiAuLi8uLi9idW5kbGVzL2NvbW1vbi1odHRwLXRlc3RpbmcudW1kLmpzXG4gIC8vIG9yICAgQGFuZ3VsYXIvY29tbW9uL2h0dHAvdGVzdGluZyAtPiAuLi8uLi9mZXNtMjAxNS9odHRwL3Rlc3RpbmcuanNcbiAgZnVuY3Rpb24gZ2V0QnVuZGxlTmFtZShwYWNrYWdlTmFtZTogc3RyaW5nLCBkaXI6IHN0cmluZykge1xuICAgIGNvbnN0IHBhcnRzID0gcGFja2FnZU5hbWUuc3BsaXQoJy8nKTtcbiAgICAvLyBSZW1vdmUgdGhlIHNjb3BlZCBwYWNrYWdlIHBhcnQsIGxpa2UgQGFuZ3VsYXIgaWYgcHJlc2VudFxuICAgIGNvbnN0IG5hbWVQYXJ0cyA9IHBhY2thZ2VOYW1lLnN0YXJ0c1dpdGgoJ0AnKSA/IHBhcnRzLnNwbGljZSgxKSA6IHBhcnRzO1xuICAgIGNvbnN0IHJlbGF0aXZlUGF0aCA9IG5ld0FycmF5KG5hbWVQYXJ0cy5sZW5ndGggLSAxLCAnLi4nKS5qb2luKCcvJykgfHwgJy4nO1xuICAgIGxldCBiYXNlbmFtZTogc3RyaW5nO1xuICAgIGlmIChkaXIgPT09ICdidW5kbGVzJykge1xuICAgICAgYmFzZW5hbWUgPSBuYW1lUGFydHMuam9pbignLScpICsgJy51bWQnO1xuICAgIH0gZWxzZSBpZiAobmFtZVBhcnRzLmxlbmd0aCA9PT0gMSkge1xuICAgICAgYmFzZW5hbWUgPSBuYW1lUGFydHNbMF07XG4gICAgfSBlbHNlIHtcbiAgICAgIGJhc2VuYW1lID0gbmFtZVBhcnRzLnNsaWNlKDEpLmpvaW4oJy8nKTtcbiAgICB9XG4gICAgcmV0dXJuIFtyZWxhdGl2ZVBhdGgsIGRpciwgYmFzZW5hbWUgKyAnLmpzJ10uam9pbignLycpO1xuICB9XG5cbiAgLyoqIFdoZXRoZXIgdGhlIHBhY2thZ2UgZXhwbGljaXRseSBzZXRzIGFueSBvZiB0aGUgZm9ybWF0IHByb3BlcnRpZXMgKGxpa2UgYG1haW5gKS4gKi9cbiAgZnVuY3Rpb24gaGFzRXhwbGljaXRGb3JtYXRQcm9wZXJ0aWVzKHBhcnNlZFBhY2thZ2U6IHtba2V5OiBzdHJpbmddOiBzdHJpbmd9KTogYm9vbGVhbiB7XG4gICAgcmV0dXJuIE9iamVjdC5rZXlzKHBhcnNlZFBhY2thZ2UpXG4gICAgICAgIC5zb21lKHByb3BlcnR5TmFtZSA9PiBrbm93bkZvcm1hdFBhY2thZ2VKc29uRmllbGRzLmluY2x1ZGVzKHByb3BlcnR5TmFtZSkpO1xuICB9XG5cbiAgLyoqIENyZWF0ZXMgbWV0YWRhdGEgcmUtZXhwb3J0IGZpbGUgZm9yIGEgc2Vjb25kYXJ5IGVudHJ5LXBvaW50LiAqL1xuICBmdW5jdGlvbiBjcmVhdGVNZXRhZGF0YVJlZXhwb3J0RmlsZShcbiAgICAgIGVudHJ5UG9pbnROYW1lOiBzdHJpbmcsIG1ldGFkYXRhRmlsZTogc3RyaW5nLCBwYWNrYWdlTmFtZTogc3RyaW5nKSB7XG4gICAgY29uc3QgaW5wdXRQYXRoID0gcGF0aC5qb2luKHNyY0RpciwgYCR7ZW50cnlQb2ludE5hbWV9Lm1ldGFkYXRhLmpzb25gKTtcbiAgICB3cml0ZUZpbGVGcm9tSW5wdXRQYXRoKGlucHV0UGF0aCwgSlNPTi5zdHJpbmdpZnkoe1xuICAgICAgJ19fc3ltYm9saWMnOiAnbW9kdWxlJyxcbiAgICAgICd2ZXJzaW9uJzogMyxcbiAgICAgICdtZXRhZGF0YSc6IHt9LFxuICAgICAgJ2V4cG9ydHMnOlxuICAgICAgICAgIFt7J2Zyb20nOiBgJHtzcmNEaXJSZWxhdGl2ZShpbnB1dFBhdGgsIG1ldGFkYXRhRmlsZS5yZXBsYWNlKC8ubWV0YWRhdGEuanNvbiQvLCAnJykpfWB9XSxcbiAgICAgICdmbGF0TW9kdWxlSW5kZXhSZWRpcmVjdCc6IHRydWUsXG4gICAgICAnaW1wb3J0QXMnOiBwYWNrYWdlTmFtZVxuICAgIH0pICsgJ1xcbicpO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgYSB0eXBpbmdzIChkLnRzKSByZS1leHBvcnQgZmlsZSBmb3IgYSBzZWNvbmRhcnktZW50cnkgcG9pbnQsXG4gICAqIGUuZy4sIGBleHBvcnQgKiBmcm9tICcuL2NvbW1vbi9jb21tb24nYFxuICAgKi9cbiAgZnVuY3Rpb24gY3JlYXRlVHlwaW5nc1JlZXhwb3J0RmlsZShlbnRyeVBvaW50TmFtZTogc3RyaW5nLCBsaWNlbnNlOiBzdHJpbmcsIHR5cGluZ3NGaWxlOiBzdHJpbmcpIHtcbiAgICBjb25zdCBpbnB1dFBhdGggPSBwYXRoLmpvaW4oc3JjRGlyLCBgJHtlbnRyeVBvaW50TmFtZX0uZC50c2ApO1xuICAgIGNvbnN0IGNvbnRlbnQgPSBgJHtsaWNlbnNlfVxuZXhwb3J0ICogZnJvbSAnJHtzcmNEaXJSZWxhdGl2ZShpbnB1dFBhdGgsIHR5cGluZ3NGaWxlLnJlcGxhY2UoL1xcLmRcXC50c3g/JC8sICcnKSl9JztcbmA7XG4gICAgd3JpdGVGaWxlRnJvbUlucHV0UGF0aChpbnB1dFBhdGgsIGNvbnRlbnQpO1xuICB9XG5cbiAgLyoqXG4gICAqIENyZWF0ZXMgYSBwYWNrYWdlLmpzb24gZm9yIGEgc2Vjb25kYXJ5IGVudHJ5LXBvaW50LlxuICAgKiBAcGFyYW0gZGlyIFRoZSBkaXJlY3RvcnkgdW5kZXIgd2hpY2ggdGhlIHBhY2thZ2UuanNvbiBzaG91bGQgYmUgd3JpdHRlbi5cbiAgICogQHBhcmFtIGVudHJ5UG9pbnRQYWNrYWdlTmFtZSBUaGUgZnVsbCBwYWNrYWdlIG5hbWUgZm9yIHRoZSBlbnRyeSBwb2ludCxcbiAgICogICAgIGUuZy4gJ0Bhbmd1bGFyL2NvbW1vbi9odHRwJy5cbiAgICovXG4gIGZ1bmN0aW9uIGNyZWF0ZUVudHJ5UG9pbnRQYWNrYWdlSnNvbihkaXI6IHN0cmluZywgZW50cnlQb2ludFBhY2thZ2VOYW1lOiBzdHJpbmcpIHtcbiAgICBjb25zdCBwa2dKc29uID0gcGF0aC5qb2luKHNyY0RpciwgZGlyLCAncGFja2FnZS5qc29uJyk7XG4gICAgY29uc3QgY29udGVudCA9IGFtZW5kUGFja2FnZUpzb24ocGtnSnNvbiwge25hbWU6IGVudHJ5UG9pbnRQYWNrYWdlTmFtZX0sIHRydWUpO1xuICAgIHdyaXRlRmlsZUZyb21JbnB1dFBhdGgocGtnSnNvbiwgY29udGVudCk7XG4gIH1cblxuICAvKipcbiAgICogTm9ybWFsaXplcyB0aGUgc3BlY2lmaWVkIHBhdGggYnkgcmVwbGFjaW5nIGJhY2tzbGFzaCBzZXBhcmF0b3JzIHdpdGggUG9zaXhcbiAgICogZm9yd2FyZCBzbGFzaCBzZXBhcmF0b3JzLlxuICAgKi9cbiAgZnVuY3Rpb24gbm9ybWFsaXplU2VwYXJhdG9ycyhwYXRoOiBzdHJpbmcpOiBzdHJpbmcge1xuICAgIHJldHVybiBwYXRoLnJlcGxhY2UoL1xcXFwvZywgJy8nKTtcbiAgfVxuXG4gIC8qKlxuICAgKiBSZXdpcmVzIG1ldGFkYXRhIHRvIHBvaW50IHRvIHRoZSBmbGF0dGVuZWQgZHRzIGZpbGUuXG4gICAqXG4gICAqIEBwYXJhbSBtZXRhZGF0YVBhdGggdGhlIG1ldGFkYXRhIGZpbGUgcGF0aFxuICAgKiBAcGFyYW0gdHlwaW5nc1BhdGggdGhlIHR5cGluZ3MgYnVuZGxlIGVudHJ5cG9pbnRcbiAgICovXG4gIGZ1bmN0aW9uIHJld2lyZU1ldGFkYXRhKG1ldGFkYXRhUGF0aDogc3RyaW5nLCB0eXBpbmdzUGF0aDogc3RyaW5nKTogc3RyaW5nIHtcbiAgICBjb25zdCBtZXRhZGF0YSA9IEpTT04ucGFyc2UoZnMucmVhZEZpbGVTeW5jKG1ldGFkYXRhUGF0aCwgJ3V0Zi04JykpIGFzIHtba2V5OiBzdHJpbmddOiBhbnl9O1xuXG4gICAgbGV0IHR5cGluZ3NSZWxhdGl2ZVBhdGggPVxuICAgICAgICBub3JtYWxpemVTZXBhcmF0b3JzKHBhdGgucmVsYXRpdmUocGF0aC5kaXJuYW1lKG1ldGFkYXRhUGF0aCksIHR5cGluZ3NQYXRoKSk7XG4gICAgaWYgKCF0eXBpbmdzUmVsYXRpdmVQYXRoLnN0YXJ0c1dpdGgoJy4uJykpIHtcbiAgICAgIHR5cGluZ3NSZWxhdGl2ZVBhdGggPSBgLi8ke3R5cGluZ3NSZWxhdGl2ZVBhdGh9YDtcbiAgICB9XG5cbiAgICB0eXBpbmdzUmVsYXRpdmVQYXRoID0gdHlwaW5nc1JlbGF0aXZlUGF0aC5yZXBsYWNlKCcuZC50cycsICcnKTtcblxuICAgIC8vIHRoZSByZWdleHAgaGVyZSBjYXRjaGVzIGFsbCByZWxhdGl2ZSBwYXRocyBzdWNoIGFzOlxuICAgIC8vIC4vc3JjL2NvcmUvZm9vLmQudHMgYW5kIC4uL3NyYy9jb3JlL2Zvby5kLnRzXG4gICAgY29uc3QgcmVsYXRpdmVQYXRoUmVnZXggPSAvXFwuP1xcLlxcL1tcXHdcXC5cXC1fXFwvXSsvZztcbiAgICBpZiAobWV0YWRhdGEuZXhwb3J0cykge1xuICAgICAgLy8gU3RyaXAgcmUtZXhwb3J0cyB3aGljaCBhcmUgbm93IHNlbGYtcmVmZXJlbmNlc1xuICAgICAgbWV0YWRhdGEuZXhwb3J0cyA9XG4gICAgICAgICAgbWV0YWRhdGEuZXhwb3J0cy5maWx0ZXIoKGU6IHtmcm9tOiBzdHJpbmd9KSA9PiAhZS5mcm9tLm1hdGNoKHJlbGF0aXZlUGF0aFJlZ2V4KSk7XG4gICAgfVxuICAgIHJldHVybiBKU09OLnN0cmluZ2lmeShtZXRhZGF0YSkucmVwbGFjZShyZWxhdGl2ZVBhdGhSZWdleCwgdHlwaW5nc1JlbGF0aXZlUGF0aCk7XG4gIH1cblxuICAvKipcbiAgICogU3RyaXAgdGhlIG5hbWVkIEFNRCBtb2R1bGUgZm9yIGNvbXBhdGliaWxpdHkgd2l0aCBub24tYmF6ZWwgdXNlcnMgZnJvbSB0eXBpbmdzIGNvbnRlbnRcbiAgICogQHBhcmFtIGZpbGVQYXRoIGR0cyBmaWxlIHBhdGhcbiAgICovXG4gIGZ1bmN0aW9uIHJlYWRUeXBpbmdzQW5kU3RyaXBBbWRNb2R1bGUoZmlsZVBhdGg6IHN0cmluZyk6IHN0cmluZyB7XG4gICAgcmV0dXJuIGZzXG4gICAgICAgIC5yZWFkRmlsZVN5bmMoZmlsZVBhdGgsICd1dGYtOCcpXG4gICAgICAgIC8vIFN0cmlwIHRoZSBuYW1lZCBBTUQgbW9kdWxlIGZvciBjb21wYXRpYmlsaXR5IHdpdGggbm9uLWJhemVsIHVzZXJzXG4gICAgICAgIC5yZXBsYWNlKC9eXFwvXFwvXFwvIDxhbWQtbW9kdWxlIG5hbWU9LipcXC8+W1xcclxcbl0rL2dtLCAnJyk7XG4gIH1cbn1cblxuaWYgKHJlcXVpcmUubWFpbiA9PT0gbW9kdWxlKSB7XG4gIHByb2Nlc3MuZXhpdENvZGUgPSBtYWluKHByb2Nlc3MuYXJndi5zbGljZSgyKSk7XG59XG5cbmV4cG9ydCBmdW5jdGlvbiBuZXdBcnJheTxUID0gYW55PihzaXplOiBudW1iZXIpOiBUW107XG5leHBvcnQgZnVuY3Rpb24gbmV3QXJyYXk8VD4oc2l6ZTogbnVtYmVyLCB2YWx1ZTogVCk6IFRbXTtcbmV4cG9ydCBmdW5jdGlvbiBuZXdBcnJheTxUPihzaXplOiBudW1iZXIsIHZhbHVlPzogVCk6IFRbXSB7XG4gIGNvbnN0IGxpc3Q6IFRbXSA9IFtdO1xuICBmb3IgKGxldCBpID0gMDsgaSA8IHNpemU7IGkrKykge1xuICAgIGxpc3QucHVzaCh2YWx1ZSEpO1xuICB9XG4gIHJldHVybiBsaXN0O1xufVxuIl19